/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module b01_C(LINE1, LINE2, STATO_REG_2__SCAN_IN, STATO_REG_1__SCAN_IN, STATO_REG_0__SCAN_IN, U45, U36, U35, U44, U34);
  input LINE1;
  wire LINE1;
  input LINE2;
  wire LINE2;
  input STATO_REG_2__SCAN_IN;
  wire STATO_REG_2__SCAN_IN;
  input STATO_REG_1__SCAN_IN;
  wire STATO_REG_1__SCAN_IN;
  input STATO_REG_0__SCAN_IN;
  wire STATO_REG_0__SCAN_IN;
  output U45;
  wire U45;
  output U36;
  wire U36;
  output U35;
  wire U35;
  output U44;
  wire U44;
  output U34;
  wire U34;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  INV_X1 _19_ (
    .A(STATO_REG_2__SCAN_IN),
    .ZN(_00_)
  );
  NAND2_X1 _20_ (
    .A1(LINE2),
    .A2(LINE1),
    .ZN(_01_)
  );
  AOI21_X1 _21_ (
    .A(STATO_REG_1__SCAN_IN),
    .B1(STATO_REG_0__SCAN_IN),
    .B2(_01_),
    .ZN(_02_)
  );
  OAI211_X1 _22_ (
    .A(_00_),
    .B(_02_),
    .C1(_01_),
    .C2(STATO_REG_0__SCAN_IN),
    .ZN(_03_)
  );
  INV_X1 _23_ (
    .A(STATO_REG_1__SCAN_IN),
    .ZN(_04_)
  );
  INV_X1 _24_ (
    .A(STATO_REG_0__SCAN_IN),
    .ZN(_05_)
  );
  NOR3_X1 _25_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(_04_),
    .A3(_05_),
    .ZN(U34)
  );
  NAND2_X1 _26_ (
    .A1(_01_),
    .A2(U34),
    .ZN(_06_)
  );
  OR3_X1 _27_ (
    .A1(_04_),
    .A2(STATO_REG_0__SCAN_IN),
    .A3(_01_),
    .ZN(_07_)
  );
  NAND2_X1 _28_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_05_),
    .ZN(_08_)
  );
  OAI211_X1 _29_ (
    .A(STATO_REG_2__SCAN_IN),
    .B(_08_),
    .C1(LINE1),
    .C2(LINE2),
    .ZN(_09_)
  );
  NAND4_X1 _30_ (
    .A1(_03_),
    .A2(_06_),
    .A3(_07_),
    .A4(_09_),
    .ZN(U35)
  );
  AOI21_X1 _31_ (
    .A(_08_),
    .B1(_01_),
    .B2(STATO_REG_2__SCAN_IN),
    .ZN(_10_)
  );
  NOR2_X1 _32_ (
    .A1(LINE2),
    .A2(LINE1),
    .ZN(_11_)
  );
  AOI22_X1 _33_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_01_),
    .B1(_11_),
    .B2(STATO_REG_2__SCAN_IN),
    .ZN(_12_)
  );
  NAND2_X1 _34_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(STATO_REG_0__SCAN_IN),
    .ZN(_13_)
  );
  OAI22_X1 _35_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_12_),
    .B1(_13_),
    .B2(_11_),
    .ZN(_14_)
  );
  OR2_X1 _36_ (
    .A1(_10_),
    .A2(_14_),
    .ZN(U36)
  );
  NAND2_X1 _37_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(_08_),
    .ZN(_15_)
  );
  XOR2_X1 _38_ (
    .A(LINE2),
    .B(LINE1),
    .Z(_16_)
  );
  XNOR2_X1 _39_ (
    .A(_15_),
    .B(_16_),
    .ZN(U44)
  );
  NAND2_X1 _40_ (
    .A1(_01_),
    .A2(_08_),
    .ZN(_17_)
  );
  AOI21_X1 _41_ (
    .A(STATO_REG_1__SCAN_IN),
    .B1(_05_),
    .B2(_11_),
    .ZN(_18_)
  );
  MUX2_X1 _42_ (
    .A(_17_),
    .B(_18_),
    .S(STATO_REG_2__SCAN_IN),
    .Z(U45)
  );
endmodule
