/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module b02_C(LINEA, STATO_REG_2__SCAN_IN, STATO_REG_1__SCAN_IN, STATO_REG_0__SCAN_IN, U33, U38, U32, U31);
  input LINEA;
  wire LINEA;
  input STATO_REG_2__SCAN_IN;
  wire STATO_REG_2__SCAN_IN;
  input STATO_REG_1__SCAN_IN;
  wire STATO_REG_1__SCAN_IN;
  input STATO_REG_0__SCAN_IN;
  wire STATO_REG_0__SCAN_IN;
  output U33;
  wire U33;
  output U38;
  wire U38;
  output U32;
  wire U32;
  output U31;
  wire U31;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  INV_X1 _09_ (
    .A(STATO_REG_2__SCAN_IN),
    .ZN(_08_)
  );
  NOR3_X1 _10_ (
    .A1(_08_),
    .A2(STATO_REG_0__SCAN_IN),
    .A3(STATO_REG_1__SCAN_IN),
    .ZN(U31)
  );
  INV_X1 _11_ (
    .A(LINEA),
    .ZN(_00_)
  );
  OAI21_X1 _12_ (
    .A(STATO_REG_0__SCAN_IN),
    .B1(_00_),
    .B2(STATO_REG_2__SCAN_IN),
    .ZN(_01_)
  );
  OAI21_X1 _13_ (
    .A(STATO_REG_1__SCAN_IN),
    .B1(LINEA),
    .B2(STATO_REG_2__SCAN_IN),
    .ZN(_02_)
  );
  AND2_X1 _14_ (
    .A1(_01_),
    .A2(_02_),
    .ZN(U32)
  );
  INV_X1 _15_ (
    .A(STATO_REG_0__SCAN_IN),
    .ZN(_03_)
  );
  NOR3_X1 _16_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(STATO_REG_1__SCAN_IN),
    .A3(LINEA),
    .ZN(_04_)
  );
  NOR2_X1 _17_ (
    .A1(_08_),
    .A2(_00_),
    .ZN(_05_)
  );
  OAI22_X1 _18_ (
    .A1(_03_),
    .A2(_04_),
    .B1(_05_),
    .B2(_02_),
    .ZN(U33)
  );
  NAND3_X1 _19_ (
    .A1(_08_),
    .A2(_03_),
    .A3(STATO_REG_1__SCAN_IN),
    .ZN(_06_)
  );
  AND2_X1 _20_ (
    .A1(_08_),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_07_)
  );
  OAI21_X1 _21_ (
    .A(_06_),
    .B1(_07_),
    .B2(_01_),
    .ZN(U38)
  );
endmodule
