/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module b03_C(STATO_REG_0__SCAN_IN, REQUEST1, REQUEST2, REQUEST3, REQUEST4, CODA0_REG_2__SCAN_IN, CODA0_REG_1__SCAN_IN, CODA0_REG_0__SCAN_IN, CODA1_REG_2__SCAN_IN, CODA1_REG_1__SCAN_IN, CODA1_REG_0__SCAN_IN, CODA2_REG_2__SCAN_IN, CODA2_REG_1__SCAN_IN, CODA2_REG_0__SCAN_IN, CODA3_REG_2__SCAN_IN, CODA3_REG_1__SCAN_IN, CODA3_REG_0__SCAN_IN, GRANT_REG_3__SCAN_IN, GRANT_REG_2__SCAN_IN, GRANT_REG_1__SCAN_IN, GRANT_REG_0__SCAN_IN
, GRANT_O_REG_3__SCAN_IN, GRANT_O_REG_2__SCAN_IN, GRANT_O_REG_1__SCAN_IN, GRANT_O_REG_0__SCAN_IN, RU3_REG_SCAN_IN, FU1_REG_SCAN_IN, FU3_REG_SCAN_IN, RU1_REG_SCAN_IN, RU4_REG_SCAN_IN, FU2_REG_SCAN_IN, FU4_REG_SCAN_IN, RU2_REG_SCAN_IN, STATO_REG_1__SCAN_IN, U217, U216, U215, U214, U213, U212, U211, U210
, U209, U208, U207, U206, U229, U230, U231, U232, U233, U234, U235, U236, U237, U205, U238, U204, U239, U240, U241, U242, U203
);
  input STATO_REG_0__SCAN_IN;
  wire STATO_REG_0__SCAN_IN;
  input REQUEST1;
  wire REQUEST1;
  input REQUEST2;
  wire REQUEST2;
  input REQUEST3;
  wire REQUEST3;
  input REQUEST4;
  wire REQUEST4;
  input CODA0_REG_2__SCAN_IN;
  wire CODA0_REG_2__SCAN_IN;
  input CODA0_REG_1__SCAN_IN;
  wire CODA0_REG_1__SCAN_IN;
  input CODA0_REG_0__SCAN_IN;
  wire CODA0_REG_0__SCAN_IN;
  input CODA1_REG_2__SCAN_IN;
  wire CODA1_REG_2__SCAN_IN;
  input CODA1_REG_1__SCAN_IN;
  wire CODA1_REG_1__SCAN_IN;
  input CODA1_REG_0__SCAN_IN;
  wire CODA1_REG_0__SCAN_IN;
  input CODA2_REG_2__SCAN_IN;
  wire CODA2_REG_2__SCAN_IN;
  input CODA2_REG_1__SCAN_IN;
  wire CODA2_REG_1__SCAN_IN;
  input CODA2_REG_0__SCAN_IN;
  wire CODA2_REG_0__SCAN_IN;
  input CODA3_REG_2__SCAN_IN;
  wire CODA3_REG_2__SCAN_IN;
  input CODA3_REG_1__SCAN_IN;
  wire CODA3_REG_1__SCAN_IN;
  input CODA3_REG_0__SCAN_IN;
  wire CODA3_REG_0__SCAN_IN;
  input GRANT_REG_3__SCAN_IN;
  wire GRANT_REG_3__SCAN_IN;
  input GRANT_REG_2__SCAN_IN;
  wire GRANT_REG_2__SCAN_IN;
  input GRANT_REG_1__SCAN_IN;
  wire GRANT_REG_1__SCAN_IN;
  input GRANT_REG_0__SCAN_IN;
  wire GRANT_REG_0__SCAN_IN;
  input GRANT_O_REG_3__SCAN_IN;
  wire GRANT_O_REG_3__SCAN_IN;
  input GRANT_O_REG_2__SCAN_IN;
  wire GRANT_O_REG_2__SCAN_IN;
  input GRANT_O_REG_1__SCAN_IN;
  wire GRANT_O_REG_1__SCAN_IN;
  input GRANT_O_REG_0__SCAN_IN;
  wire GRANT_O_REG_0__SCAN_IN;
  input RU3_REG_SCAN_IN;
  wire RU3_REG_SCAN_IN;
  input FU1_REG_SCAN_IN;
  wire FU1_REG_SCAN_IN;
  input FU3_REG_SCAN_IN;
  wire FU3_REG_SCAN_IN;
  input RU1_REG_SCAN_IN;
  wire RU1_REG_SCAN_IN;
  input RU4_REG_SCAN_IN;
  wire RU4_REG_SCAN_IN;
  input FU2_REG_SCAN_IN;
  wire FU2_REG_SCAN_IN;
  input FU4_REG_SCAN_IN;
  wire FU4_REG_SCAN_IN;
  input RU2_REG_SCAN_IN;
  wire RU2_REG_SCAN_IN;
  input STATO_REG_1__SCAN_IN;
  wire STATO_REG_1__SCAN_IN;
  output U217;
  wire U217;
  output U216;
  wire U216;
  output U215;
  wire U215;
  output U214;
  wire U214;
  output U213;
  wire U213;
  output U212;
  wire U212;
  output U211;
  wire U211;
  output U210;
  wire U210;
  output U209;
  wire U209;
  output U208;
  wire U208;
  output U207;
  wire U207;
  output U206;
  wire U206;
  output U229;
  wire U229;
  output U230;
  wire U230;
  output U231;
  wire U231;
  output U232;
  wire U232;
  output U233;
  wire U233;
  output U234;
  wire U234;
  output U235;
  wire U235;
  output U236;
  wire U236;
  output U237;
  wire U237;
  output U205;
  wire U205;
  output U238;
  wire U238;
  output U204;
  wire U204;
  output U239;
  wire U239;
  output U240;
  wire U240;
  output U241;
  wire U241;
  output U242;
  wire U242;
  output U203;
  wire U203;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  BUF_X1 _050_ (
    .A(STATO_REG_0__SCAN_IN),
    .Z(_021_)
  );
  MUX2_X1 _051_ (
    .A(REQUEST1),
    .B(RU1_REG_SCAN_IN),
    .S(_021_),
    .Z(U204)
  );
  MUX2_X1 _052_ (
    .A(FU1_REG_SCAN_IN),
    .B(RU1_REG_SCAN_IN),
    .S(_021_),
    .Z(U205)
  );
  INV_X1 _053_ (
    .A(FU1_REG_SCAN_IN),
    .ZN(_022_)
  );
  INV_X1 _054_ (
    .A(RU1_REG_SCAN_IN),
    .ZN(_023_)
  );
  OAI21_X1 _055_ (
    .A(STATO_REG_0__SCAN_IN),
    .B1(_022_),
    .B2(_023_),
    .ZN(_024_)
  );
  INV_X1 _056_ (
    .A(FU2_REG_SCAN_IN),
    .ZN(_025_)
  );
  NOR3_X1 _057_ (
    .A1(RU2_REG_SCAN_IN),
    .A2(RU3_REG_SCAN_IN),
    .A3(FU4_REG_SCAN_IN),
    .ZN(_026_)
  );
  AOI221_X1 _058_ (
    .A(RU1_REG_SCAN_IN),
    .B1(RU2_REG_SCAN_IN),
    .B2(_025_),
    .C1(RU4_REG_SCAN_IN),
    .C2(_026_),
    .ZN(_027_)
  );
  INV_X1 _059_ (
    .A(RU3_REG_SCAN_IN),
    .ZN(_028_)
  );
  OR3_X1 _060_ (
    .A1(RU2_REG_SCAN_IN),
    .A2(_028_),
    .A3(FU3_REG_SCAN_IN),
    .ZN(_029_)
  );
  AOI211_X1 _061_ (
    .A(STATO_REG_1__SCAN_IN),
    .B(_024_),
    .C1(_027_),
    .C2(_029_),
    .ZN(_030_)
  );
  BUF_X1 _062_ (
    .A(_030_),
    .Z(_031_)
  );
  NAND2_X1 _063_ (
    .A1(CODA2_REG_0__SCAN_IN),
    .A2(_031_),
    .ZN(_032_)
  );
  AOI21_X1 _064_ (
    .A(_024_),
    .B1(_027_),
    .B2(_029_),
    .ZN(_033_)
  );
  INV_X1 _065_ (
    .A(STATO_REG_1__SCAN_IN),
    .ZN(_034_)
  );
  NOR3_X1 _066_ (
    .A1(FU3_REG_SCAN_IN),
    .A2(FU2_REG_SCAN_IN),
    .A3(FU4_REG_SCAN_IN),
    .ZN(_035_)
  );
  AOI21_X1 _067_ (
    .A(_034_),
    .B1(_035_),
    .B2(_022_),
    .ZN(_036_)
  );
  OR2_X1 _068_ (
    .A1(_033_),
    .A2(_036_),
    .ZN(_037_)
  );
  BUF_X1 _069_ (
    .A(_037_),
    .Z(_038_)
  );
  INV_X1 _070_ (
    .A(CODA3_REG_0__SCAN_IN),
    .ZN(_039_)
  );
  OAI21_X1 _071_ (
    .A(_032_),
    .B1(_038_),
    .B2(_039_),
    .ZN(U206)
  );
  NAND2_X1 _072_ (
    .A1(CODA2_REG_1__SCAN_IN),
    .A2(_031_),
    .ZN(_040_)
  );
  INV_X1 _073_ (
    .A(CODA3_REG_1__SCAN_IN),
    .ZN(_041_)
  );
  OAI21_X1 _074_ (
    .A(_040_),
    .B1(_038_),
    .B2(_041_),
    .ZN(U207)
  );
  NAND2_X1 _075_ (
    .A1(CODA2_REG_2__SCAN_IN),
    .A2(_031_),
    .ZN(_042_)
  );
  INV_X1 _076_ (
    .A(CODA3_REG_2__SCAN_IN),
    .ZN(_043_)
  );
  OAI21_X1 _077_ (
    .A(_042_),
    .B1(_038_),
    .B2(_043_),
    .ZN(U208)
  );
  NAND2_X1 _078_ (
    .A1(CODA1_REG_0__SCAN_IN),
    .A2(_031_),
    .ZN(_044_)
  );
  OAI21_X1 _079_ (
    .A(STATO_REG_1__SCAN_IN),
    .B1(_033_),
    .B2(_036_),
    .ZN(_045_)
  );
  INV_X1 _080_ (
    .A(CODA2_REG_0__SCAN_IN),
    .ZN(_046_)
  );
  OAI221_X1 _081_ (
    .A(_044_),
    .B1(_045_),
    .B2(_039_),
    .C1(_046_),
    .C2(_038_),
    .ZN(U209)
  );
  NAND2_X1 _082_ (
    .A1(CODA1_REG_1__SCAN_IN),
    .A2(_031_),
    .ZN(_047_)
  );
  INV_X1 _083_ (
    .A(CODA2_REG_1__SCAN_IN),
    .ZN(_048_)
  );
  OAI221_X1 _084_ (
    .A(_047_),
    .B1(_045_),
    .B2(_041_),
    .C1(_048_),
    .C2(_038_),
    .ZN(U210)
  );
  NAND2_X1 _085_ (
    .A1(CODA1_REG_2__SCAN_IN),
    .A2(_031_),
    .ZN(_049_)
  );
  INV_X1 _086_ (
    .A(CODA2_REG_2__SCAN_IN),
    .ZN(_000_)
  );
  OAI221_X1 _087_ (
    .A(_049_),
    .B1(_045_),
    .B2(_043_),
    .C1(_000_),
    .C2(_038_),
    .ZN(U211)
  );
  NAND2_X1 _088_ (
    .A1(CODA0_REG_0__SCAN_IN),
    .A2(_031_),
    .ZN(_001_)
  );
  INV_X1 _089_ (
    .A(CODA1_REG_0__SCAN_IN),
    .ZN(_002_)
  );
  OAI221_X1 _090_ (
    .A(_001_),
    .B1(_038_),
    .B2(_002_),
    .C1(_046_),
    .C2(_045_),
    .ZN(U212)
  );
  NAND2_X1 _091_ (
    .A1(CODA0_REG_1__SCAN_IN),
    .A2(_031_),
    .ZN(_003_)
  );
  INV_X1 _092_ (
    .A(CODA1_REG_1__SCAN_IN),
    .ZN(_004_)
  );
  OAI221_X1 _093_ (
    .A(_003_),
    .B1(_038_),
    .B2(_004_),
    .C1(_048_),
    .C2(_045_),
    .ZN(U213)
  );
  NAND2_X1 _094_ (
    .A1(CODA0_REG_2__SCAN_IN),
    .A2(_031_),
    .ZN(_005_)
  );
  INV_X1 _095_ (
    .A(CODA1_REG_2__SCAN_IN),
    .ZN(_006_)
  );
  OAI221_X1 _096_ (
    .A(_005_),
    .B1(_038_),
    .B2(_006_),
    .C1(_000_),
    .C2(_045_),
    .ZN(U214)
  );
  INV_X1 _097_ (
    .A(CODA0_REG_0__SCAN_IN),
    .ZN(_007_)
  );
  NAND2_X1 _098_ (
    .A1(_023_),
    .A2(_030_),
    .ZN(_008_)
  );
  OAI222_X1 _099_ (
    .A1(_007_),
    .A2(_038_),
    .B1(_008_),
    .B2(RU2_REG_SCAN_IN),
    .C1(_045_),
    .C2(_002_),
    .ZN(U215)
  );
  OAI211_X1 _100_ (
    .A(_023_),
    .B(_030_),
    .C1(_028_),
    .C2(RU2_REG_SCAN_IN),
    .ZN(_009_)
  );
  INV_X1 _101_ (
    .A(CODA0_REG_1__SCAN_IN),
    .ZN(_010_)
  );
  OAI221_X1 _102_ (
    .A(_009_),
    .B1(_037_),
    .B2(_010_),
    .C1(_004_),
    .C2(_045_),
    .ZN(U216)
  );
  OAI21_X1 _103_ (
    .A(_023_),
    .B1(RU2_REG_SCAN_IN),
    .B2(RU3_REG_SCAN_IN),
    .ZN(_011_)
  );
  NAND2_X1 _104_ (
    .A1(_031_),
    .A2(_011_),
    .ZN(_012_)
  );
  INV_X1 _105_ (
    .A(CODA0_REG_2__SCAN_IN),
    .ZN(_013_)
  );
  OAI221_X1 _106_ (
    .A(_012_),
    .B1(_037_),
    .B2(_013_),
    .C1(_006_),
    .C2(_045_),
    .ZN(U217)
  );
  INV_X1 _107_ (
    .A(GRANT_REG_3__SCAN_IN),
    .ZN(_014_)
  );
  NAND2_X1 _108_ (
    .A1(CODA0_REG_2__SCAN_IN),
    .A2(_036_),
    .ZN(_015_)
  );
  NAND2_X1 _109_ (
    .A1(_007_),
    .A2(_010_),
    .ZN(_016_)
  );
  OAI22_X1 _110_ (
    .A1(_014_),
    .A2(_036_),
    .B1(_015_),
    .B2(_016_),
    .ZN(U229)
  );
  NOR3_X1 _111_ (
    .A1(CODA0_REG_0__SCAN_IN),
    .A2(_010_),
    .A3(CODA0_REG_2__SCAN_IN),
    .ZN(_017_)
  );
  MUX2_X1 _112_ (
    .A(GRANT_REG_2__SCAN_IN),
    .B(_017_),
    .S(_036_),
    .Z(U230)
  );
  NOR3_X1 _113_ (
    .A1(_007_),
    .A2(CODA0_REG_1__SCAN_IN),
    .A3(CODA0_REG_2__SCAN_IN),
    .ZN(_018_)
  );
  MUX2_X1 _114_ (
    .A(GRANT_REG_1__SCAN_IN),
    .B(_018_),
    .S(_036_),
    .Z(U231)
  );
  INV_X1 _115_ (
    .A(GRANT_REG_0__SCAN_IN),
    .ZN(_019_)
  );
  NAND2_X1 _116_ (
    .A1(CODA0_REG_0__SCAN_IN),
    .A2(CODA0_REG_1__SCAN_IN),
    .ZN(_020_)
  );
  OAI22_X1 _117_ (
    .A1(_019_),
    .A2(_036_),
    .B1(_015_),
    .B2(_020_),
    .ZN(U232)
  );
  MUX2_X1 _118_ (
    .A(GRANT_O_REG_3__SCAN_IN),
    .B(GRANT_REG_3__SCAN_IN),
    .S(_021_),
    .Z(U233)
  );
  MUX2_X1 _119_ (
    .A(GRANT_O_REG_2__SCAN_IN),
    .B(GRANT_REG_2__SCAN_IN),
    .S(_021_),
    .Z(U234)
  );
  MUX2_X1 _120_ (
    .A(GRANT_O_REG_1__SCAN_IN),
    .B(GRANT_REG_1__SCAN_IN),
    .S(_021_),
    .Z(U235)
  );
  MUX2_X1 _121_ (
    .A(GRANT_O_REG_0__SCAN_IN),
    .B(GRANT_REG_0__SCAN_IN),
    .S(_021_),
    .Z(U236)
  );
  MUX2_X1 _122_ (
    .A(REQUEST3),
    .B(RU3_REG_SCAN_IN),
    .S(_021_),
    .Z(U237)
  );
  MUX2_X1 _123_ (
    .A(FU3_REG_SCAN_IN),
    .B(RU3_REG_SCAN_IN),
    .S(_021_),
    .Z(U238)
  );
  MUX2_X1 _124_ (
    .A(REQUEST4),
    .B(RU4_REG_SCAN_IN),
    .S(_021_),
    .Z(U239)
  );
  MUX2_X1 _125_ (
    .A(FU2_REG_SCAN_IN),
    .B(RU2_REG_SCAN_IN),
    .S(STATO_REG_0__SCAN_IN),
    .Z(U240)
  );
  MUX2_X1 _126_ (
    .A(FU4_REG_SCAN_IN),
    .B(RU4_REG_SCAN_IN),
    .S(STATO_REG_0__SCAN_IN),
    .Z(U241)
  );
  MUX2_X1 _127_ (
    .A(REQUEST2),
    .B(RU2_REG_SCAN_IN),
    .S(STATO_REG_0__SCAN_IN),
    .Z(U242)
  );
  INV_X1 _128_ (
    .A(_021_),
    .ZN(U203)
  );
endmodule
