/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module b04_C(RESTART, AVERAGE, ENABLE, DATA_IN_7_, DATA_IN_6_, DATA_IN_5_, DATA_IN_4_, DATA_IN_3_, DATA_IN_2_, DATA_IN_1_, DATA_IN_0_, STATO_REG_0__SCAN_IN, STATO_REG_1__SCAN_IN, DATA_OUT_REG_0__SCAN_IN, DATA_OUT_REG_1__SCAN_IN, DATA_OUT_REG_2__SCAN_IN, DATA_OUT_REG_3__SCAN_IN, DATA_OUT_REG_4__SCAN_IN, DATA_OUT_REG_5__SCAN_IN, DATA_OUT_REG_6__SCAN_IN, DATA_OUT_REG_7__SCAN_IN
, REG4_REG_0__SCAN_IN, REG4_REG_1__SCAN_IN, REG4_REG_2__SCAN_IN, RMAX_REG_7__SCAN_IN, RMAX_REG_6__SCAN_IN, RMAX_REG_5__SCAN_IN, RMAX_REG_4__SCAN_IN, RMAX_REG_3__SCAN_IN, RMAX_REG_2__SCAN_IN, RMAX_REG_1__SCAN_IN, RMAX_REG_0__SCAN_IN, RMIN_REG_7__SCAN_IN, RMIN_REG_6__SCAN_IN, RMIN_REG_5__SCAN_IN, RMIN_REG_4__SCAN_IN, RMIN_REG_3__SCAN_IN, RMIN_REG_2__SCAN_IN, RMIN_REG_1__SCAN_IN, RMIN_REG_0__SCAN_IN, RLAST_REG_7__SCAN_IN, RLAST_REG_6__SCAN_IN
, RLAST_REG_5__SCAN_IN, RLAST_REG_4__SCAN_IN, RLAST_REG_3__SCAN_IN, RLAST_REG_2__SCAN_IN, RLAST_REG_1__SCAN_IN, RLAST_REG_0__SCAN_IN, REG1_REG_7__SCAN_IN, REG1_REG_6__SCAN_IN, REG1_REG_5__SCAN_IN, REG1_REG_4__SCAN_IN, REG1_REG_3__SCAN_IN, REG1_REG_2__SCAN_IN, REG1_REG_1__SCAN_IN, REG1_REG_0__SCAN_IN, REG2_REG_7__SCAN_IN, REG2_REG_6__SCAN_IN, REG2_REG_5__SCAN_IN, REG2_REG_4__SCAN_IN, REG2_REG_3__SCAN_IN, REG2_REG_2__SCAN_IN, REG2_REG_1__SCAN_IN
, REG2_REG_0__SCAN_IN, REG3_REG_7__SCAN_IN, REG3_REG_6__SCAN_IN, REG3_REG_5__SCAN_IN, REG3_REG_4__SCAN_IN, REG3_REG_3__SCAN_IN, REG3_REG_2__SCAN_IN, REG3_REG_1__SCAN_IN, REG3_REG_0__SCAN_IN, REG4_REG_7__SCAN_IN, REG4_REG_6__SCAN_IN, REG4_REG_5__SCAN_IN, REG4_REG_4__SCAN_IN, REG4_REG_3__SCAN_IN, U344, U343, U342, U341, U340, U339, U338
, U337, U336, U335, U334, U333, U332, U331, U330, U329, U328, U327, U326, U325, U324, U323, U322, U321, U320, U319, U318, U317
, U316, U315, U314, U313, U312, U311, U310, U309, U308, U307, U306, U305, U304, U303, U302, U301, U300, U299, U298, U297, U296
, U295, U294, U293, U292, U291, U290, U289, U288, U287, U286, U285, U284, U283, U282, U281, U280, U375);
  input RESTART;
  wire RESTART;
  input AVERAGE;
  wire AVERAGE;
  input ENABLE;
  wire ENABLE;
  input DATA_IN_7_;
  wire DATA_IN_7_;
  input DATA_IN_6_;
  wire DATA_IN_6_;
  input DATA_IN_5_;
  wire DATA_IN_5_;
  input DATA_IN_4_;
  wire DATA_IN_4_;
  input DATA_IN_3_;
  wire DATA_IN_3_;
  input DATA_IN_2_;
  wire DATA_IN_2_;
  input DATA_IN_1_;
  wire DATA_IN_1_;
  input DATA_IN_0_;
  wire DATA_IN_0_;
  input STATO_REG_0__SCAN_IN;
  wire STATO_REG_0__SCAN_IN;
  input STATO_REG_1__SCAN_IN;
  wire STATO_REG_1__SCAN_IN;
  input DATA_OUT_REG_0__SCAN_IN;
  wire DATA_OUT_REG_0__SCAN_IN;
  input DATA_OUT_REG_1__SCAN_IN;
  wire DATA_OUT_REG_1__SCAN_IN;
  input DATA_OUT_REG_2__SCAN_IN;
  wire DATA_OUT_REG_2__SCAN_IN;
  input DATA_OUT_REG_3__SCAN_IN;
  wire DATA_OUT_REG_3__SCAN_IN;
  input DATA_OUT_REG_4__SCAN_IN;
  wire DATA_OUT_REG_4__SCAN_IN;
  input DATA_OUT_REG_5__SCAN_IN;
  wire DATA_OUT_REG_5__SCAN_IN;
  input DATA_OUT_REG_6__SCAN_IN;
  wire DATA_OUT_REG_6__SCAN_IN;
  input DATA_OUT_REG_7__SCAN_IN;
  wire DATA_OUT_REG_7__SCAN_IN;
  input REG4_REG_0__SCAN_IN;
  wire REG4_REG_0__SCAN_IN;
  input REG4_REG_1__SCAN_IN;
  wire REG4_REG_1__SCAN_IN;
  input REG4_REG_2__SCAN_IN;
  wire REG4_REG_2__SCAN_IN;
  input RMAX_REG_7__SCAN_IN;
  wire RMAX_REG_7__SCAN_IN;
  input RMAX_REG_6__SCAN_IN;
  wire RMAX_REG_6__SCAN_IN;
  input RMAX_REG_5__SCAN_IN;
  wire RMAX_REG_5__SCAN_IN;
  input RMAX_REG_4__SCAN_IN;
  wire RMAX_REG_4__SCAN_IN;
  input RMAX_REG_3__SCAN_IN;
  wire RMAX_REG_3__SCAN_IN;
  input RMAX_REG_2__SCAN_IN;
  wire RMAX_REG_2__SCAN_IN;
  input RMAX_REG_1__SCAN_IN;
  wire RMAX_REG_1__SCAN_IN;
  input RMAX_REG_0__SCAN_IN;
  wire RMAX_REG_0__SCAN_IN;
  input RMIN_REG_7__SCAN_IN;
  wire RMIN_REG_7__SCAN_IN;
  input RMIN_REG_6__SCAN_IN;
  wire RMIN_REG_6__SCAN_IN;
  input RMIN_REG_5__SCAN_IN;
  wire RMIN_REG_5__SCAN_IN;
  input RMIN_REG_4__SCAN_IN;
  wire RMIN_REG_4__SCAN_IN;
  input RMIN_REG_3__SCAN_IN;
  wire RMIN_REG_3__SCAN_IN;
  input RMIN_REG_2__SCAN_IN;
  wire RMIN_REG_2__SCAN_IN;
  input RMIN_REG_1__SCAN_IN;
  wire RMIN_REG_1__SCAN_IN;
  input RMIN_REG_0__SCAN_IN;
  wire RMIN_REG_0__SCAN_IN;
  input RLAST_REG_7__SCAN_IN;
  wire RLAST_REG_7__SCAN_IN;
  input RLAST_REG_6__SCAN_IN;
  wire RLAST_REG_6__SCAN_IN;
  input RLAST_REG_5__SCAN_IN;
  wire RLAST_REG_5__SCAN_IN;
  input RLAST_REG_4__SCAN_IN;
  wire RLAST_REG_4__SCAN_IN;
  input RLAST_REG_3__SCAN_IN;
  wire RLAST_REG_3__SCAN_IN;
  input RLAST_REG_2__SCAN_IN;
  wire RLAST_REG_2__SCAN_IN;
  input RLAST_REG_1__SCAN_IN;
  wire RLAST_REG_1__SCAN_IN;
  input RLAST_REG_0__SCAN_IN;
  wire RLAST_REG_0__SCAN_IN;
  input REG1_REG_7__SCAN_IN;
  wire REG1_REG_7__SCAN_IN;
  input REG1_REG_6__SCAN_IN;
  wire REG1_REG_6__SCAN_IN;
  input REG1_REG_5__SCAN_IN;
  wire REG1_REG_5__SCAN_IN;
  input REG1_REG_4__SCAN_IN;
  wire REG1_REG_4__SCAN_IN;
  input REG1_REG_3__SCAN_IN;
  wire REG1_REG_3__SCAN_IN;
  input REG1_REG_2__SCAN_IN;
  wire REG1_REG_2__SCAN_IN;
  input REG1_REG_1__SCAN_IN;
  wire REG1_REG_1__SCAN_IN;
  input REG1_REG_0__SCAN_IN;
  wire REG1_REG_0__SCAN_IN;
  input REG2_REG_7__SCAN_IN;
  wire REG2_REG_7__SCAN_IN;
  input REG2_REG_6__SCAN_IN;
  wire REG2_REG_6__SCAN_IN;
  input REG2_REG_5__SCAN_IN;
  wire REG2_REG_5__SCAN_IN;
  input REG2_REG_4__SCAN_IN;
  wire REG2_REG_4__SCAN_IN;
  input REG2_REG_3__SCAN_IN;
  wire REG2_REG_3__SCAN_IN;
  input REG2_REG_2__SCAN_IN;
  wire REG2_REG_2__SCAN_IN;
  input REG2_REG_1__SCAN_IN;
  wire REG2_REG_1__SCAN_IN;
  input REG2_REG_0__SCAN_IN;
  wire REG2_REG_0__SCAN_IN;
  input REG3_REG_7__SCAN_IN;
  wire REG3_REG_7__SCAN_IN;
  input REG3_REG_6__SCAN_IN;
  wire REG3_REG_6__SCAN_IN;
  input REG3_REG_5__SCAN_IN;
  wire REG3_REG_5__SCAN_IN;
  input REG3_REG_4__SCAN_IN;
  wire REG3_REG_4__SCAN_IN;
  input REG3_REG_3__SCAN_IN;
  wire REG3_REG_3__SCAN_IN;
  input REG3_REG_2__SCAN_IN;
  wire REG3_REG_2__SCAN_IN;
  input REG3_REG_1__SCAN_IN;
  wire REG3_REG_1__SCAN_IN;
  input REG3_REG_0__SCAN_IN;
  wire REG3_REG_0__SCAN_IN;
  input REG4_REG_7__SCAN_IN;
  wire REG4_REG_7__SCAN_IN;
  input REG4_REG_6__SCAN_IN;
  wire REG4_REG_6__SCAN_IN;
  input REG4_REG_5__SCAN_IN;
  wire REG4_REG_5__SCAN_IN;
  input REG4_REG_4__SCAN_IN;
  wire REG4_REG_4__SCAN_IN;
  input REG4_REG_3__SCAN_IN;
  wire REG4_REG_3__SCAN_IN;
  output U344;
  wire U344;
  output U343;
  wire U343;
  output U342;
  wire U342;
  output U341;
  wire U341;
  output U340;
  wire U340;
  output U339;
  wire U339;
  output U338;
  wire U338;
  output U337;
  wire U337;
  output U336;
  wire U336;
  output U335;
  wire U335;
  output U334;
  wire U334;
  output U333;
  wire U333;
  output U332;
  wire U332;
  output U331;
  wire U331;
  output U330;
  wire U330;
  output U329;
  wire U329;
  output U328;
  wire U328;
  output U327;
  wire U327;
  output U326;
  wire U326;
  output U325;
  wire U325;
  output U324;
  wire U324;
  output U323;
  wire U323;
  output U322;
  wire U322;
  output U321;
  wire U321;
  output U320;
  wire U320;
  output U319;
  wire U319;
  output U318;
  wire U318;
  output U317;
  wire U317;
  output U316;
  wire U316;
  output U315;
  wire U315;
  output U314;
  wire U314;
  output U313;
  wire U313;
  output U312;
  wire U312;
  output U311;
  wire U311;
  output U310;
  wire U310;
  output U309;
  wire U309;
  output U308;
  wire U308;
  output U307;
  wire U307;
  output U306;
  wire U306;
  output U305;
  wire U305;
  output U304;
  wire U304;
  output U303;
  wire U303;
  output U302;
  wire U302;
  output U301;
  wire U301;
  output U300;
  wire U300;
  output U299;
  wire U299;
  output U298;
  wire U298;
  output U297;
  wire U297;
  output U296;
  wire U296;
  output U295;
  wire U295;
  output U294;
  wire U294;
  output U293;
  wire U293;
  output U292;
  wire U292;
  output U291;
  wire U291;
  output U290;
  wire U290;
  output U289;
  wire U289;
  output U288;
  wire U288;
  output U287;
  wire U287;
  output U286;
  wire U286;
  output U285;
  wire U285;
  output U284;
  wire U284;
  output U283;
  wire U283;
  output U282;
  wire U282;
  output U281;
  wire U281;
  output U280;
  wire U280;
  output U375;
  wire U375;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  AOI22_X1 _210_ (
    .A1(RMIN_REG_5__SCAN_IN),
    .A2(RMAX_REG_5__SCAN_IN),
    .B1(RMIN_REG_4__SCAN_IN),
    .B2(RMAX_REG_4__SCAN_IN),
    .ZN(_000_)
  );
  OAI22_X1 _211_ (
    .A1(RMIN_REG_4__SCAN_IN),
    .A2(RMAX_REG_4__SCAN_IN),
    .B1(RMIN_REG_3__SCAN_IN),
    .B2(RMAX_REG_3__SCAN_IN),
    .ZN(_001_)
  );
  NOR2_X1 _212_ (
    .A1(RMIN_REG_2__SCAN_IN),
    .A2(RMAX_REG_2__SCAN_IN),
    .ZN(_002_)
  );
  NAND2_X1 _213_ (
    .A1(RMAX_REG_1__SCAN_IN),
    .A2(RMIN_REG_1__SCAN_IN),
    .ZN(_003_)
  );
  OAI211_X1 _214_ (
    .A(RMIN_REG_0__SCAN_IN),
    .B(RMAX_REG_0__SCAN_IN),
    .C1(RMAX_REG_1__SCAN_IN),
    .C2(RMIN_REG_1__SCAN_IN),
    .ZN(_004_)
  );
  AOI21_X1 _215_ (
    .A(_002_),
    .B1(_003_),
    .B2(_004_),
    .ZN(_005_)
  );
  AOI221_X1 _216_ (
    .A(_005_),
    .B1(RMAX_REG_3__SCAN_IN),
    .B2(RMIN_REG_3__SCAN_IN),
    .C1(RMIN_REG_2__SCAN_IN),
    .C2(RMAX_REG_2__SCAN_IN),
    .ZN(_006_)
  );
  OAI21_X1 _217_ (
    .A(_000_),
    .B1(_001_),
    .B2(_006_),
    .ZN(_007_)
  );
  OAI221_X1 _218_ (
    .A(_007_),
    .B1(RMAX_REG_5__SCAN_IN),
    .B2(RMIN_REG_5__SCAN_IN),
    .C1(RMIN_REG_6__SCAN_IN),
    .C2(RMAX_REG_6__SCAN_IN),
    .ZN(_008_)
  );
  NOR2_X1 _219_ (
    .A1(RMIN_REG_7__SCAN_IN),
    .A2(RMAX_REG_7__SCAN_IN),
    .ZN(_009_)
  );
  AOI21_X1 _220_ (
    .A(_009_),
    .B1(RMAX_REG_6__SCAN_IN),
    .B2(RMIN_REG_6__SCAN_IN),
    .ZN(_010_)
  );
  AOI22_X1 _221_ (
    .A1(RMIN_REG_7__SCAN_IN),
    .A2(RMAX_REG_7__SCAN_IN),
    .B1(_008_),
    .B2(_010_),
    .ZN(_011_)
  );
  BUF_X1 _222_ (
    .A(RESTART),
    .Z(_012_)
  );
  BUF_X1 _223_ (
    .A(_012_),
    .Z(_013_)
  );
  INV_X1 _224_ (
    .A(STATO_REG_1__SCAN_IN),
    .ZN(_014_)
  );
  NOR2_X1 _225_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_014_),
    .ZN(_015_)
  );
  NAND2_X1 _226_ (
    .A1(_013_),
    .A2(_015_),
    .ZN(_016_)
  );
  INV_X1 _227_ (
    .A(ENABLE),
    .ZN(_017_)
  );
  INV_X1 _228_ (
    .A(STATO_REG_0__SCAN_IN),
    .ZN(_018_)
  );
  NAND2_X1 _229_ (
    .A1(_018_),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_019_)
  );
  OR4_X1 _230_ (
    .A1(_013_),
    .A2(AVERAGE),
    .A3(_017_),
    .A4(_019_),
    .ZN(_020_)
  );
  NAND2_X1 _231_ (
    .A1(REG4_REG_7__SCAN_IN),
    .A2(DATA_IN_7_),
    .ZN(_021_)
  );
  NAND2_X1 _232_ (
    .A1(REG4_REG_6__SCAN_IN),
    .A2(DATA_IN_6_),
    .ZN(_022_)
  );
  AOI22_X1 _233_ (
    .A1(REG4_REG_1__SCAN_IN),
    .A2(DATA_IN_1_),
    .B1(DATA_IN_0_),
    .B2(REG4_REG_0__SCAN_IN),
    .ZN(_023_)
  );
  OAI22_X1 _234_ (
    .A1(REG4_REG_1__SCAN_IN),
    .A2(DATA_IN_1_),
    .B1(DATA_IN_2_),
    .B2(REG4_REG_2__SCAN_IN),
    .ZN(_024_)
  );
  NOR2_X1 _235_ (
    .A1(_023_),
    .A2(_024_),
    .ZN(_025_)
  );
  AOI221_X1 _236_ (
    .A(_025_),
    .B1(DATA_IN_3_),
    .B2(REG4_REG_3__SCAN_IN),
    .C1(REG4_REG_2__SCAN_IN),
    .C2(DATA_IN_2_),
    .ZN(_026_)
  );
  OAI22_X1 _237_ (
    .A1(REG4_REG_4__SCAN_IN),
    .A2(DATA_IN_4_),
    .B1(DATA_IN_3_),
    .B2(REG4_REG_3__SCAN_IN),
    .ZN(_027_)
  );
  NOR2_X1 _238_ (
    .A1(_026_),
    .A2(_027_),
    .ZN(_028_)
  );
  AOI221_X1 _239_ (
    .A(_028_),
    .B1(DATA_IN_5_),
    .B2(REG4_REG_5__SCAN_IN),
    .C1(REG4_REG_4__SCAN_IN),
    .C2(DATA_IN_4_),
    .ZN(_029_)
  );
  OAI22_X1 _240_ (
    .A1(REG4_REG_6__SCAN_IN),
    .A2(DATA_IN_6_),
    .B1(DATA_IN_5_),
    .B2(REG4_REG_5__SCAN_IN),
    .ZN(_030_)
  );
  OAI221_X1 _241_ (
    .A(_022_),
    .B1(_029_),
    .B2(_030_),
    .C1(DATA_IN_7_),
    .C2(REG4_REG_7__SCAN_IN),
    .ZN(_031_)
  );
  AND2_X1 _242_ (
    .A1(_021_),
    .A2(_031_),
    .ZN(_032_)
  );
  OAI22_X1 _243_ (
    .A1(_011_),
    .A2(_016_),
    .B1(_020_),
    .B2(_032_),
    .ZN(_033_)
  );
  MUX2_X1 _244_ (
    .A(DATA_IN_1_),
    .B(RMAX_REG_1__SCAN_IN),
    .S(_012_),
    .Z(_034_)
  );
  MUX2_X1 _245_ (
    .A(DATA_IN_0_),
    .B(RMAX_REG_0__SCAN_IN),
    .S(RESTART),
    .Z(_035_)
  );
  MUX2_X1 _246_ (
    .A(REG4_REG_0__SCAN_IN),
    .B(RMIN_REG_0__SCAN_IN),
    .S(RESTART),
    .Z(_036_)
  );
  MUX2_X1 _247_ (
    .A(REG4_REG_1__SCAN_IN),
    .B(RMIN_REG_1__SCAN_IN),
    .S(_012_),
    .Z(_037_)
  );
  AND3_X1 _248_ (
    .A1(_035_),
    .A2(_036_),
    .A3(_037_),
    .ZN(_038_)
  );
  AOI21_X1 _249_ (
    .A(_037_),
    .B1(_036_),
    .B2(_035_),
    .ZN(_039_)
  );
  OAI21_X1 _250_ (
    .A(_034_),
    .B1(_038_),
    .B2(_039_),
    .ZN(_040_)
  );
  OR3_X1 _251_ (
    .A1(_039_),
    .A2(_038_),
    .A3(_034_),
    .ZN(_041_)
  );
  AND2_X1 _252_ (
    .A1(_040_),
    .A2(_041_),
    .ZN(_042_)
  );
  XNOR2_X1 _253_ (
    .A(_035_),
    .B(_036_),
    .ZN(_043_)
  );
  OR2_X1 _254_ (
    .A1(_042_),
    .A2(_043_),
    .ZN(_044_)
  );
  NAND3_X1 _255_ (
    .A1(_040_),
    .A2(_041_),
    .A3(_043_),
    .ZN(_045_)
  );
  NAND3_X1 _256_ (
    .A1(_033_),
    .A2(_044_),
    .A3(_045_),
    .ZN(_046_)
  );
  INV_X1 _257_ (
    .A(AVERAGE),
    .ZN(_047_)
  );
  NOR4_X1 _258_ (
    .A1(_013_),
    .A2(_047_),
    .A3(_017_),
    .A4(_019_),
    .ZN(_048_)
  );
  XNOR2_X1 _259_ (
    .A(STATO_REG_0__SCAN_IN),
    .B(STATO_REG_1__SCAN_IN),
    .ZN(_049_)
  );
  BUF_X1 _260_ (
    .A(_049_),
    .Z(_050_)
  );
  NOR3_X1 _261_ (
    .A1(_013_),
    .A2(ENABLE),
    .A3(_019_),
    .ZN(_051_)
  );
  AOI222_X1 _262_ (
    .A1(REG4_REG_0__SCAN_IN),
    .A2(_048_),
    .B1(_050_),
    .B2(DATA_OUT_REG_0__SCAN_IN),
    .C1(_051_),
    .C2(RLAST_REG_0__SCAN_IN),
    .ZN(_052_)
  );
  INV_X1 _263_ (
    .A(_042_),
    .ZN(_053_)
  );
  NAND3_X1 _264_ (
    .A1(_013_),
    .A2(_011_),
    .A3(_015_),
    .ZN(_054_)
  );
  NAND2_X1 _265_ (
    .A1(_021_),
    .A2(_031_),
    .ZN(_055_)
  );
  OAI21_X1 _266_ (
    .A(_054_),
    .B1(_055_),
    .B2(_020_),
    .ZN(_056_)
  );
  NAND2_X1 _267_ (
    .A1(_053_),
    .A2(_056_),
    .ZN(_057_)
  );
  NAND3_X1 _268_ (
    .A1(_046_),
    .A2(_052_),
    .A3(_057_),
    .ZN(U281)
  );
  BUF_X1 _269_ (
    .A(_050_),
    .Z(_058_)
  );
  INV_X1 _270_ (
    .A(_058_),
    .ZN(U280)
  );
  AOI222_X1 _271_ (
    .A1(REG4_REG_1__SCAN_IN),
    .A2(_048_),
    .B1(_049_),
    .B2(DATA_OUT_REG_1__SCAN_IN),
    .C1(_051_),
    .C2(RLAST_REG_1__SCAN_IN),
    .ZN(_059_)
  );
  NAND3_X1 _272_ (
    .A1(_035_),
    .A2(_036_),
    .A3(_037_),
    .ZN(_060_)
  );
  INV_X1 _273_ (
    .A(_034_),
    .ZN(_061_)
  );
  AOI21_X1 _274_ (
    .A(_039_),
    .B1(_060_),
    .B2(_061_),
    .ZN(_062_)
  );
  MUX2_X1 _275_ (
    .A(REG4_REG_2__SCAN_IN),
    .B(RMIN_REG_2__SCAN_IN),
    .S(_012_),
    .Z(_063_)
  );
  MUX2_X1 _276_ (
    .A(DATA_IN_2_),
    .B(RMAX_REG_2__SCAN_IN),
    .S(_012_),
    .Z(_064_)
  );
  AND2_X1 _277_ (
    .A1(_063_),
    .A2(_064_),
    .ZN(_065_)
  );
  NOR2_X1 _278_ (
    .A1(_063_),
    .A2(_064_),
    .ZN(_066_)
  );
  NOR2_X1 _279_ (
    .A1(_065_),
    .A2(_066_),
    .ZN(_067_)
  );
  XOR2_X1 _280_ (
    .A(_062_),
    .B(_067_),
    .Z(_068_)
  );
  NAND2_X1 _281_ (
    .A1(_056_),
    .A2(_068_),
    .ZN(_069_)
  );
  AOI21_X1 _282_ (
    .A(_043_),
    .B1(_041_),
    .B2(_040_),
    .ZN(_070_)
  );
  XNOR2_X1 _283_ (
    .A(_070_),
    .B(_068_),
    .ZN(_071_)
  );
  INV_X1 _284_ (
    .A(_033_),
    .ZN(_072_)
  );
  OAI211_X1 _285_ (
    .A(_059_),
    .B(_069_),
    .C1(_071_),
    .C2(_072_),
    .ZN(U282)
  );
  AOI222_X1 _286_ (
    .A1(REG4_REG_2__SCAN_IN),
    .A2(_048_),
    .B1(_050_),
    .B2(DATA_OUT_REG_2__SCAN_IN),
    .C1(_051_),
    .C2(RLAST_REG_2__SCAN_IN),
    .ZN(_073_)
  );
  AND2_X1 _287_ (
    .A1(_070_),
    .A2(_068_),
    .ZN(_074_)
  );
  NOR2_X1 _288_ (
    .A1(_045_),
    .A2(_068_),
    .ZN(_075_)
  );
  AOI211_X1 _289_ (
    .A(_039_),
    .B(_066_),
    .C1(_061_),
    .C2(_060_),
    .ZN(_076_)
  );
  MUX2_X1 _290_ (
    .A(REG4_REG_3__SCAN_IN),
    .B(RMIN_REG_3__SCAN_IN),
    .S(_012_),
    .Z(_077_)
  );
  MUX2_X1 _291_ (
    .A(DATA_IN_3_),
    .B(RMAX_REG_3__SCAN_IN),
    .S(_012_),
    .Z(_078_)
  );
  XOR2_X1 _292_ (
    .A(_077_),
    .B(_078_),
    .Z(_079_)
  );
  OR3_X1 _293_ (
    .A1(_065_),
    .A2(_076_),
    .A3(_079_),
    .ZN(_080_)
  );
  OAI21_X1 _294_ (
    .A(_079_),
    .B1(_076_),
    .B2(_065_),
    .ZN(_081_)
  );
  AND2_X1 _295_ (
    .A1(_080_),
    .A2(_081_),
    .ZN(_082_)
  );
  NOR3_X1 _296_ (
    .A1(_074_),
    .A2(_075_),
    .A3(_082_),
    .ZN(_083_)
  );
  AOI211_X1 _297_ (
    .A(_045_),
    .B(_068_),
    .C1(_080_),
    .C2(_081_),
    .ZN(_084_)
  );
  AOI21_X1 _298_ (
    .A(_084_),
    .B1(_082_),
    .B2(_074_),
    .ZN(_085_)
  );
  AOI22_X1 _299_ (
    .A1(_056_),
    .A2(_082_),
    .B1(_085_),
    .B2(_033_),
    .ZN(_086_)
  );
  OAI21_X1 _300_ (
    .A(_073_),
    .B1(_083_),
    .B2(_086_),
    .ZN(U283)
  );
  AOI222_X1 _301_ (
    .A1(REG4_REG_3__SCAN_IN),
    .A2(_048_),
    .B1(_050_),
    .B2(DATA_OUT_REG_3__SCAN_IN),
    .C1(_051_),
    .C2(RLAST_REG_3__SCAN_IN),
    .ZN(_087_)
  );
  AND2_X1 _302_ (
    .A1(_012_),
    .A2(RMAX_REG_3__SCAN_IN),
    .ZN(_088_)
  );
  INV_X1 _303_ (
    .A(DATA_IN_3_),
    .ZN(_089_)
  );
  NOR2_X1 _304_ (
    .A1(_013_),
    .A2(_089_),
    .ZN(_090_)
  );
  AND2_X1 _305_ (
    .A1(_077_),
    .A2(_078_),
    .ZN(_091_)
  );
  OAI33_X1 _306_ (
    .A1(_077_),
    .A2(_088_),
    .A3(_090_),
    .B1(_091_),
    .B2(_065_),
    .B3(_076_),
    .ZN(_092_)
  );
  MUX2_X1 _307_ (
    .A(REG4_REG_4__SCAN_IN),
    .B(RMIN_REG_4__SCAN_IN),
    .S(_012_),
    .Z(_093_)
  );
  MUX2_X1 _308_ (
    .A(DATA_IN_4_),
    .B(RMAX_REG_4__SCAN_IN),
    .S(_012_),
    .Z(_094_)
  );
  XOR2_X1 _309_ (
    .A(_093_),
    .B(_094_),
    .Z(_095_)
  );
  XNOR2_X1 _310_ (
    .A(_092_),
    .B(_095_),
    .ZN(_096_)
  );
  XNOR2_X1 _311_ (
    .A(_084_),
    .B(_096_),
    .ZN(_097_)
  );
  AND2_X1 _312_ (
    .A1(_085_),
    .A2(_097_),
    .ZN(_098_)
  );
  OR2_X1 _313_ (
    .A1(_085_),
    .A2(_097_),
    .ZN(_099_)
  );
  AOI22_X1 _314_ (
    .A1(_056_),
    .A2(_096_),
    .B1(_099_),
    .B2(_033_),
    .ZN(_100_)
  );
  OAI21_X1 _315_ (
    .A(_087_),
    .B1(_098_),
    .B2(_100_),
    .ZN(U284)
  );
  NAND2_X1 _316_ (
    .A1(REG4_REG_4__SCAN_IN),
    .A2(_048_),
    .ZN(_101_)
  );
  NAND2_X1 _317_ (
    .A1(_093_),
    .A2(_094_),
    .ZN(_102_)
  );
  NOR2_X1 _318_ (
    .A1(_093_),
    .A2(_094_),
    .ZN(_103_)
  );
  OAI21_X1 _319_ (
    .A(_102_),
    .B1(_103_),
    .B2(_092_),
    .ZN(_104_)
  );
  MUX2_X1 _320_ (
    .A(REG4_REG_5__SCAN_IN),
    .B(RMIN_REG_5__SCAN_IN),
    .S(_013_),
    .Z(_105_)
  );
  MUX2_X1 _321_ (
    .A(DATA_IN_5_),
    .B(RMAX_REG_5__SCAN_IN),
    .S(_013_),
    .Z(_106_)
  );
  XNOR2_X1 _322_ (
    .A(_105_),
    .B(_106_),
    .ZN(_107_)
  );
  XNOR2_X1 _323_ (
    .A(_104_),
    .B(_107_),
    .ZN(_108_)
  );
  AOI222_X1 _324_ (
    .A1(RLAST_REG_4__SCAN_IN),
    .A2(_051_),
    .B1(_056_),
    .B2(_108_),
    .C1(_049_),
    .C2(DATA_OUT_REG_4__SCAN_IN),
    .ZN(_109_)
  );
  OR4_X1 _325_ (
    .A1(_045_),
    .A2(_068_),
    .A3(_082_),
    .A4(_096_),
    .ZN(_110_)
  );
  XOR2_X1 _326_ (
    .A(_110_),
    .B(_108_),
    .Z(_111_)
  );
  XNOR2_X1 _327_ (
    .A(_099_),
    .B(_111_),
    .ZN(_112_)
  );
  OAI211_X1 _328_ (
    .A(_101_),
    .B(_109_),
    .C1(_072_),
    .C2(_112_),
    .ZN(U285)
  );
  NAND2_X1 _329_ (
    .A1(RLAST_REG_5__SCAN_IN),
    .A2(_051_),
    .ZN(_113_)
  );
  AND2_X1 _330_ (
    .A1(_105_),
    .A2(_106_),
    .ZN(_114_)
  );
  OR2_X1 _331_ (
    .A1(_105_),
    .A2(_106_),
    .ZN(_115_)
  );
  AOI21_X1 _332_ (
    .A(_114_),
    .B1(_115_),
    .B2(_104_),
    .ZN(_116_)
  );
  XOR2_X1 _333_ (
    .A(RMIN_REG_6__SCAN_IN),
    .B(RMAX_REG_6__SCAN_IN),
    .Z(_117_)
  );
  INV_X1 _334_ (
    .A(REG4_REG_6__SCAN_IN),
    .ZN(_118_)
  );
  INV_X1 _335_ (
    .A(DATA_IN_6_),
    .ZN(_119_)
  );
  AOI21_X1 _336_ (
    .A(_013_),
    .B1(_118_),
    .B2(_119_),
    .ZN(_120_)
  );
  AOI22_X1 _337_ (
    .A1(_013_),
    .A2(_117_),
    .B1(_120_),
    .B2(_022_),
    .ZN(_121_)
  );
  XOR2_X1 _338_ (
    .A(_116_),
    .B(_121_),
    .Z(_122_)
  );
  AOI222_X1 _339_ (
    .A1(REG4_REG_5__SCAN_IN),
    .A2(_048_),
    .B1(_056_),
    .B2(_122_),
    .C1(_049_),
    .C2(DATA_OUT_REG_5__SCAN_IN),
    .ZN(_123_)
  );
  OR2_X1 _340_ (
    .A1(_099_),
    .A2(_111_),
    .ZN(_124_)
  );
  NOR2_X1 _341_ (
    .A1(_110_),
    .A2(_108_),
    .ZN(_125_)
  );
  XNOR2_X1 _342_ (
    .A(_125_),
    .B(_122_),
    .ZN(_126_)
  );
  XNOR2_X1 _343_ (
    .A(_124_),
    .B(_126_),
    .ZN(_127_)
  );
  OAI211_X1 _344_ (
    .A(_113_),
    .B(_123_),
    .C1(_072_),
    .C2(_127_),
    .ZN(U286)
  );
  AOI222_X1 _345_ (
    .A1(REG4_REG_6__SCAN_IN),
    .A2(_048_),
    .B1(_051_),
    .B2(RLAST_REG_6__SCAN_IN),
    .C1(DATA_OUT_REG_6__SCAN_IN),
    .C2(_049_),
    .ZN(_128_)
  );
  OAI211_X1 _346_ (
    .A(_033_),
    .B(_122_),
    .C1(_108_),
    .C2(_110_),
    .ZN(_129_)
  );
  OAI21_X1 _347_ (
    .A(_128_),
    .B1(_129_),
    .B2(_124_),
    .ZN(U287)
  );
  AOI222_X1 _348_ (
    .A1(REG4_REG_7__SCAN_IN),
    .A2(_048_),
    .B1(_051_),
    .B2(RLAST_REG_7__SCAN_IN),
    .C1(_050_),
    .C2(DATA_OUT_REG_7__SCAN_IN),
    .ZN(_130_)
  );
  INV_X1 _349_ (
    .A(_130_),
    .ZN(U288)
  );
  NOR2_X1 _350_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(U375)
  );
  BUF_X1 _351_ (
    .A(_015_),
    .Z(_131_)
  );
  AOI22_X1 _352_ (
    .A1(REG3_REG_0__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_0__SCAN_IN),
    .ZN(_132_)
  );
  INV_X1 _353_ (
    .A(_132_),
    .ZN(U289)
  );
  AOI22_X1 _354_ (
    .A1(REG3_REG_1__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_1__SCAN_IN),
    .ZN(_133_)
  );
  INV_X1 _355_ (
    .A(_133_),
    .ZN(U290)
  );
  AOI22_X1 _356_ (
    .A1(REG3_REG_2__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_2__SCAN_IN),
    .ZN(_134_)
  );
  INV_X1 _357_ (
    .A(_134_),
    .ZN(U291)
  );
  AOI22_X1 _358_ (
    .A1(REG3_REG_3__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_3__SCAN_IN),
    .ZN(_135_)
  );
  INV_X1 _359_ (
    .A(_135_),
    .ZN(U292)
  );
  AOI22_X1 _360_ (
    .A1(REG3_REG_4__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_4__SCAN_IN),
    .ZN(_136_)
  );
  INV_X1 _361_ (
    .A(_136_),
    .ZN(U293)
  );
  AOI22_X1 _362_ (
    .A1(REG3_REG_5__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_5__SCAN_IN),
    .ZN(_137_)
  );
  INV_X1 _363_ (
    .A(_137_),
    .ZN(U294)
  );
  AOI22_X1 _364_ (
    .A1(REG3_REG_6__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_6__SCAN_IN),
    .ZN(_138_)
  );
  INV_X1 _365_ (
    .A(_138_),
    .ZN(U295)
  );
  AOI22_X1 _366_ (
    .A1(REG3_REG_7__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG4_REG_7__SCAN_IN),
    .ZN(_139_)
  );
  INV_X1 _367_ (
    .A(_139_),
    .ZN(U296)
  );
  AOI22_X1 _368_ (
    .A1(REG2_REG_0__SCAN_IN),
    .A2(_131_),
    .B1(_058_),
    .B2(REG3_REG_0__SCAN_IN),
    .ZN(_140_)
  );
  INV_X1 _369_ (
    .A(_140_),
    .ZN(U297)
  );
  BUF_X1 _370_ (
    .A(_050_),
    .Z(_141_)
  );
  AOI22_X1 _371_ (
    .A1(REG2_REG_1__SCAN_IN),
    .A2(_131_),
    .B1(_141_),
    .B2(REG3_REG_1__SCAN_IN),
    .ZN(_142_)
  );
  INV_X1 _372_ (
    .A(_142_),
    .ZN(U298)
  );
  CLKBUF_X1 _373_ (
    .A(_015_),
    .Z(_143_)
  );
  AOI22_X1 _374_ (
    .A1(REG2_REG_2__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG3_REG_2__SCAN_IN),
    .ZN(_144_)
  );
  INV_X1 _375_ (
    .A(_144_),
    .ZN(U299)
  );
  AOI22_X1 _376_ (
    .A1(REG2_REG_3__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG3_REG_3__SCAN_IN),
    .ZN(_145_)
  );
  INV_X1 _377_ (
    .A(_145_),
    .ZN(U300)
  );
  AOI22_X1 _378_ (
    .A1(REG2_REG_4__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG3_REG_4__SCAN_IN),
    .ZN(_146_)
  );
  INV_X1 _379_ (
    .A(_146_),
    .ZN(U301)
  );
  AOI22_X1 _380_ (
    .A1(REG2_REG_5__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG3_REG_5__SCAN_IN),
    .ZN(_147_)
  );
  INV_X1 _381_ (
    .A(_147_),
    .ZN(U302)
  );
  AOI22_X1 _382_ (
    .A1(REG2_REG_6__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG3_REG_6__SCAN_IN),
    .ZN(_148_)
  );
  INV_X1 _383_ (
    .A(_148_),
    .ZN(U303)
  );
  AOI22_X1 _384_ (
    .A1(REG2_REG_7__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG3_REG_7__SCAN_IN),
    .ZN(_149_)
  );
  INV_X1 _385_ (
    .A(_149_),
    .ZN(U304)
  );
  AOI22_X1 _386_ (
    .A1(REG1_REG_0__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG2_REG_0__SCAN_IN),
    .ZN(_150_)
  );
  INV_X1 _387_ (
    .A(_150_),
    .ZN(U305)
  );
  AOI22_X1 _388_ (
    .A1(REG1_REG_1__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG2_REG_1__SCAN_IN),
    .ZN(_151_)
  );
  INV_X1 _389_ (
    .A(_151_),
    .ZN(U306)
  );
  AOI22_X1 _390_ (
    .A1(REG1_REG_2__SCAN_IN),
    .A2(_143_),
    .B1(_141_),
    .B2(REG2_REG_2__SCAN_IN),
    .ZN(_152_)
  );
  INV_X1 _391_ (
    .A(_152_),
    .ZN(U307)
  );
  BUF_X1 _392_ (
    .A(_050_),
    .Z(_153_)
  );
  AOI22_X1 _393_ (
    .A1(REG1_REG_3__SCAN_IN),
    .A2(_143_),
    .B1(_153_),
    .B2(REG2_REG_3__SCAN_IN),
    .ZN(_154_)
  );
  INV_X1 _394_ (
    .A(_154_),
    .ZN(U308)
  );
  BUF_X1 _395_ (
    .A(_015_),
    .Z(_155_)
  );
  AOI22_X1 _396_ (
    .A1(REG1_REG_4__SCAN_IN),
    .A2(_155_),
    .B1(_153_),
    .B2(REG2_REG_4__SCAN_IN),
    .ZN(_156_)
  );
  INV_X1 _397_ (
    .A(_156_),
    .ZN(U309)
  );
  AOI22_X1 _398_ (
    .A1(REG1_REG_5__SCAN_IN),
    .A2(_155_),
    .B1(_153_),
    .B2(REG2_REG_5__SCAN_IN),
    .ZN(_157_)
  );
  INV_X1 _399_ (
    .A(_157_),
    .ZN(U310)
  );
  AOI22_X1 _400_ (
    .A1(REG1_REG_6__SCAN_IN),
    .A2(_155_),
    .B1(_153_),
    .B2(REG2_REG_6__SCAN_IN),
    .ZN(_158_)
  );
  INV_X1 _401_ (
    .A(_158_),
    .ZN(U311)
  );
  AOI22_X1 _402_ (
    .A1(REG1_REG_7__SCAN_IN),
    .A2(_155_),
    .B1(_153_),
    .B2(REG2_REG_7__SCAN_IN),
    .ZN(_159_)
  );
  INV_X1 _403_ (
    .A(_159_),
    .ZN(U312)
  );
  AOI22_X1 _404_ (
    .A1(DATA_IN_0_),
    .A2(_155_),
    .B1(_153_),
    .B2(REG1_REG_0__SCAN_IN),
    .ZN(_160_)
  );
  INV_X1 _405_ (
    .A(_160_),
    .ZN(U313)
  );
  AOI22_X1 _406_ (
    .A1(DATA_IN_1_),
    .A2(_155_),
    .B1(_153_),
    .B2(REG1_REG_1__SCAN_IN),
    .ZN(_161_)
  );
  INV_X1 _407_ (
    .A(_161_),
    .ZN(U314)
  );
  AOI22_X1 _408_ (
    .A1(DATA_IN_2_),
    .A2(_155_),
    .B1(_153_),
    .B2(REG1_REG_2__SCAN_IN),
    .ZN(_162_)
  );
  INV_X1 _409_ (
    .A(_162_),
    .ZN(U315)
  );
  AOI22_X1 _410_ (
    .A1(DATA_IN_3_),
    .A2(_155_),
    .B1(_153_),
    .B2(REG1_REG_3__SCAN_IN),
    .ZN(_163_)
  );
  INV_X1 _411_ (
    .A(_163_),
    .ZN(U316)
  );
  AOI22_X1 _412_ (
    .A1(DATA_IN_4_),
    .A2(_155_),
    .B1(_153_),
    .B2(REG1_REG_4__SCAN_IN),
    .ZN(_164_)
  );
  INV_X1 _413_ (
    .A(_164_),
    .ZN(U317)
  );
  AOI22_X1 _414_ (
    .A1(DATA_IN_5_),
    .A2(_155_),
    .B1(_050_),
    .B2(REG1_REG_5__SCAN_IN),
    .ZN(_165_)
  );
  INV_X1 _415_ (
    .A(_165_),
    .ZN(U318)
  );
  AOI22_X1 _416_ (
    .A1(DATA_IN_6_),
    .A2(_015_),
    .B1(_050_),
    .B2(REG1_REG_6__SCAN_IN),
    .ZN(_166_)
  );
  INV_X1 _417_ (
    .A(_166_),
    .ZN(U319)
  );
  AOI22_X1 _418_ (
    .A1(DATA_IN_7_),
    .A2(_015_),
    .B1(_050_),
    .B2(REG1_REG_7__SCAN_IN),
    .ZN(_167_)
  );
  INV_X1 _419_ (
    .A(_167_),
    .ZN(U320)
  );
  AOI21_X1 _420_ (
    .A(_014_),
    .B1(_018_),
    .B2(_017_),
    .ZN(_168_)
  );
  AOI21_X1 _421_ (
    .A(STATO_REG_0__SCAN_IN),
    .B1(STATO_REG_1__SCAN_IN),
    .B2(ENABLE),
    .ZN(_169_)
  );
  AOI22_X1 _422_ (
    .A1(DATA_IN_0_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_0__SCAN_IN),
    .ZN(_170_)
  );
  INV_X1 _423_ (
    .A(_170_),
    .ZN(U321)
  );
  AOI22_X1 _424_ (
    .A1(DATA_IN_1_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_1__SCAN_IN),
    .ZN(_171_)
  );
  INV_X1 _425_ (
    .A(_171_),
    .ZN(U322)
  );
  AOI22_X1 _426_ (
    .A1(DATA_IN_2_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_2__SCAN_IN),
    .ZN(_172_)
  );
  INV_X1 _427_ (
    .A(_172_),
    .ZN(U323)
  );
  AOI22_X1 _428_ (
    .A1(DATA_IN_3_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_3__SCAN_IN),
    .ZN(_173_)
  );
  INV_X1 _429_ (
    .A(_173_),
    .ZN(U324)
  );
  AOI22_X1 _430_ (
    .A1(DATA_IN_4_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_4__SCAN_IN),
    .ZN(_174_)
  );
  INV_X1 _431_ (
    .A(_174_),
    .ZN(U325)
  );
  AOI22_X1 _432_ (
    .A1(DATA_IN_5_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_5__SCAN_IN),
    .ZN(_175_)
  );
  INV_X1 _433_ (
    .A(_175_),
    .ZN(U326)
  );
  AOI22_X1 _434_ (
    .A1(DATA_IN_6_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_6__SCAN_IN),
    .ZN(_176_)
  );
  INV_X1 _435_ (
    .A(_176_),
    .ZN(U327)
  );
  AOI22_X1 _436_ (
    .A1(DATA_IN_7_),
    .A2(_168_),
    .B1(_169_),
    .B2(RLAST_REG_7__SCAN_IN),
    .ZN(_177_)
  );
  INV_X1 _437_ (
    .A(_177_),
    .ZN(U328)
  );
  INV_X1 _438_ (
    .A(DATA_IN_7_),
    .ZN(_178_)
  );
  AOI21_X1 _439_ (
    .A(_014_),
    .B1(RMIN_REG_7__SCAN_IN),
    .B2(_178_),
    .ZN(_179_)
  );
  INV_X1 _440_ (
    .A(RMAX_REG_7__SCAN_IN),
    .ZN(_180_)
  );
  AOI22_X1 _441_ (
    .A1(DATA_IN_7_),
    .A2(_180_),
    .B1(RMAX_REG_6__SCAN_IN),
    .B2(_119_),
    .ZN(_181_)
  );
  INV_X1 _442_ (
    .A(DATA_IN_5_),
    .ZN(_182_)
  );
  OAI22_X1 _443_ (
    .A1(_119_),
    .A2(RMAX_REG_6__SCAN_IN),
    .B1(RMAX_REG_5__SCAN_IN),
    .B2(_182_),
    .ZN(_183_)
  );
  INV_X1 _444_ (
    .A(DATA_IN_2_),
    .ZN(_184_)
  );
  AOI22_X1 _445_ (
    .A1(_184_),
    .A2(RMAX_REG_2__SCAN_IN),
    .B1(RMAX_REG_3__SCAN_IN),
    .B2(_089_),
    .ZN(_185_)
  );
  INV_X1 _446_ (
    .A(DATA_IN_1_),
    .ZN(_186_)
  );
  OAI22_X1 _447_ (
    .A1(_186_),
    .A2(RMAX_REG_1__SCAN_IN),
    .B1(RMAX_REG_2__SCAN_IN),
    .B2(_184_),
    .ZN(_187_)
  );
  INV_X1 _448_ (
    .A(DATA_IN_0_),
    .ZN(_188_)
  );
  AOI211_X1 _449_ (
    .A(_188_),
    .B(RMAX_REG_0__SCAN_IN),
    .C1(RMAX_REG_1__SCAN_IN),
    .C2(_186_),
    .ZN(_189_)
  );
  OAI21_X1 _450_ (
    .A(_185_),
    .B1(_187_),
    .B2(_189_),
    .ZN(_190_)
  );
  INV_X1 _451_ (
    .A(DATA_IN_4_),
    .ZN(_191_)
  );
  OAI221_X1 _452_ (
    .A(_190_),
    .B1(RMAX_REG_3__SCAN_IN),
    .B2(_089_),
    .C1(_191_),
    .C2(RMAX_REG_4__SCAN_IN),
    .ZN(_192_)
  );
  AOI22_X1 _453_ (
    .A1(_182_),
    .A2(RMAX_REG_5__SCAN_IN),
    .B1(RMAX_REG_4__SCAN_IN),
    .B2(_191_),
    .ZN(_193_)
  );
  AND2_X1 _454_ (
    .A1(_192_),
    .A2(_193_),
    .ZN(_194_)
  );
  OAI21_X1 _455_ (
    .A(_181_),
    .B1(_183_),
    .B2(_194_),
    .ZN(_195_)
  );
  OAI21_X1 _456_ (
    .A(_195_),
    .B1(_180_),
    .B2(DATA_IN_7_),
    .ZN(_196_)
  );
  AOI22_X1 _457_ (
    .A1(_119_),
    .A2(RMIN_REG_6__SCAN_IN),
    .B1(RMIN_REG_5__SCAN_IN),
    .B2(_182_),
    .ZN(_197_)
  );
  OAI22_X1 _458_ (
    .A1(_182_),
    .A2(RMIN_REG_5__SCAN_IN),
    .B1(RMIN_REG_4__SCAN_IN),
    .B2(_191_),
    .ZN(_198_)
  );
  OAI22_X1 _459_ (
    .A1(_184_),
    .A2(RMIN_REG_2__SCAN_IN),
    .B1(RMIN_REG_3__SCAN_IN),
    .B2(_089_),
    .ZN(_199_)
  );
  AOI22_X1 _460_ (
    .A1(_186_),
    .A2(RMIN_REG_1__SCAN_IN),
    .B1(RMIN_REG_2__SCAN_IN),
    .B2(_184_),
    .ZN(_200_)
  );
  OAI211_X1 _461_ (
    .A(_188_),
    .B(RMIN_REG_0__SCAN_IN),
    .C1(RMIN_REG_1__SCAN_IN),
    .C2(_186_),
    .ZN(_201_)
  );
  AOI21_X1 _462_ (
    .A(_199_),
    .B1(_200_),
    .B2(_201_),
    .ZN(_202_)
  );
  AOI221_X1 _463_ (
    .A(_202_),
    .B1(RMIN_REG_3__SCAN_IN),
    .B2(_089_),
    .C1(_191_),
    .C2(RMIN_REG_4__SCAN_IN),
    .ZN(_203_)
  );
  OAI21_X1 _464_ (
    .A(_197_),
    .B1(_198_),
    .B2(_203_),
    .ZN(_204_)
  );
  OAI21_X1 _465_ (
    .A(_204_),
    .B1(RMIN_REG_6__SCAN_IN),
    .B2(_119_),
    .ZN(_205_)
  );
  OR2_X1 _466_ (
    .A1(_178_),
    .A2(RMIN_REG_7__SCAN_IN),
    .ZN(_206_)
  );
  AOI21_X1 _467_ (
    .A(_196_),
    .B1(_205_),
    .B2(_206_),
    .ZN(_207_)
  );
  AOI21_X1 _468_ (
    .A(STATO_REG_0__SCAN_IN),
    .B1(_179_),
    .B2(_207_),
    .ZN(_208_)
  );
  MUX2_X1 _469_ (
    .A(DATA_IN_0_),
    .B(RMIN_REG_0__SCAN_IN),
    .S(_208_),
    .Z(U329)
  );
  MUX2_X1 _470_ (
    .A(DATA_IN_1_),
    .B(RMIN_REG_1__SCAN_IN),
    .S(_208_),
    .Z(U330)
  );
  MUX2_X1 _471_ (
    .A(DATA_IN_2_),
    .B(RMIN_REG_2__SCAN_IN),
    .S(_208_),
    .Z(U331)
  );
  MUX2_X1 _472_ (
    .A(DATA_IN_3_),
    .B(RMIN_REG_3__SCAN_IN),
    .S(_208_),
    .Z(U332)
  );
  MUX2_X1 _473_ (
    .A(DATA_IN_4_),
    .B(RMIN_REG_4__SCAN_IN),
    .S(_208_),
    .Z(U333)
  );
  MUX2_X1 _474_ (
    .A(DATA_IN_5_),
    .B(RMIN_REG_5__SCAN_IN),
    .S(_208_),
    .Z(U334)
  );
  MUX2_X1 _475_ (
    .A(DATA_IN_6_),
    .B(RMIN_REG_6__SCAN_IN),
    .S(_208_),
    .Z(U335)
  );
  MUX2_X1 _476_ (
    .A(DATA_IN_7_),
    .B(RMIN_REG_7__SCAN_IN),
    .S(_208_),
    .Z(U336)
  );
  AOI21_X1 _477_ (
    .A(STATO_REG_0__SCAN_IN),
    .B1(STATO_REG_1__SCAN_IN),
    .B2(_196_),
    .ZN(_209_)
  );
  MUX2_X1 _478_ (
    .A(DATA_IN_0_),
    .B(RMAX_REG_0__SCAN_IN),
    .S(_209_),
    .Z(U337)
  );
  MUX2_X1 _479_ (
    .A(DATA_IN_1_),
    .B(RMAX_REG_1__SCAN_IN),
    .S(_209_),
    .Z(U338)
  );
  MUX2_X1 _480_ (
    .A(DATA_IN_2_),
    .B(RMAX_REG_2__SCAN_IN),
    .S(_209_),
    .Z(U339)
  );
  MUX2_X1 _481_ (
    .A(DATA_IN_3_),
    .B(RMAX_REG_3__SCAN_IN),
    .S(_209_),
    .Z(U340)
  );
  MUX2_X1 _482_ (
    .A(DATA_IN_4_),
    .B(RMAX_REG_4__SCAN_IN),
    .S(_209_),
    .Z(U341)
  );
  MUX2_X1 _483_ (
    .A(DATA_IN_5_),
    .B(RMAX_REG_5__SCAN_IN),
    .S(_209_),
    .Z(U342)
  );
  MUX2_X1 _484_ (
    .A(DATA_IN_6_),
    .B(RMAX_REG_6__SCAN_IN),
    .S(_209_),
    .Z(U343)
  );
  MUX2_X1 _485_ (
    .A(DATA_IN_7_),
    .B(RMAX_REG_7__SCAN_IN),
    .S(_209_),
    .Z(U344)
  );
endmodule
