/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module b07_C(START, STATO_REG_0__SCAN_IN, STATO_REG_1__SCAN_IN, PUNTI_RETTA_REG_7__SCAN_IN, PUNTI_RETTA_REG_6__SCAN_IN, PUNTI_RETTA_REG_5__SCAN_IN, PUNTI_RETTA_REG_4__SCAN_IN, PUNTI_RETTA_REG_3__SCAN_IN, PUNTI_RETTA_REG_2__SCAN_IN, PUNTI_RETTA_REG_1__SCAN_IN, PUNTI_RETTA_REG_0__SCAN_IN, CONT_REG_7__SCAN_IN, CONT_REG_6__SCAN_IN, CONT_REG_5__SCAN_IN, CONT_REG_4__SCAN_IN, CONT_REG_3__SCAN_IN, CONT_REG_2__SCAN_IN, CONT_REG_1__SCAN_IN, CONT_REG_0__SCAN_IN, MAR_REG_7__SCAN_IN, MAR_REG_6__SCAN_IN
, MAR_REG_5__SCAN_IN, MAR_REG_4__SCAN_IN, MAR_REG_3__SCAN_IN, MAR_REG_2__SCAN_IN, MAR_REG_1__SCAN_IN, MAR_REG_0__SCAN_IN, X_REG_7__SCAN_IN, X_REG_6__SCAN_IN, X_REG_5__SCAN_IN, X_REG_4__SCAN_IN, X_REG_3__SCAN_IN, X_REG_2__SCAN_IN, X_REG_1__SCAN_IN, X_REG_0__SCAN_IN, Y_REG_3__SCAN_IN, Y_REG_1__SCAN_IN, Y_REG_5__SCAN_IN, T_REG_3__SCAN_IN, T_REG_5__SCAN_IN, T_REG_1__SCAN_IN, T_REG_0__SCAN_IN
, T_REG_4__SCAN_IN, T_REG_6__SCAN_IN, T_REG_2__SCAN_IN, Y_REG_4__SCAN_IN, Y_REG_0__SCAN_IN, Y_REG_2__SCAN_IN, Y_REG_6__SCAN_IN, STATO_REG_2__SCAN_IN, U358, U357, U356, U355, U354, U353, U352, U351, U350, U349, U348, U347, U346
, U345, U344, U343, U342, U341, U340, U339, U388, U389, U390, U391, U338, U337, U336, U335, U334, U333, U332, U331, U330, U394
, U329, U395, U396, U397, U398, U399, U400, U401, U328, U402, U403, U327, U324, U325, U326);
  input START;
  wire START;
  input STATO_REG_0__SCAN_IN;
  wire STATO_REG_0__SCAN_IN;
  input STATO_REG_1__SCAN_IN;
  wire STATO_REG_1__SCAN_IN;
  input PUNTI_RETTA_REG_7__SCAN_IN;
  wire PUNTI_RETTA_REG_7__SCAN_IN;
  input PUNTI_RETTA_REG_6__SCAN_IN;
  wire PUNTI_RETTA_REG_6__SCAN_IN;
  input PUNTI_RETTA_REG_5__SCAN_IN;
  wire PUNTI_RETTA_REG_5__SCAN_IN;
  input PUNTI_RETTA_REG_4__SCAN_IN;
  wire PUNTI_RETTA_REG_4__SCAN_IN;
  input PUNTI_RETTA_REG_3__SCAN_IN;
  wire PUNTI_RETTA_REG_3__SCAN_IN;
  input PUNTI_RETTA_REG_2__SCAN_IN;
  wire PUNTI_RETTA_REG_2__SCAN_IN;
  input PUNTI_RETTA_REG_1__SCAN_IN;
  wire PUNTI_RETTA_REG_1__SCAN_IN;
  input PUNTI_RETTA_REG_0__SCAN_IN;
  wire PUNTI_RETTA_REG_0__SCAN_IN;
  input CONT_REG_7__SCAN_IN;
  wire CONT_REG_7__SCAN_IN;
  input CONT_REG_6__SCAN_IN;
  wire CONT_REG_6__SCAN_IN;
  input CONT_REG_5__SCAN_IN;
  wire CONT_REG_5__SCAN_IN;
  input CONT_REG_4__SCAN_IN;
  wire CONT_REG_4__SCAN_IN;
  input CONT_REG_3__SCAN_IN;
  wire CONT_REG_3__SCAN_IN;
  input CONT_REG_2__SCAN_IN;
  wire CONT_REG_2__SCAN_IN;
  input CONT_REG_1__SCAN_IN;
  wire CONT_REG_1__SCAN_IN;
  input CONT_REG_0__SCAN_IN;
  wire CONT_REG_0__SCAN_IN;
  input MAR_REG_7__SCAN_IN;
  wire MAR_REG_7__SCAN_IN;
  input MAR_REG_6__SCAN_IN;
  wire MAR_REG_6__SCAN_IN;
  input MAR_REG_5__SCAN_IN;
  wire MAR_REG_5__SCAN_IN;
  input MAR_REG_4__SCAN_IN;
  wire MAR_REG_4__SCAN_IN;
  input MAR_REG_3__SCAN_IN;
  wire MAR_REG_3__SCAN_IN;
  input MAR_REG_2__SCAN_IN;
  wire MAR_REG_2__SCAN_IN;
  input MAR_REG_1__SCAN_IN;
  wire MAR_REG_1__SCAN_IN;
  input MAR_REG_0__SCAN_IN;
  wire MAR_REG_0__SCAN_IN;
  input X_REG_7__SCAN_IN;
  wire X_REG_7__SCAN_IN;
  input X_REG_6__SCAN_IN;
  wire X_REG_6__SCAN_IN;
  input X_REG_5__SCAN_IN;
  wire X_REG_5__SCAN_IN;
  input X_REG_4__SCAN_IN;
  wire X_REG_4__SCAN_IN;
  input X_REG_3__SCAN_IN;
  wire X_REG_3__SCAN_IN;
  input X_REG_2__SCAN_IN;
  wire X_REG_2__SCAN_IN;
  input X_REG_1__SCAN_IN;
  wire X_REG_1__SCAN_IN;
  input X_REG_0__SCAN_IN;
  wire X_REG_0__SCAN_IN;
  input Y_REG_3__SCAN_IN;
  wire Y_REG_3__SCAN_IN;
  input Y_REG_1__SCAN_IN;
  wire Y_REG_1__SCAN_IN;
  input Y_REG_5__SCAN_IN;
  wire Y_REG_5__SCAN_IN;
  input T_REG_3__SCAN_IN;
  wire T_REG_3__SCAN_IN;
  input T_REG_5__SCAN_IN;
  wire T_REG_5__SCAN_IN;
  input T_REG_1__SCAN_IN;
  wire T_REG_1__SCAN_IN;
  input T_REG_0__SCAN_IN;
  wire T_REG_0__SCAN_IN;
  input T_REG_4__SCAN_IN;
  wire T_REG_4__SCAN_IN;
  input T_REG_6__SCAN_IN;
  wire T_REG_6__SCAN_IN;
  input T_REG_2__SCAN_IN;
  wire T_REG_2__SCAN_IN;
  input Y_REG_4__SCAN_IN;
  wire Y_REG_4__SCAN_IN;
  input Y_REG_0__SCAN_IN;
  wire Y_REG_0__SCAN_IN;
  input Y_REG_2__SCAN_IN;
  wire Y_REG_2__SCAN_IN;
  input Y_REG_6__SCAN_IN;
  wire Y_REG_6__SCAN_IN;
  input STATO_REG_2__SCAN_IN;
  wire STATO_REG_2__SCAN_IN;
  output U358;
  wire U358;
  output U357;
  wire U357;
  output U356;
  wire U356;
  output U355;
  wire U355;
  output U354;
  wire U354;
  output U353;
  wire U353;
  output U352;
  wire U352;
  output U351;
  wire U351;
  output U350;
  wire U350;
  output U349;
  wire U349;
  output U348;
  wire U348;
  output U347;
  wire U347;
  output U346;
  wire U346;
  output U345;
  wire U345;
  output U344;
  wire U344;
  output U343;
  wire U343;
  output U342;
  wire U342;
  output U341;
  wire U341;
  output U340;
  wire U340;
  output U339;
  wire U339;
  output U388;
  wire U388;
  output U389;
  wire U389;
  output U390;
  wire U390;
  output U391;
  wire U391;
  output U338;
  wire U338;
  output U337;
  wire U337;
  output U336;
  wire U336;
  output U335;
  wire U335;
  output U334;
  wire U334;
  output U333;
  wire U333;
  output U332;
  wire U332;
  output U331;
  wire U331;
  output U330;
  wire U330;
  output U394;
  wire U394;
  output U329;
  wire U329;
  output U395;
  wire U395;
  output U396;
  wire U396;
  output U397;
  wire U397;
  output U398;
  wire U398;
  output U399;
  wire U399;
  output U400;
  wire U400;
  output U401;
  wire U401;
  output U328;
  wire U328;
  output U402;
  wire U402;
  output U403;
  wire U403;
  output U327;
  wire U327;
  output U324;
  wire U324;
  output U325;
  wire U325;
  output U326;
  wire U326;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  BUF_X1 _173_ (
    .A(STATO_REG_0__SCAN_IN),
    .Z(_000_)
  );
  NAND2_X1 _174_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_000_),
    .ZN(_001_)
  );
  BUF_X1 _175_ (
    .A(_001_),
    .Z(_002_)
  );
  BUF_X1 _176_ (
    .A(STATO_REG_2__SCAN_IN),
    .Z(_003_)
  );
  INV_X1 _177_ (
    .A(_003_),
    .ZN(_004_)
  );
  OR2_X1 _178_ (
    .A1(_004_),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_005_)
  );
  AND3_X1 _179_ (
    .A1(MAR_REG_2__SCAN_IN),
    .A2(MAR_REG_1__SCAN_IN),
    .A3(MAR_REG_0__SCAN_IN),
    .ZN(_006_)
  );
  NOR4_X1 _180_ (
    .A1(MAR_REG_4__SCAN_IN),
    .A2(MAR_REG_5__SCAN_IN),
    .A3(MAR_REG_6__SCAN_IN),
    .A4(MAR_REG_7__SCAN_IN),
    .ZN(_007_)
  );
  NAND3_X1 _181_ (
    .A1(MAR_REG_3__SCAN_IN),
    .A2(_006_),
    .A3(_007_),
    .ZN(_008_)
  );
  NAND2_X1 _182_ (
    .A1(_003_),
    .A2(START),
    .ZN(_009_)
  );
  OAI211_X1 _183_ (
    .A(_002_),
    .B(_005_),
    .C1(_008_),
    .C2(_009_),
    .ZN(U324)
  );
  NAND2_X1 _184_ (
    .A1(START),
    .A2(_000_),
    .ZN(_010_)
  );
  OR2_X1 _185_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_010_),
    .ZN(_011_)
  );
  NOR3_X1 _186_ (
    .A1(_004_),
    .A2(START),
    .A3(_008_),
    .ZN(_012_)
  );
  INV_X1 _187_ (
    .A(_000_),
    .ZN(_013_)
  );
  NAND2_X1 _188_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_013_),
    .ZN(_014_)
  );
  OAI221_X1 _189_ (
    .A(_011_),
    .B1(_012_),
    .B2(_014_),
    .C1(_004_),
    .C2(_013_),
    .ZN(U325)
  );
  INV_X1 _190_ (
    .A(START),
    .ZN(_015_)
  );
  NOR2_X1 _191_ (
    .A1(_003_),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_016_)
  );
  NAND2_X1 _192_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_017_)
  );
  NOR2_X1 _193_ (
    .A1(_008_),
    .A2(_017_),
    .ZN(_018_)
  );
  OAI21_X1 _194_ (
    .A(_015_),
    .B1(_016_),
    .B2(_018_),
    .ZN(_019_)
  );
  AND2_X1 _195_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_020_)
  );
  OAI21_X1 _196_ (
    .A(_019_),
    .B1(_020_),
    .B2(_000_),
    .ZN(U326)
  );
  OR2_X1 _197_ (
    .A1(MAR_REG_3__SCAN_IN),
    .A2(MAR_REG_1__SCAN_IN),
    .ZN(_021_)
  );
  NOR2_X1 _198_ (
    .A1(MAR_REG_2__SCAN_IN),
    .A2(_021_),
    .ZN(_022_)
  );
  NAND2_X1 _199_ (
    .A1(MAR_REG_0__SCAN_IN),
    .A2(_022_),
    .ZN(_023_)
  );
  INV_X1 _200_ (
    .A(MAR_REG_2__SCAN_IN),
    .ZN(_024_)
  );
  NAND3_X1 _201_ (
    .A1(MAR_REG_3__SCAN_IN),
    .A2(_024_),
    .A3(MAR_REG_1__SCAN_IN),
    .ZN(_025_)
  );
  OAI21_X1 _202_ (
    .A(_023_),
    .B1(_025_),
    .B2(MAR_REG_0__SCAN_IN),
    .ZN(_026_)
  );
  OR2_X1 _203_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(STATO_REG_0__SCAN_IN),
    .ZN(_027_)
  );
  NOR2_X1 _204_ (
    .A1(_004_),
    .A2(_027_),
    .ZN(_028_)
  );
  NAND2_X1 _205_ (
    .A1(_026_),
    .A2(_028_),
    .ZN(_029_)
  );
  INV_X1 _206_ (
    .A(Y_REG_6__SCAN_IN),
    .ZN(_030_)
  );
  OAI21_X1 _207_ (
    .A(_029_),
    .B1(_028_),
    .B2(_030_),
    .ZN(U327)
  );
  INV_X1 _208_ (
    .A(Y_REG_4__SCAN_IN),
    .ZN(_031_)
  );
  OAI21_X1 _209_ (
    .A(_029_),
    .B1(_028_),
    .B2(_031_),
    .ZN(U328)
  );
  INV_X1 _210_ (
    .A(Y_REG_5__SCAN_IN),
    .ZN(_032_)
  );
  OAI21_X1 _211_ (
    .A(_029_),
    .B1(_028_),
    .B2(_032_),
    .ZN(U329)
  );
  INV_X1 _212_ (
    .A(Y_REG_3__SCAN_IN),
    .ZN(_033_)
  );
  OAI21_X1 _213_ (
    .A(_029_),
    .B1(_028_),
    .B2(_033_),
    .ZN(U330)
  );
  NOR2_X1 _214_ (
    .A1(_004_),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_034_)
  );
  NOR2_X1 _215_ (
    .A1(_003_),
    .A2(_014_),
    .ZN(_035_)
  );
  NOR2_X1 _216_ (
    .A1(_034_),
    .A2(_035_),
    .ZN(_036_)
  );
  OAI21_X1 _217_ (
    .A(_025_),
    .B1(_021_),
    .B2(MAR_REG_2__SCAN_IN),
    .ZN(_037_)
  );
  AOI22_X1 _218_ (
    .A1(X_REG_0__SCAN_IN),
    .A2(_036_),
    .B1(_037_),
    .B2(_035_),
    .ZN(_038_)
  );
  INV_X1 _219_ (
    .A(X_REG_0__SCAN_IN),
    .ZN(_039_)
  );
  AOI21_X1 _220_ (
    .A(_039_),
    .B1(_013_),
    .B2(_020_),
    .ZN(_040_)
  );
  INV_X1 _221_ (
    .A(CONT_REG_0__SCAN_IN),
    .ZN(_041_)
  );
  NOR2_X1 _222_ (
    .A1(_041_),
    .A2(_017_),
    .ZN(_042_)
  );
  NOR2_X1 _223_ (
    .A1(_040_),
    .A2(_042_),
    .ZN(_043_)
  );
  NOR2_X1 _224_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_000_),
    .ZN(_044_)
  );
  AND2_X1 _225_ (
    .A1(T_REG_0__SCAN_IN),
    .A2(_044_),
    .ZN(_045_)
  );
  NAND3_X1 _226_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(_000_),
    .A3(Y_REG_0__SCAN_IN),
    .ZN(_046_)
  );
  OAI211_X1 _227_ (
    .A(_017_),
    .B(_046_),
    .C1(_003_),
    .C2(_039_),
    .ZN(_047_)
  );
  NOR2_X1 _228_ (
    .A1(_045_),
    .A2(_047_),
    .ZN(_048_)
  );
  XNOR2_X1 _229_ (
    .A(_043_),
    .B(_048_),
    .ZN(_049_)
  );
  OAI21_X1 _230_ (
    .A(_038_),
    .B1(_049_),
    .B2(_005_),
    .ZN(U331)
  );
  NAND2_X1 _231_ (
    .A1(MAR_REG_3__SCAN_IN),
    .A2(_006_),
    .ZN(_050_)
  );
  INV_X1 _232_ (
    .A(MAR_REG_1__SCAN_IN),
    .ZN(_051_)
  );
  NAND2_X1 _233_ (
    .A1(_051_),
    .A2(MAR_REG_0__SCAN_IN),
    .ZN(_052_)
  );
  OAI211_X1 _234_ (
    .A(_050_),
    .B(_052_),
    .C1(_025_),
    .C2(MAR_REG_0__SCAN_IN),
    .ZN(_053_)
  );
  AOI22_X1 _235_ (
    .A1(X_REG_1__SCAN_IN),
    .A2(_036_),
    .B1(_053_),
    .B2(_035_),
    .ZN(_054_)
  );
  OAI22_X1 _236_ (
    .A1(_040_),
    .A2(_042_),
    .B1(_045_),
    .B2(_047_),
    .ZN(_055_)
  );
  INV_X1 _237_ (
    .A(X_REG_1__SCAN_IN),
    .ZN(_056_)
  );
  AOI21_X1 _238_ (
    .A(_056_),
    .B1(_013_),
    .B2(_020_),
    .ZN(_057_)
  );
  INV_X1 _239_ (
    .A(CONT_REG_1__SCAN_IN),
    .ZN(_058_)
  );
  NOR2_X1 _240_ (
    .A1(_058_),
    .A2(_017_),
    .ZN(_059_)
  );
  NOR2_X1 _241_ (
    .A1(_057_),
    .A2(_059_),
    .ZN(_060_)
  );
  NAND3_X1 _242_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(_000_),
    .A3(Y_REG_1__SCAN_IN),
    .ZN(_061_)
  );
  INV_X1 _243_ (
    .A(T_REG_1__SCAN_IN),
    .ZN(_062_)
  );
  OAI221_X1 _244_ (
    .A(_061_),
    .B1(_027_),
    .B2(_062_),
    .C1(_003_),
    .C2(_056_),
    .ZN(_063_)
  );
  XNOR2_X1 _245_ (
    .A(_060_),
    .B(_063_),
    .ZN(_064_)
  );
  XOR2_X1 _246_ (
    .A(_055_),
    .B(_064_),
    .Z(_065_)
  );
  OAI21_X1 _247_ (
    .A(_054_),
    .B1(_065_),
    .B2(_005_),
    .ZN(U332)
  );
  NAND2_X1 _248_ (
    .A1(_023_),
    .A2(_025_),
    .ZN(_066_)
  );
  AOI22_X1 _249_ (
    .A1(X_REG_2__SCAN_IN),
    .A2(_036_),
    .B1(_066_),
    .B2(_035_),
    .ZN(_067_)
  );
  AND2_X1 _250_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(_000_),
    .ZN(_068_)
  );
  AOI222_X1 _251_ (
    .A1(_004_),
    .A2(X_REG_2__SCAN_IN),
    .B1(Y_REG_2__SCAN_IN),
    .B2(_068_),
    .C1(_044_),
    .C2(T_REG_2__SCAN_IN),
    .ZN(_069_)
  );
  NAND2_X1 _252_ (
    .A1(_013_),
    .A2(_020_),
    .ZN(_070_)
  );
  AOI22_X1 _253_ (
    .A1(CONT_REG_2__SCAN_IN),
    .A2(_020_),
    .B1(_070_),
    .B2(X_REG_2__SCAN_IN),
    .ZN(_071_)
  );
  XOR2_X1 _254_ (
    .A(_069_),
    .B(_071_),
    .Z(_072_)
  );
  NOR3_X1 _255_ (
    .A1(_057_),
    .A2(_059_),
    .A3(_063_),
    .ZN(_073_)
  );
  OAI21_X1 _256_ (
    .A(_063_),
    .B1(_059_),
    .B2(_057_),
    .ZN(_074_)
  );
  AND2_X1 _257_ (
    .A1(_055_),
    .A2(_074_),
    .ZN(_075_)
  );
  OR2_X1 _258_ (
    .A1(_073_),
    .A2(_075_),
    .ZN(_076_)
  );
  XNOR2_X1 _259_ (
    .A(_072_),
    .B(_076_),
    .ZN(_077_)
  );
  INV_X1 _260_ (
    .A(_077_),
    .ZN(_078_)
  );
  OAI21_X1 _261_ (
    .A(_067_),
    .B1(_078_),
    .B2(_005_),
    .ZN(U333)
  );
  NAND2_X1 _262_ (
    .A1(X_REG_3__SCAN_IN),
    .A2(_036_),
    .ZN(_079_)
  );
  NAND2_X1 _263_ (
    .A1(_026_),
    .A2(_035_),
    .ZN(_080_)
  );
  OAI21_X1 _264_ (
    .A(X_REG_3__SCAN_IN),
    .B1(_000_),
    .B2(_017_),
    .ZN(_081_)
  );
  INV_X1 _265_ (
    .A(CONT_REG_3__SCAN_IN),
    .ZN(_082_)
  );
  OAI21_X1 _266_ (
    .A(_081_),
    .B1(_017_),
    .B2(_082_),
    .ZN(_083_)
  );
  NAND2_X1 _267_ (
    .A1(T_REG_3__SCAN_IN),
    .A2(_044_),
    .ZN(_084_)
  );
  NAND2_X1 _268_ (
    .A1(_004_),
    .A2(X_REG_3__SCAN_IN),
    .ZN(_085_)
  );
  NAND2_X1 _269_ (
    .A1(Y_REG_3__SCAN_IN),
    .A2(_068_),
    .ZN(_086_)
  );
  NAND3_X1 _270_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_086_),
    .ZN(_087_)
  );
  XNOR2_X1 _271_ (
    .A(_083_),
    .B(_087_),
    .ZN(_088_)
  );
  NOR2_X1 _272_ (
    .A1(_069_),
    .A2(_071_),
    .ZN(_089_)
  );
  AOI221_X1 _273_ (
    .A(_073_),
    .B1(_069_),
    .B2(_071_),
    .C1(_074_),
    .C2(_055_),
    .ZN(_090_)
  );
  NOR2_X1 _274_ (
    .A1(_089_),
    .A2(_090_),
    .ZN(_091_)
  );
  XNOR2_X1 _275_ (
    .A(_088_),
    .B(_091_),
    .ZN(_092_)
  );
  OAI211_X1 _276_ (
    .A(_079_),
    .B(_080_),
    .C1(_005_),
    .C2(_092_),
    .ZN(U334)
  );
  NAND2_X1 _277_ (
    .A1(X_REG_4__SCAN_IN),
    .A2(_036_),
    .ZN(_093_)
  );
  INV_X1 _278_ (
    .A(_085_),
    .ZN(_094_)
  );
  NAND2_X1 _279_ (
    .A1(_084_),
    .A2(_086_),
    .ZN(_095_)
  );
  AND2_X1 _280_ (
    .A1(_083_),
    .A2(_087_),
    .ZN(_096_)
  );
  OAI33_X1 _281_ (
    .A1(_083_),
    .A2(_094_),
    .A3(_095_),
    .B1(_096_),
    .B2(_089_),
    .B3(_090_),
    .ZN(_097_)
  );
  AOI22_X1 _282_ (
    .A1(CONT_REG_4__SCAN_IN),
    .A2(_020_),
    .B1(_070_),
    .B2(X_REG_4__SCAN_IN),
    .ZN(_098_)
  );
  INV_X1 _283_ (
    .A(_098_),
    .ZN(_099_)
  );
  AOI22_X1 _284_ (
    .A1(Y_REG_4__SCAN_IN),
    .A2(_068_),
    .B1(_044_),
    .B2(T_REG_4__SCAN_IN),
    .ZN(_100_)
  );
  INV_X1 _285_ (
    .A(X_REG_4__SCAN_IN),
    .ZN(_101_)
  );
  OAI21_X1 _286_ (
    .A(_100_),
    .B1(_101_),
    .B2(_003_),
    .ZN(_102_)
  );
  NAND2_X1 _287_ (
    .A1(_099_),
    .A2(_102_),
    .ZN(_103_)
  );
  NOR2_X1 _288_ (
    .A1(_099_),
    .A2(_102_),
    .ZN(_104_)
  );
  AOI21_X1 _289_ (
    .A(_104_),
    .B1(_103_),
    .B2(_097_),
    .ZN(_105_)
  );
  AND2_X1 _290_ (
    .A1(_097_),
    .A2(_104_),
    .ZN(_106_)
  );
  OAI22_X1 _291_ (
    .A1(_097_),
    .A2(_103_),
    .B1(_105_),
    .B2(_106_),
    .ZN(_107_)
  );
  INV_X1 _292_ (
    .A(_107_),
    .ZN(_108_)
  );
  OAI211_X1 _293_ (
    .A(_080_),
    .B(_093_),
    .C1(_108_),
    .C2(_005_),
    .ZN(U335)
  );
  NAND2_X1 _294_ (
    .A1(X_REG_5__SCAN_IN),
    .A2(_036_),
    .ZN(_109_)
  );
  AOI22_X1 _295_ (
    .A1(CONT_REG_5__SCAN_IN),
    .A2(_020_),
    .B1(_070_),
    .B2(X_REG_5__SCAN_IN),
    .ZN(_110_)
  );
  NAND2_X1 _296_ (
    .A1(_004_),
    .A2(X_REG_5__SCAN_IN),
    .ZN(_111_)
  );
  AOI22_X1 _297_ (
    .A1(Y_REG_5__SCAN_IN),
    .A2(_068_),
    .B1(_044_),
    .B2(T_REG_5__SCAN_IN),
    .ZN(_112_)
  );
  AOI21_X1 _298_ (
    .A(_110_),
    .B1(_111_),
    .B2(_112_),
    .ZN(_113_)
  );
  AND3_X1 _299_ (
    .A1(_110_),
    .A2(_111_),
    .A3(_112_),
    .ZN(_114_)
  );
  NOR2_X1 _300_ (
    .A1(_113_),
    .A2(_114_),
    .ZN(_115_)
  );
  XOR2_X1 _301_ (
    .A(_105_),
    .B(_115_),
    .Z(_116_)
  );
  INV_X1 _302_ (
    .A(_116_),
    .ZN(_117_)
  );
  OAI211_X1 _303_ (
    .A(_080_),
    .B(_109_),
    .C1(_117_),
    .C2(_005_),
    .ZN(U336)
  );
  NAND2_X1 _304_ (
    .A1(X_REG_6__SCAN_IN),
    .A2(_036_),
    .ZN(_118_)
  );
  AOI222_X1 _305_ (
    .A1(_004_),
    .A2(X_REG_6__SCAN_IN),
    .B1(T_REG_6__SCAN_IN),
    .B2(_044_),
    .C1(_068_),
    .C2(Y_REG_6__SCAN_IN),
    .ZN(_119_)
  );
  AOI211_X1 _306_ (
    .A(_104_),
    .B(_114_),
    .C1(_103_),
    .C2(_097_),
    .ZN(_120_)
  );
  NAND2_X1 _307_ (
    .A1(X_REG_6__SCAN_IN),
    .A2(_070_),
    .ZN(_121_)
  );
  INV_X1 _308_ (
    .A(CONT_REG_6__SCAN_IN),
    .ZN(_122_)
  );
  OAI21_X1 _309_ (
    .A(_121_),
    .B1(_017_),
    .B2(_122_),
    .ZN(_123_)
  );
  OR3_X1 _310_ (
    .A1(_113_),
    .A2(_120_),
    .A3(_123_),
    .ZN(_124_)
  );
  OAI21_X1 _311_ (
    .A(_123_),
    .B1(_120_),
    .B2(_113_),
    .ZN(_125_)
  );
  NAND2_X1 _312_ (
    .A1(_124_),
    .A2(_125_),
    .ZN(_126_)
  );
  XNOR2_X1 _313_ (
    .A(_119_),
    .B(_126_),
    .ZN(_127_)
  );
  OAI211_X1 _314_ (
    .A(_080_),
    .B(_118_),
    .C1(_127_),
    .C2(_005_),
    .ZN(U337)
  );
  NOR3_X1 _315_ (
    .A1(_113_),
    .A2(_120_),
    .A3(_123_),
    .ZN(_128_)
  );
  AOI21_X1 _316_ (
    .A(_128_),
    .B1(_125_),
    .B2(_119_),
    .ZN(_129_)
  );
  NAND2_X1 _317_ (
    .A1(_034_),
    .A2(_129_),
    .ZN(_130_)
  );
  NAND2_X1 _318_ (
    .A1(X_REG_7__SCAN_IN),
    .A2(_036_),
    .ZN(_131_)
  );
  NAND3_X1 _319_ (
    .A1(_080_),
    .A2(_130_),
    .A3(_131_),
    .ZN(U338)
  );
  AND2_X1 _320_ (
    .A1(_008_),
    .A2(_020_),
    .ZN(_132_)
  );
  OAI21_X1 _321_ (
    .A(_001_),
    .B1(_010_),
    .B2(_003_),
    .ZN(_133_)
  );
  NOR2_X1 _322_ (
    .A1(_132_),
    .A2(_133_),
    .ZN(_134_)
  );
  AND2_X1 _323_ (
    .A1(MAR_REG_4__SCAN_IN),
    .A2(_134_),
    .ZN(U339)
  );
  AND2_X1 _324_ (
    .A1(MAR_REG_5__SCAN_IN),
    .A2(_134_),
    .ZN(U340)
  );
  AND2_X1 _325_ (
    .A1(MAR_REG_6__SCAN_IN),
    .A2(_134_),
    .ZN(U341)
  );
  AND2_X1 _326_ (
    .A1(MAR_REG_7__SCAN_IN),
    .A2(_134_),
    .ZN(U342)
  );
  NOR4_X1 _327_ (
    .A1(X_REG_4__SCAN_IN),
    .A2(X_REG_5__SCAN_IN),
    .A3(X_REG_6__SCAN_IN),
    .A4(X_REG_7__SCAN_IN),
    .ZN(_135_)
  );
  NOR4_X1 _328_ (
    .A1(X_REG_0__SCAN_IN),
    .A2(_056_),
    .A3(X_REG_2__SCAN_IN),
    .A4(X_REG_3__SCAN_IN),
    .ZN(_136_)
  );
  AND2_X1 _329_ (
    .A1(_135_),
    .A2(_136_),
    .ZN(_137_)
  );
  NAND2_X1 _330_ (
    .A1(_132_),
    .A2(_137_),
    .ZN(_138_)
  );
  OAI21_X1 _331_ (
    .A(_138_),
    .B1(_011_),
    .B2(_003_),
    .ZN(_139_)
  );
  OAI22_X1 _332_ (
    .A1(_049_),
    .A2(_138_),
    .B1(_139_),
    .B2(_041_),
    .ZN(U343)
  );
  OAI22_X1 _333_ (
    .A1(_065_),
    .A2(_138_),
    .B1(_139_),
    .B2(_058_),
    .ZN(U344)
  );
  INV_X1 _334_ (
    .A(CONT_REG_2__SCAN_IN),
    .ZN(_140_)
  );
  OAI22_X1 _335_ (
    .A1(_078_),
    .A2(_138_),
    .B1(_139_),
    .B2(_140_),
    .ZN(U345)
  );
  OAI22_X1 _336_ (
    .A1(_092_),
    .A2(_138_),
    .B1(_139_),
    .B2(_082_),
    .ZN(U346)
  );
  INV_X1 _337_ (
    .A(CONT_REG_4__SCAN_IN),
    .ZN(_141_)
  );
  OAI22_X1 _338_ (
    .A1(_108_),
    .A2(_138_),
    .B1(_139_),
    .B2(_141_),
    .ZN(U347)
  );
  INV_X1 _339_ (
    .A(CONT_REG_5__SCAN_IN),
    .ZN(_142_)
  );
  OAI22_X1 _340_ (
    .A1(_117_),
    .A2(_138_),
    .B1(_139_),
    .B2(_142_),
    .ZN(U348)
  );
  OAI22_X1 _341_ (
    .A1(_127_),
    .A2(_138_),
    .B1(_139_),
    .B2(_122_),
    .ZN(U349)
  );
  INV_X1 _342_ (
    .A(CONT_REG_7__SCAN_IN),
    .ZN(_143_)
  );
  NAND2_X1 _343_ (
    .A1(CONT_REG_7__SCAN_IN),
    .A2(_020_),
    .ZN(_144_)
  );
  XOR2_X1 _344_ (
    .A(_129_),
    .B(_144_),
    .Z(_145_)
  );
  OAI22_X1 _345_ (
    .A1(_143_),
    .A2(_139_),
    .B1(_145_),
    .B2(_138_),
    .ZN(U350)
  );
  NAND4_X1 _346_ (
    .A1(_003_),
    .A2(_015_),
    .A3(_018_),
    .A4(_137_),
    .ZN(_146_)
  );
  NOR2_X1 _347_ (
    .A1(_049_),
    .A2(_146_),
    .ZN(_147_)
  );
  NOR2_X1 _348_ (
    .A1(_000_),
    .A2(_018_),
    .ZN(_148_)
  );
  OR2_X1 _349_ (
    .A1(_019_),
    .A2(_148_),
    .ZN(_149_)
  );
  NOR3_X1 _350_ (
    .A1(_004_),
    .A2(_137_),
    .A3(_149_),
    .ZN(_150_)
  );
  AOI221_X1 _351_ (
    .A(_147_),
    .B1(_149_),
    .B2(PUNTI_RETTA_REG_0__SCAN_IN),
    .C1(CONT_REG_0__SCAN_IN),
    .C2(_150_),
    .ZN(_151_)
  );
  INV_X1 _352_ (
    .A(_151_),
    .ZN(U351)
  );
  NOR2_X1 _353_ (
    .A1(_065_),
    .A2(_146_),
    .ZN(_152_)
  );
  AOI221_X1 _354_ (
    .A(_152_),
    .B1(_149_),
    .B2(PUNTI_RETTA_REG_1__SCAN_IN),
    .C1(CONT_REG_1__SCAN_IN),
    .C2(_150_),
    .ZN(_153_)
  );
  INV_X1 _355_ (
    .A(_153_),
    .ZN(U352)
  );
  NOR2_X1 _356_ (
    .A1(_078_),
    .A2(_146_),
    .ZN(_154_)
  );
  AOI221_X1 _357_ (
    .A(_154_),
    .B1(_149_),
    .B2(PUNTI_RETTA_REG_2__SCAN_IN),
    .C1(CONT_REG_2__SCAN_IN),
    .C2(_150_),
    .ZN(_155_)
  );
  INV_X1 _358_ (
    .A(_155_),
    .ZN(U353)
  );
  AOI22_X1 _359_ (
    .A1(PUNTI_RETTA_REG_3__SCAN_IN),
    .A2(_149_),
    .B1(_150_),
    .B2(CONT_REG_3__SCAN_IN),
    .ZN(_156_)
  );
  OAI21_X1 _360_ (
    .A(_156_),
    .B1(_146_),
    .B2(_092_),
    .ZN(U354)
  );
  AOI22_X1 _361_ (
    .A1(PUNTI_RETTA_REG_4__SCAN_IN),
    .A2(_149_),
    .B1(_150_),
    .B2(CONT_REG_4__SCAN_IN),
    .ZN(_157_)
  );
  OAI21_X1 _362_ (
    .A(_157_),
    .B1(_146_),
    .B2(_108_),
    .ZN(U355)
  );
  AOI22_X1 _363_ (
    .A1(PUNTI_RETTA_REG_5__SCAN_IN),
    .A2(_149_),
    .B1(_150_),
    .B2(CONT_REG_5__SCAN_IN),
    .ZN(_158_)
  );
  OAI21_X1 _364_ (
    .A(_158_),
    .B1(_146_),
    .B2(_117_),
    .ZN(U356)
  );
  AOI22_X1 _365_ (
    .A1(PUNTI_RETTA_REG_6__SCAN_IN),
    .A2(_149_),
    .B1(_150_),
    .B2(CONT_REG_6__SCAN_IN),
    .ZN(_159_)
  );
  OAI21_X1 _366_ (
    .A(_159_),
    .B1(_146_),
    .B2(_127_),
    .ZN(U357)
  );
  AOI22_X1 _367_ (
    .A1(PUNTI_RETTA_REG_7__SCAN_IN),
    .A2(_149_),
    .B1(_150_),
    .B2(CONT_REG_7__SCAN_IN),
    .ZN(_160_)
  );
  OAI21_X1 _368_ (
    .A(_160_),
    .B1(_146_),
    .B2(_145_),
    .ZN(U358)
  );
  NOR2_X1 _369_ (
    .A1(MAR_REG_3__SCAN_IN),
    .A2(_006_),
    .ZN(_161_)
  );
  INV_X1 _370_ (
    .A(_132_),
    .ZN(_162_)
  );
  NAND2_X1 _371_ (
    .A1(_001_),
    .A2(_162_),
    .ZN(_163_)
  );
  AOI22_X1 _372_ (
    .A1(_050_),
    .A2(_163_),
    .B1(_134_),
    .B2(MAR_REG_3__SCAN_IN),
    .ZN(_164_)
  );
  NOR2_X1 _373_ (
    .A1(_161_),
    .A2(_164_),
    .ZN(U388)
  );
  INV_X1 _374_ (
    .A(_163_),
    .ZN(_165_)
  );
  AOI21_X1 _375_ (
    .A(MAR_REG_2__SCAN_IN),
    .B1(MAR_REG_1__SCAN_IN),
    .B2(MAR_REG_0__SCAN_IN),
    .ZN(_166_)
  );
  OAI33_X1 _376_ (
    .A1(_024_),
    .A2(_132_),
    .A3(_133_),
    .B1(_165_),
    .B2(_166_),
    .B3(_006_),
    .ZN(U389)
  );
  NOR2_X1 _377_ (
    .A1(MAR_REG_0__SCAN_IN),
    .A2(_016_),
    .ZN(_167_)
  );
  OAI21_X1 _378_ (
    .A(MAR_REG_1__SCAN_IN),
    .B1(_134_),
    .B2(_167_),
    .ZN(_168_)
  );
  OAI21_X1 _379_ (
    .A(_168_),
    .B1(_165_),
    .B2(_052_),
    .ZN(U390)
  );
  MUX2_X1 _380_ (
    .A(_167_),
    .B(MAR_REG_0__SCAN_IN),
    .S(_134_),
    .Z(U391)
  );
  MUX2_X1 _381_ (
    .A(Y_REG_1__SCAN_IN),
    .B(_053_),
    .S(_028_),
    .Z(U394)
  );
  NAND2_X1 _382_ (
    .A1(T_REG_3__SCAN_IN),
    .A2(_002_),
    .ZN(_169_)
  );
  OAI21_X1 _383_ (
    .A(_169_),
    .B1(_092_),
    .B2(_002_),
    .ZN(U395)
  );
  MUX2_X1 _384_ (
    .A(_116_),
    .B(T_REG_5__SCAN_IN),
    .S(_002_),
    .Z(U396)
  );
  NAND2_X1 _385_ (
    .A1(T_REG_1__SCAN_IN),
    .A2(_002_),
    .ZN(_170_)
  );
  OAI21_X1 _386_ (
    .A(_170_),
    .B1(_065_),
    .B2(_002_),
    .ZN(U397)
  );
  NAND2_X1 _387_ (
    .A1(T_REG_0__SCAN_IN),
    .A2(_002_),
    .ZN(_171_)
  );
  OAI21_X1 _388_ (
    .A(_171_),
    .B1(_049_),
    .B2(_002_),
    .ZN(U398)
  );
  MUX2_X1 _389_ (
    .A(_107_),
    .B(T_REG_4__SCAN_IN),
    .S(_001_),
    .Z(U399)
  );
  NAND2_X1 _390_ (
    .A1(T_REG_6__SCAN_IN),
    .A2(_002_),
    .ZN(_172_)
  );
  OAI21_X1 _391_ (
    .A(_172_),
    .B1(_127_),
    .B2(_002_),
    .ZN(U400)
  );
  MUX2_X1 _392_ (
    .A(_077_),
    .B(T_REG_2__SCAN_IN),
    .S(_001_),
    .Z(U401)
  );
  MUX2_X1 _393_ (
    .A(Y_REG_0__SCAN_IN),
    .B(_037_),
    .S(_028_),
    .Z(U402)
  );
  MUX2_X1 _394_ (
    .A(Y_REG_2__SCAN_IN),
    .B(_066_),
    .S(_028_),
    .Z(U403)
  );
endmodule
