/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module b11_C(X_IN_5_, X_IN_4_, X_IN_3_, X_IN_2_, X_IN_1_, X_IN_0_, STBI, STATO_REG_0__SCAN_IN, STATO_REG_1__SCAN_IN, STATO_REG_2__SCAN_IN, STATO_REG_3__SCAN_IN, X_OUT_REG_0__SCAN_IN, X_OUT_REG_1__SCAN_IN, X_OUT_REG_2__SCAN_IN, X_OUT_REG_3__SCAN_IN, X_OUT_REG_4__SCAN_IN, X_OUT_REG_5__SCAN_IN, CONT1_REG_0__SCAN_IN, CONT1_REG_1__SCAN_IN, R_IN_REG_5__SCAN_IN, R_IN_REG_4__SCAN_IN
, R_IN_REG_3__SCAN_IN, R_IN_REG_2__SCAN_IN, R_IN_REG_1__SCAN_IN, R_IN_REG_0__SCAN_IN, CONT_REG_5__SCAN_IN, CONT_REG_4__SCAN_IN, CONT_REG_3__SCAN_IN, CONT_REG_2__SCAN_IN, CONT_REG_1__SCAN_IN, CONT_REG_0__SCAN_IN, CONT1_REG_8__SCAN_IN, CONT1_REG_7__SCAN_IN, CONT1_REG_6__SCAN_IN, CONT1_REG_5__SCAN_IN, CONT1_REG_4__SCAN_IN, CONT1_REG_3__SCAN_IN, CONT1_REG_2__SCAN_IN, U404, U405, U406, U407
, U408, U409, U384, U383, U382, U381, U380, U379, U378, U377, U376, U375, U374, U373, U372, U371, U370, U369, U368, U367, U366
, U365, U364, U360, U361, U362, U363);
  input X_IN_5_;
  wire X_IN_5_;
  input X_IN_4_;
  wire X_IN_4_;
  input X_IN_3_;
  wire X_IN_3_;
  input X_IN_2_;
  wire X_IN_2_;
  input X_IN_1_;
  wire X_IN_1_;
  input X_IN_0_;
  wire X_IN_0_;
  input STBI;
  wire STBI;
  input STATO_REG_0__SCAN_IN;
  wire STATO_REG_0__SCAN_IN;
  input STATO_REG_1__SCAN_IN;
  wire STATO_REG_1__SCAN_IN;
  input STATO_REG_2__SCAN_IN;
  wire STATO_REG_2__SCAN_IN;
  input STATO_REG_3__SCAN_IN;
  wire STATO_REG_3__SCAN_IN;
  input X_OUT_REG_0__SCAN_IN;
  wire X_OUT_REG_0__SCAN_IN;
  input X_OUT_REG_1__SCAN_IN;
  wire X_OUT_REG_1__SCAN_IN;
  input X_OUT_REG_2__SCAN_IN;
  wire X_OUT_REG_2__SCAN_IN;
  input X_OUT_REG_3__SCAN_IN;
  wire X_OUT_REG_3__SCAN_IN;
  input X_OUT_REG_4__SCAN_IN;
  wire X_OUT_REG_4__SCAN_IN;
  input X_OUT_REG_5__SCAN_IN;
  wire X_OUT_REG_5__SCAN_IN;
  input CONT1_REG_0__SCAN_IN;
  wire CONT1_REG_0__SCAN_IN;
  input CONT1_REG_1__SCAN_IN;
  wire CONT1_REG_1__SCAN_IN;
  input R_IN_REG_5__SCAN_IN;
  wire R_IN_REG_5__SCAN_IN;
  input R_IN_REG_4__SCAN_IN;
  wire R_IN_REG_4__SCAN_IN;
  input R_IN_REG_3__SCAN_IN;
  wire R_IN_REG_3__SCAN_IN;
  input R_IN_REG_2__SCAN_IN;
  wire R_IN_REG_2__SCAN_IN;
  input R_IN_REG_1__SCAN_IN;
  wire R_IN_REG_1__SCAN_IN;
  input R_IN_REG_0__SCAN_IN;
  wire R_IN_REG_0__SCAN_IN;
  input CONT_REG_5__SCAN_IN;
  wire CONT_REG_5__SCAN_IN;
  input CONT_REG_4__SCAN_IN;
  wire CONT_REG_4__SCAN_IN;
  input CONT_REG_3__SCAN_IN;
  wire CONT_REG_3__SCAN_IN;
  input CONT_REG_2__SCAN_IN;
  wire CONT_REG_2__SCAN_IN;
  input CONT_REG_1__SCAN_IN;
  wire CONT_REG_1__SCAN_IN;
  input CONT_REG_0__SCAN_IN;
  wire CONT_REG_0__SCAN_IN;
  input CONT1_REG_8__SCAN_IN;
  wire CONT1_REG_8__SCAN_IN;
  input CONT1_REG_7__SCAN_IN;
  wire CONT1_REG_7__SCAN_IN;
  input CONT1_REG_6__SCAN_IN;
  wire CONT1_REG_6__SCAN_IN;
  input CONT1_REG_5__SCAN_IN;
  wire CONT1_REG_5__SCAN_IN;
  input CONT1_REG_4__SCAN_IN;
  wire CONT1_REG_4__SCAN_IN;
  input CONT1_REG_3__SCAN_IN;
  wire CONT1_REG_3__SCAN_IN;
  input CONT1_REG_2__SCAN_IN;
  wire CONT1_REG_2__SCAN_IN;
  output U404;
  wire U404;
  output U405;
  wire U405;
  output U406;
  wire U406;
  output U407;
  wire U407;
  output U408;
  wire U408;
  output U409;
  wire U409;
  output U384;
  wire U384;
  output U383;
  wire U383;
  output U382;
  wire U382;
  output U381;
  wire U381;
  output U380;
  wire U380;
  output U379;
  wire U379;
  output U378;
  wire U378;
  output U377;
  wire U377;
  output U376;
  wire U376;
  output U375;
  wire U375;
  output U374;
  wire U374;
  output U373;
  wire U373;
  output U372;
  wire U372;
  output U371;
  wire U371;
  output U370;
  wire U370;
  output U369;
  wire U369;
  output U368;
  wire U368;
  output U367;
  wire U367;
  output U366;
  wire U366;
  output U365;
  wire U365;
  output U364;
  wire U364;
  output U360;
  wire U360;
  output U361;
  wire U361;
  output U362;
  wire U362;
  output U363;
  wire U363;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  BUF_X1 _252_ (
    .A(STATO_REG_2__SCAN_IN),
    .Z(_224_)
  );
  NAND3_X1 _253_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_224_),
    .A3(STATO_REG_1__SCAN_IN),
    .ZN(_225_)
  );
  BUF_X1 _254_ (
    .A(R_IN_REG_2__SCAN_IN),
    .Z(_226_)
  );
  INV_X1 _255_ (
    .A(_226_),
    .ZN(_227_)
  );
  MUX2_X1 _256_ (
    .A(_227_),
    .B(R_IN_REG_4__SCAN_IN),
    .S(R_IN_REG_0__SCAN_IN),
    .Z(_228_)
  );
  BUF_X1 _257_ (
    .A(R_IN_REG_3__SCAN_IN),
    .Z(_229_)
  );
  INV_X1 _258_ (
    .A(_229_),
    .ZN(_230_)
  );
  MUX2_X1 _259_ (
    .A(_230_),
    .B(_226_),
    .S(R_IN_REG_1__SCAN_IN),
    .Z(_231_)
  );
  INV_X1 _260_ (
    .A(R_IN_REG_4__SCAN_IN),
    .ZN(_232_)
  );
  INV_X1 _261_ (
    .A(R_IN_REG_5__SCAN_IN),
    .ZN(_233_)
  );
  MUX2_X1 _262_ (
    .A(_229_),
    .B(_232_),
    .S(_233_),
    .Z(_234_)
  );
  NAND3_X1 _263_ (
    .A1(_228_),
    .A2(_231_),
    .A3(_234_),
    .ZN(_235_)
  );
  INV_X1 _264_ (
    .A(STATO_REG_1__SCAN_IN),
    .ZN(_236_)
  );
  OR2_X1 _265_ (
    .A1(STATO_REG_2__SCAN_IN),
    .A2(_236_),
    .ZN(_237_)
  );
  OR2_X1 _266_ (
    .A1(_235_),
    .A2(_237_),
    .ZN(_238_)
  );
  CLKBUF_X1 _267_ (
    .A(STATO_REG_0__SCAN_IN),
    .Z(_239_)
  );
  OAI21_X1 _268_ (
    .A(_225_),
    .B1(_238_),
    .B2(_239_),
    .ZN(U360)
  );
  NAND2_X1 _269_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_240_)
  );
  XNOR2_X1 _270_ (
    .A(_224_),
    .B(_240_),
    .ZN(U361)
  );
  INV_X1 _271_ (
    .A(STATO_REG_0__SCAN_IN),
    .ZN(_241_)
  );
  INV_X1 _272_ (
    .A(CONT1_REG_8__SCAN_IN),
    .ZN(_242_)
  );
  INV_X1 _273_ (
    .A(CONT1_REG_5__SCAN_IN),
    .ZN(_243_)
  );
  NOR2_X1 _274_ (
    .A1(CONT1_REG_6__SCAN_IN),
    .A2(CONT1_REG_7__SCAN_IN),
    .ZN(_244_)
  );
  BUF_X1 _275_ (
    .A(CONT1_REG_2__SCAN_IN),
    .Z(_245_)
  );
  OAI21_X1 _276_ (
    .A(CONT1_REG_4__SCAN_IN),
    .B1(_245_),
    .B2(CONT1_REG_1__SCAN_IN),
    .ZN(_246_)
  );
  OAI21_X1 _277_ (
    .A(CONT1_REG_3__SCAN_IN),
    .B1(CONT1_REG_0__SCAN_IN),
    .B2(_245_),
    .ZN(_247_)
  );
  OAI211_X1 _278_ (
    .A(_243_),
    .B(_244_),
    .C1(_246_),
    .C2(_247_),
    .ZN(_248_)
  );
  AOI21_X1 _279_ (
    .A(_241_),
    .B1(_242_),
    .B2(_248_),
    .ZN(_249_)
  );
  BUF_X1 _280_ (
    .A(R_IN_REG_1__SCAN_IN),
    .Z(_250_)
  );
  AOI21_X1 _281_ (
    .A(STATO_REG_0__SCAN_IN),
    .B1(_250_),
    .B2(_236_),
    .ZN(_251_)
  );
  OAI211_X1 _282_ (
    .A(_224_),
    .B(_240_),
    .C1(_249_),
    .C2(_251_),
    .ZN(_000_)
  );
  NOR2_X1 _283_ (
    .A1(_239_),
    .A2(_237_),
    .ZN(_001_)
  );
  OAI211_X1 _284_ (
    .A(_229_),
    .B(R_IN_REG_4__SCAN_IN),
    .C1(_226_),
    .C2(R_IN_REG_0__SCAN_IN),
    .ZN(_002_)
  );
  INV_X1 _285_ (
    .A(R_IN_REG_1__SCAN_IN),
    .ZN(_003_)
  );
  AOI21_X1 _286_ (
    .A(_002_),
    .B1(_227_),
    .B2(_003_),
    .ZN(_004_)
  );
  NOR2_X1 _287_ (
    .A1(R_IN_REG_5__SCAN_IN),
    .A2(_004_),
    .ZN(_005_)
  );
  NAND3_X1 _288_ (
    .A1(_235_),
    .A2(_001_),
    .A3(_005_),
    .ZN(_006_)
  );
  NOR2_X1 _289_ (
    .A1(_224_),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_007_)
  );
  NAND2_X1 _290_ (
    .A1(_239_),
    .A2(_007_),
    .ZN(_008_)
  );
  OAI211_X1 _291_ (
    .A(_000_),
    .B(_006_),
    .C1(_008_),
    .C2(STBI),
    .ZN(U362)
  );
  NAND2_X1 _292_ (
    .A1(_235_),
    .A2(_001_),
    .ZN(_009_)
  );
  OAI221_X1 _293_ (
    .A(_236_),
    .B1(STBI),
    .B2(_224_),
    .C1(_239_),
    .C2(_250_),
    .ZN(_010_)
  );
  NAND2_X1 _294_ (
    .A1(_241_),
    .A2(_007_),
    .ZN(_011_)
  );
  BUF_X1 _295_ (
    .A(_011_),
    .Z(_012_)
  );
  NAND2_X1 _296_ (
    .A1(_224_),
    .A2(STATO_REG_1__SCAN_IN),
    .ZN(_013_)
  );
  NOR2_X1 _297_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_013_),
    .ZN(_014_)
  );
  OAI21_X1 _298_ (
    .A(_014_),
    .B1(_244_),
    .B2(CONT1_REG_8__SCAN_IN),
    .ZN(_015_)
  );
  NAND4_X1 _299_ (
    .A1(_009_),
    .A2(_010_),
    .A3(_012_),
    .A4(_015_),
    .ZN(U363)
  );
  BUF_X1 _300_ (
    .A(STATO_REG_3__SCAN_IN),
    .Z(_016_)
  );
  AND2_X1 _301_ (
    .A1(_016_),
    .A2(CONT1_REG_0__SCAN_IN),
    .ZN(_017_)
  );
  MUX2_X1 _302_ (
    .A(_017_),
    .B(X_OUT_REG_0__SCAN_IN),
    .S(_012_),
    .Z(U364)
  );
  INV_X1 _303_ (
    .A(STATO_REG_3__SCAN_IN),
    .ZN(_018_)
  );
  NOR3_X1 _304_ (
    .A1(_018_),
    .A2(_242_),
    .A3(_011_),
    .ZN(_019_)
  );
  NAND2_X1 _305_ (
    .A1(_016_),
    .A2(CONT1_REG_0__SCAN_IN),
    .ZN(_020_)
  );
  XOR2_X1 _306_ (
    .A(STATO_REG_3__SCAN_IN),
    .B(CONT1_REG_1__SCAN_IN),
    .Z(_021_)
  );
  NAND2_X1 _307_ (
    .A1(_020_),
    .A2(_021_),
    .ZN(_022_)
  );
  INV_X1 _308_ (
    .A(_022_),
    .ZN(_023_)
  );
  BUF_X1 _309_ (
    .A(CONT1_REG_1__SCAN_IN),
    .Z(_024_)
  );
  AOI21_X1 _310_ (
    .A(_023_),
    .B1(_017_),
    .B2(_024_),
    .ZN(_025_)
  );
  NOR3_X1 _311_ (
    .A1(_018_),
    .A2(CONT1_REG_8__SCAN_IN),
    .A3(_012_),
    .ZN(_026_)
  );
  AOI222_X1 _312_ (
    .A1(X_OUT_REG_1__SCAN_IN),
    .A2(_012_),
    .B1(_019_),
    .B2(_025_),
    .C1(_026_),
    .C2(_024_),
    .ZN(_027_)
  );
  INV_X1 _313_ (
    .A(_027_),
    .ZN(U365)
  );
  INV_X1 _314_ (
    .A(CONT1_REG_2__SCAN_IN),
    .ZN(_028_)
  );
  XNOR2_X1 _315_ (
    .A(_028_),
    .B(_022_),
    .ZN(_029_)
  );
  AOI222_X1 _316_ (
    .A1(X_OUT_REG_2__SCAN_IN),
    .A2(_012_),
    .B1(_019_),
    .B2(_029_),
    .C1(_026_),
    .C2(_245_),
    .ZN(_030_)
  );
  INV_X1 _317_ (
    .A(_030_),
    .ZN(U366)
  );
  NAND2_X1 _318_ (
    .A1(_016_),
    .A2(CONT1_REG_3__SCAN_IN),
    .ZN(_031_)
  );
  NOR3_X1 _319_ (
    .A1(CONT1_REG_8__SCAN_IN),
    .A2(_012_),
    .A3(_031_),
    .ZN(_032_)
  );
  AOI21_X1 _320_ (
    .A(_245_),
    .B1(_020_),
    .B2(_021_),
    .ZN(_033_)
  );
  NOR2_X1 _321_ (
    .A1(_018_),
    .A2(_028_),
    .ZN(_034_)
  );
  NOR2_X1 _322_ (
    .A1(_033_),
    .A2(_034_),
    .ZN(_035_)
  );
  XNOR2_X1 _323_ (
    .A(STATO_REG_3__SCAN_IN),
    .B(CONT1_REG_3__SCAN_IN),
    .ZN(_036_)
  );
  XNOR2_X1 _324_ (
    .A(_035_),
    .B(_036_),
    .ZN(_037_)
  );
  AOI221_X1 _325_ (
    .A(_032_),
    .B1(_037_),
    .B2(_019_),
    .C1(X_OUT_REG_3__SCAN_IN),
    .C2(_012_),
    .ZN(_038_)
  );
  INV_X1 _326_ (
    .A(_038_),
    .ZN(U367)
  );
  NOR3_X1 _327_ (
    .A1(_033_),
    .A2(_034_),
    .A3(_036_),
    .ZN(_039_)
  );
  XNOR2_X1 _328_ (
    .A(_016_),
    .B(CONT1_REG_4__SCAN_IN),
    .ZN(_040_)
  );
  XNOR2_X1 _329_ (
    .A(_039_),
    .B(_040_),
    .ZN(_041_)
  );
  AOI222_X1 _330_ (
    .A1(X_OUT_REG_4__SCAN_IN),
    .A2(_012_),
    .B1(_019_),
    .B2(_041_),
    .C1(_026_),
    .C2(CONT1_REG_4__SCAN_IN),
    .ZN(_042_)
  );
  INV_X1 _331_ (
    .A(_042_),
    .ZN(U368)
  );
  BUF_X1 _332_ (
    .A(CONT1_REG_5__SCAN_IN),
    .Z(_043_)
  );
  NOR4_X1 _333_ (
    .A1(_033_),
    .A2(_034_),
    .A3(_036_),
    .A4(_040_),
    .ZN(_044_)
  );
  XNOR2_X1 _334_ (
    .A(_043_),
    .B(_044_),
    .ZN(_045_)
  );
  AOI222_X1 _335_ (
    .A1(X_OUT_REG_5__SCAN_IN),
    .A2(_012_),
    .B1(_019_),
    .B2(_045_),
    .C1(_026_),
    .C2(_043_),
    .ZN(_046_)
  );
  INV_X1 _336_ (
    .A(_046_),
    .ZN(U369)
  );
  NOR3_X1 _337_ (
    .A1(_224_),
    .A2(R_IN_REG_0__SCAN_IN),
    .A3(_240_),
    .ZN(_047_)
  );
  NAND2_X1 _338_ (
    .A1(CONT_REG_0__SCAN_IN),
    .A2(_047_),
    .ZN(_048_)
  );
  AND2_X1 _339_ (
    .A1(CONT1_REG_0__SCAN_IN),
    .A2(_227_),
    .ZN(_049_)
  );
  NOR2_X1 _340_ (
    .A1(_241_),
    .A2(_013_),
    .ZN(_050_)
  );
  OAI21_X1 _341_ (
    .A(_050_),
    .B1(_227_),
    .B2(CONT1_REG_0__SCAN_IN),
    .ZN(_051_)
  );
  OAI21_X1 _342_ (
    .A(STATO_REG_1__SCAN_IN),
    .B1(CONT1_REG_8__SCAN_IN),
    .B2(_244_),
    .ZN(_052_)
  );
  NAND2_X1 _343_ (
    .A1(_224_),
    .A2(_052_),
    .ZN(_053_)
  );
  OR2_X1 _344_ (
    .A1(_249_),
    .A2(_053_),
    .ZN(_054_)
  );
  NOR2_X1 _345_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_054_),
    .ZN(_055_)
  );
  XOR2_X1 _346_ (
    .A(CONT1_REG_0__SCAN_IN),
    .B(R_IN_REG_0__SCAN_IN),
    .Z(_056_)
  );
  AOI21_X1 _347_ (
    .A(_237_),
    .B1(_235_),
    .B2(_241_),
    .ZN(_057_)
  );
  AOI22_X1 _348_ (
    .A1(_055_),
    .A2(_056_),
    .B1(_057_),
    .B2(R_IN_REG_0__SCAN_IN),
    .ZN(_058_)
  );
  OAI221_X1 _349_ (
    .A(_048_),
    .B1(_049_),
    .B2(_051_),
    .C1(_058_),
    .C2(_239_),
    .ZN(_059_)
  );
  AND3_X1 _350_ (
    .A1(_240_),
    .A2(_238_),
    .A3(_054_),
    .ZN(_060_)
  );
  OR2_X1 _351_ (
    .A1(STATO_REG_1__SCAN_IN),
    .A2(_054_),
    .ZN(_061_)
  );
  NOR2_X1 _352_ (
    .A1(_241_),
    .A2(_061_),
    .ZN(_062_)
  );
  OR3_X1 _353_ (
    .A1(_014_),
    .A2(_060_),
    .A3(_062_),
    .ZN(_063_)
  );
  AOI21_X1 _354_ (
    .A(_059_),
    .B1(_063_),
    .B2(CONT1_REG_0__SCAN_IN),
    .ZN(_064_)
  );
  INV_X1 _355_ (
    .A(_064_),
    .ZN(U370)
  );
  INV_X1 _356_ (
    .A(R_IN_REG_0__SCAN_IN),
    .ZN(_065_)
  );
  NOR3_X1 _357_ (
    .A1(_224_),
    .A2(_065_),
    .A3(_240_),
    .ZN(_066_)
  );
  AOI22_X1 _358_ (
    .A1(CONT_REG_1__SCAN_IN),
    .A2(_047_),
    .B1(_066_),
    .B2(CONT_REG_0__SCAN_IN),
    .ZN(_067_)
  );
  AND2_X1 _359_ (
    .A1(R_IN_REG_3__SCAN_IN),
    .A2(R_IN_REG_2__SCAN_IN),
    .ZN(_068_)
  );
  NOR2_X1 _360_ (
    .A1(_049_),
    .A2(_068_),
    .ZN(_069_)
  );
  XNOR2_X1 _361_ (
    .A(_024_),
    .B(_069_),
    .ZN(_070_)
  );
  OAI21_X1 _362_ (
    .A(_067_),
    .B1(_070_),
    .B2(_225_),
    .ZN(_071_)
  );
  AOI221_X1 _363_ (
    .A(_071_),
    .B1(_062_),
    .B2(_025_),
    .C1(_024_),
    .C2(_060_),
    .ZN(_072_)
  );
  INV_X1 _364_ (
    .A(CONT1_REG_1__SCAN_IN),
    .ZN(_073_)
  );
  NOR2_X1 _365_ (
    .A1(_013_),
    .A2(_060_),
    .ZN(_074_)
  );
  MUX2_X1 _366_ (
    .A(_003_),
    .B(R_IN_REG_0__SCAN_IN),
    .S(CONT1_REG_0__SCAN_IN),
    .Z(_075_)
  );
  XNOR2_X1 _367_ (
    .A(_024_),
    .B(_075_),
    .ZN(_076_)
  );
  AOI222_X1 _368_ (
    .A1(_073_),
    .A2(_074_),
    .B1(_076_),
    .B2(_055_),
    .C1(_057_),
    .C2(_250_),
    .ZN(_077_)
  );
  OAI21_X1 _369_ (
    .A(_072_),
    .B1(_077_),
    .B2(_239_),
    .ZN(U371)
  );
  AOI22_X1 _370_ (
    .A1(CONT_REG_2__SCAN_IN),
    .A2(_047_),
    .B1(_066_),
    .B2(CONT_REG_1__SCAN_IN),
    .ZN(_078_)
  );
  NOR2_X1 _371_ (
    .A1(_229_),
    .A2(_226_),
    .ZN(_079_)
  );
  XNOR2_X1 _372_ (
    .A(_028_),
    .B(_079_),
    .ZN(_080_)
  );
  NOR2_X1 _373_ (
    .A1(_073_),
    .A2(_068_),
    .ZN(_081_)
  );
  NOR2_X1 _374_ (
    .A1(_049_),
    .A2(_081_),
    .ZN(_082_)
  );
  XNOR2_X1 _375_ (
    .A(_080_),
    .B(_082_),
    .ZN(_083_)
  );
  OAI21_X1 _376_ (
    .A(_078_),
    .B1(_083_),
    .B2(_225_),
    .ZN(_084_)
  );
  AOI221_X1 _377_ (
    .A(_084_),
    .B1(_062_),
    .B2(_029_),
    .C1(_245_),
    .C2(_060_),
    .ZN(_085_)
  );
  XNOR2_X1 _378_ (
    .A(R_IN_REG_1__SCAN_IN),
    .B(_245_),
    .ZN(_086_)
  );
  XNOR2_X1 _379_ (
    .A(_227_),
    .B(_086_),
    .ZN(_087_)
  );
  NAND2_X1 _380_ (
    .A1(_003_),
    .A2(_024_),
    .ZN(_088_)
  );
  OAI21_X1 _381_ (
    .A(_088_),
    .B1(_075_),
    .B2(_024_),
    .ZN(_089_)
  );
  XNOR2_X1 _382_ (
    .A(_087_),
    .B(_089_),
    .ZN(_090_)
  );
  XOR2_X1 _383_ (
    .A(_024_),
    .B(_245_),
    .Z(_091_)
  );
  AOI222_X1 _384_ (
    .A1(_226_),
    .A2(_057_),
    .B1(_090_),
    .B2(_055_),
    .C1(_091_),
    .C2(_074_),
    .ZN(_092_)
  );
  OAI21_X1 _385_ (
    .A(_085_),
    .B1(_092_),
    .B2(_239_),
    .ZN(U372)
  );
  AOI22_X1 _386_ (
    .A1(CONT_REG_3__SCAN_IN),
    .A2(_047_),
    .B1(_066_),
    .B2(CONT_REG_2__SCAN_IN),
    .ZN(_093_)
  );
  NOR2_X1 _387_ (
    .A1(_028_),
    .A2(_079_),
    .ZN(_094_)
  );
  OAI33_X1 _388_ (
    .A1(_229_),
    .A2(_226_),
    .A3(_245_),
    .B1(_049_),
    .B2(_094_),
    .B3(_081_),
    .ZN(_095_)
  );
  OAI21_X1 _389_ (
    .A(CONT1_REG_3__SCAN_IN),
    .B1(_068_),
    .B2(_079_),
    .ZN(_096_)
  );
  NOR3_X1 _390_ (
    .A1(CONT1_REG_3__SCAN_IN),
    .A2(_068_),
    .A3(_079_),
    .ZN(_097_)
  );
  INV_X1 _391_ (
    .A(_097_),
    .ZN(_098_)
  );
  NAND2_X1 _392_ (
    .A1(_096_),
    .A2(_098_),
    .ZN(_099_)
  );
  XNOR2_X1 _393_ (
    .A(_095_),
    .B(_099_),
    .ZN(_100_)
  );
  OAI21_X1 _394_ (
    .A(_093_),
    .B1(_100_),
    .B2(_225_),
    .ZN(_101_)
  );
  AOI221_X1 _395_ (
    .A(_101_),
    .B1(_062_),
    .B2(_037_),
    .C1(CONT1_REG_3__SCAN_IN),
    .C2(_060_),
    .ZN(_102_)
  );
  AND3_X1 _396_ (
    .A1(_024_),
    .A2(CONT1_REG_3__SCAN_IN),
    .A3(_245_),
    .ZN(_103_)
  );
  AOI21_X1 _397_ (
    .A(CONT1_REG_3__SCAN_IN),
    .B1(_245_),
    .B2(_024_),
    .ZN(_104_)
  );
  OR2_X1 _398_ (
    .A1(_103_),
    .A2(_104_),
    .ZN(_105_)
  );
  XNOR2_X1 _399_ (
    .A(_250_),
    .B(CONT1_REG_3__SCAN_IN),
    .ZN(_106_)
  );
  NOR2_X1 _400_ (
    .A1(_229_),
    .A2(_106_),
    .ZN(_107_)
  );
  AND2_X1 _401_ (
    .A1(_229_),
    .A2(_106_),
    .ZN(_108_)
  );
  NOR2_X1 _402_ (
    .A1(_107_),
    .A2(_108_),
    .ZN(_109_)
  );
  NOR2_X1 _403_ (
    .A1(_226_),
    .A2(_086_),
    .ZN(_110_)
  );
  NAND2_X1 _404_ (
    .A1(_226_),
    .A2(_086_),
    .ZN(_111_)
  );
  AOI21_X1 _405_ (
    .A(_110_),
    .B1(_111_),
    .B2(_089_),
    .ZN(_112_)
  );
  XOR2_X1 _406_ (
    .A(_109_),
    .B(_112_),
    .Z(_113_)
  );
  AOI222_X1 _407_ (
    .A1(_229_),
    .A2(_057_),
    .B1(_105_),
    .B2(_074_),
    .C1(_113_),
    .C2(_055_),
    .ZN(_114_)
  );
  OAI21_X1 _408_ (
    .A(_102_),
    .B1(_114_),
    .B2(_239_),
    .ZN(U373)
  );
  NAND2_X1 _409_ (
    .A1(_241_),
    .A2(_074_),
    .ZN(_115_)
  );
  XNOR2_X1 _410_ (
    .A(CONT1_REG_4__SCAN_IN),
    .B(_104_),
    .ZN(_116_)
  );
  NOR2_X1 _411_ (
    .A1(_115_),
    .A2(_116_),
    .ZN(_117_)
  );
  AOI222_X1 _412_ (
    .A1(CONT1_REG_4__SCAN_IN),
    .A2(_060_),
    .B1(_047_),
    .B2(CONT_REG_4__SCAN_IN),
    .C1(_066_),
    .C2(CONT_REG_3__SCAN_IN),
    .ZN(_118_)
  );
  XOR2_X1 _413_ (
    .A(CONT1_REG_4__SCAN_IN),
    .B(_226_),
    .Z(_119_)
  );
  AOI21_X1 _414_ (
    .A(_097_),
    .B1(_095_),
    .B2(_096_),
    .ZN(_120_)
  );
  XNOR2_X1 _415_ (
    .A(_119_),
    .B(_120_),
    .ZN(_121_)
  );
  OAI21_X1 _416_ (
    .A(_118_),
    .B1(_121_),
    .B2(_225_),
    .ZN(_122_)
  );
  AOI211_X1 _417_ (
    .A(_117_),
    .B(_122_),
    .C1(_041_),
    .C2(_062_),
    .ZN(_123_)
  );
  XNOR2_X1 _418_ (
    .A(_250_),
    .B(CONT1_REG_4__SCAN_IN),
    .ZN(_124_)
  );
  XNOR2_X1 _419_ (
    .A(_232_),
    .B(_124_),
    .ZN(_125_)
  );
  AOI211_X1 _420_ (
    .A(_110_),
    .B(_107_),
    .C1(_089_),
    .C2(_111_),
    .ZN(_126_)
  );
  NOR2_X1 _421_ (
    .A1(_108_),
    .A2(_126_),
    .ZN(_127_)
  );
  XNOR2_X1 _422_ (
    .A(_125_),
    .B(_127_),
    .ZN(_128_)
  );
  AOI22_X1 _423_ (
    .A1(R_IN_REG_4__SCAN_IN),
    .A2(_057_),
    .B1(_128_),
    .B2(_055_),
    .ZN(_129_)
  );
  OAI21_X1 _424_ (
    .A(_123_),
    .B1(_129_),
    .B2(_239_),
    .ZN(U374)
  );
  XNOR2_X1 _425_ (
    .A(_250_),
    .B(CONT1_REG_5__SCAN_IN),
    .ZN(_130_)
  );
  NOR2_X1 _426_ (
    .A1(R_IN_REG_5__SCAN_IN),
    .A2(_130_),
    .ZN(_131_)
  );
  INV_X1 _427_ (
    .A(_131_),
    .ZN(_132_)
  );
  NAND2_X1 _428_ (
    .A1(R_IN_REG_5__SCAN_IN),
    .A2(_130_),
    .ZN(_133_)
  );
  NAND2_X1 _429_ (
    .A1(_132_),
    .A2(_133_),
    .ZN(_134_)
  );
  NOR2_X1 _430_ (
    .A1(R_IN_REG_4__SCAN_IN),
    .A2(_124_),
    .ZN(_135_)
  );
  AOI211_X1 _431_ (
    .A(_108_),
    .B(_126_),
    .C1(_124_),
    .C2(R_IN_REG_4__SCAN_IN),
    .ZN(_136_)
  );
  OR2_X1 _432_ (
    .A1(_135_),
    .A2(_136_),
    .ZN(_137_)
  );
  AOI211_X1 _433_ (
    .A(_239_),
    .B(_061_),
    .C1(_134_),
    .C2(_137_),
    .ZN(_138_)
  );
  OAI21_X1 _434_ (
    .A(_138_),
    .B1(_137_),
    .B2(_134_),
    .ZN(_139_)
  );
  AOI222_X1 _435_ (
    .A1(_043_),
    .A2(_060_),
    .B1(_062_),
    .B2(_045_),
    .C1(_066_),
    .C2(CONT_REG_4__SCAN_IN),
    .ZN(_140_)
  );
  INV_X1 _436_ (
    .A(CONT1_REG_4__SCAN_IN),
    .ZN(_141_)
  );
  AND3_X1 _437_ (
    .A1(_141_),
    .A2(_243_),
    .A3(_104_),
    .ZN(_142_)
  );
  AOI21_X1 _438_ (
    .A(_243_),
    .B1(_104_),
    .B2(_141_),
    .ZN(_143_)
  );
  OAI33_X1 _439_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_233_),
    .A3(_238_),
    .B1(_115_),
    .B2(_142_),
    .B3(_143_),
    .ZN(_144_)
  );
  NOR2_X1 _440_ (
    .A1(_141_),
    .A2(_227_),
    .ZN(_145_)
  );
  AOI221_X1 _441_ (
    .A(_097_),
    .B1(_095_),
    .B2(_096_),
    .C1(_141_),
    .C2(_227_),
    .ZN(_146_)
  );
  OR3_X1 _442_ (
    .A1(_043_),
    .A2(_145_),
    .A3(_146_),
    .ZN(_147_)
  );
  OAI21_X1 _443_ (
    .A(_043_),
    .B1(_145_),
    .B2(_146_),
    .ZN(_148_)
  );
  NAND2_X1 _444_ (
    .A1(_147_),
    .A2(_148_),
    .ZN(_149_)
  );
  XNOR2_X1 _445_ (
    .A(_079_),
    .B(_149_),
    .ZN(_150_)
  );
  AOI221_X1 _446_ (
    .A(_144_),
    .B1(_150_),
    .B2(_050_),
    .C1(CONT_REG_5__SCAN_IN),
    .C2(_047_),
    .ZN(_151_)
  );
  NAND3_X1 _447_ (
    .A1(_139_),
    .A2(_140_),
    .A3(_151_),
    .ZN(U375)
  );
  NOR2_X1 _448_ (
    .A1(_043_),
    .A2(_044_),
    .ZN(_152_)
  );
  INV_X1 _449_ (
    .A(CONT1_REG_6__SCAN_IN),
    .ZN(_153_)
  );
  NOR2_X1 _450_ (
    .A1(_016_),
    .A2(_153_),
    .ZN(_154_)
  );
  XOR2_X1 _451_ (
    .A(_152_),
    .B(_154_),
    .Z(_155_)
  );
  AOI22_X1 _452_ (
    .A1(CONT1_REG_6__SCAN_IN),
    .A2(_060_),
    .B1(_062_),
    .B2(_155_),
    .ZN(_156_)
  );
  OAI211_X1 _453_ (
    .A(_241_),
    .B(_074_),
    .C1(_143_),
    .C2(CONT1_REG_6__SCAN_IN),
    .ZN(_157_)
  );
  AND2_X1 _454_ (
    .A1(CONT1_REG_6__SCAN_IN),
    .A2(_143_),
    .ZN(_158_)
  );
  OAI21_X1 _455_ (
    .A(_156_),
    .B1(_157_),
    .B2(_158_),
    .ZN(_159_)
  );
  AOI21_X1 _456_ (
    .A(_131_),
    .B1(_133_),
    .B2(_137_),
    .ZN(_160_)
  );
  XOR2_X1 _457_ (
    .A(_250_),
    .B(CONT1_REG_6__SCAN_IN),
    .Z(_161_)
  );
  XNOR2_X1 _458_ (
    .A(_160_),
    .B(_161_),
    .ZN(_162_)
  );
  NOR2_X1 _459_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_061_),
    .ZN(_163_)
  );
  AOI221_X1 _460_ (
    .A(_159_),
    .B1(_162_),
    .B2(_163_),
    .C1(CONT_REG_5__SCAN_IN),
    .C2(_066_),
    .ZN(_164_)
  );
  OAI211_X1 _461_ (
    .A(_230_),
    .B(_227_),
    .C1(_043_),
    .C2(_146_),
    .ZN(_165_)
  );
  AOI21_X1 _462_ (
    .A(_153_),
    .B1(_148_),
    .B2(_165_),
    .ZN(_166_)
  );
  AND3_X1 _463_ (
    .A1(_153_),
    .A2(_148_),
    .A3(_165_),
    .ZN(_167_)
  );
  NOR2_X1 _464_ (
    .A1(_166_),
    .A2(_167_),
    .ZN(_168_)
  );
  XNOR2_X1 _465_ (
    .A(_230_),
    .B(_168_),
    .ZN(_169_)
  );
  OAI21_X1 _466_ (
    .A(_164_),
    .B1(_169_),
    .B2(_225_),
    .ZN(U376)
  );
  NAND2_X1 _467_ (
    .A1(CONT1_REG_7__SCAN_IN),
    .A2(_158_),
    .ZN(_170_)
  );
  AOI21_X1 _468_ (
    .A(_060_),
    .B1(_170_),
    .B2(_014_),
    .ZN(_171_)
  );
  NAND3_X1 _469_ (
    .A1(_241_),
    .A2(_074_),
    .A3(_158_),
    .ZN(_172_)
  );
  INV_X1 _470_ (
    .A(CONT1_REG_7__SCAN_IN),
    .ZN(_173_)
  );
  AOI21_X1 _471_ (
    .A(_171_),
    .B1(_172_),
    .B2(_173_),
    .ZN(_174_)
  );
  NOR3_X1 _472_ (
    .A1(_043_),
    .A2(_044_),
    .A3(_154_),
    .ZN(_175_)
  );
  AOI21_X1 _473_ (
    .A(_175_),
    .B1(_043_),
    .B2(_016_),
    .ZN(_176_)
  );
  NAND2_X1 _474_ (
    .A1(_018_),
    .A2(CONT1_REG_7__SCAN_IN),
    .ZN(_177_)
  );
  NAND2_X1 _475_ (
    .A1(_016_),
    .A2(_043_),
    .ZN(_178_)
  );
  AOI21_X1 _476_ (
    .A(_176_),
    .B1(_177_),
    .B2(_178_),
    .ZN(_179_)
  );
  NAND2_X1 _477_ (
    .A1(_178_),
    .A2(_177_),
    .ZN(_180_)
  );
  OAI21_X1 _478_ (
    .A(_062_),
    .B1(_175_),
    .B2(_180_),
    .ZN(_181_)
  );
  NOR2_X1 _479_ (
    .A1(_179_),
    .A2(_181_),
    .ZN(_182_)
  );
  AOI211_X1 _480_ (
    .A(_131_),
    .B(_161_),
    .C1(_137_),
    .C2(_133_),
    .ZN(_183_)
  );
  XNOR2_X1 _481_ (
    .A(_250_),
    .B(CONT1_REG_7__SCAN_IN),
    .ZN(_184_)
  );
  XOR2_X1 _482_ (
    .A(_183_),
    .B(_184_),
    .Z(_185_)
  );
  AOI211_X1 _483_ (
    .A(_174_),
    .B(_182_),
    .C1(_163_),
    .C2(_185_),
    .ZN(_186_)
  );
  NAND3_X1 _484_ (
    .A1(_153_),
    .A2(_148_),
    .A3(_165_),
    .ZN(_187_)
  );
  AOI21_X1 _485_ (
    .A(_166_),
    .B1(_187_),
    .B2(_230_),
    .ZN(_188_)
  );
  XNOR2_X1 _486_ (
    .A(CONT1_REG_7__SCAN_IN),
    .B(_188_),
    .ZN(_189_)
  );
  XNOR2_X1 _487_ (
    .A(_230_),
    .B(_189_),
    .ZN(_190_)
  );
  OAI21_X1 _488_ (
    .A(_186_),
    .B1(_190_),
    .B2(_225_),
    .ZN(U377)
  );
  XOR2_X1 _489_ (
    .A(_250_),
    .B(CONT1_REG_8__SCAN_IN),
    .Z(_191_)
  );
  AOI21_X1 _490_ (
    .A(_191_),
    .B1(_184_),
    .B2(_183_),
    .ZN(_192_)
  );
  AND3_X1 _491_ (
    .A1(_183_),
    .A2(_184_),
    .A3(_191_),
    .ZN(_193_)
  );
  OAI21_X1 _492_ (
    .A(_163_),
    .B1(_192_),
    .B2(_193_),
    .ZN(_194_)
  );
  NOR3_X1 _493_ (
    .A1(CONT1_REG_8__SCAN_IN),
    .A2(_115_),
    .A3(_170_),
    .ZN(_195_)
  );
  NOR2_X1 _494_ (
    .A1(_242_),
    .A2(_171_),
    .ZN(_196_)
  );
  AOI21_X1 _495_ (
    .A(_176_),
    .B1(CONT1_REG_7__SCAN_IN),
    .B2(_018_),
    .ZN(_197_)
  );
  OAI21_X1 _496_ (
    .A(_178_),
    .B1(_242_),
    .B2(_016_),
    .ZN(_198_)
  );
  XOR2_X1 _497_ (
    .A(_197_),
    .B(_198_),
    .Z(_199_)
  );
  AOI211_X1 _498_ (
    .A(_195_),
    .B(_196_),
    .C1(_062_),
    .C2(_199_),
    .ZN(_200_)
  );
  AOI21_X1 _499_ (
    .A(_230_),
    .B1(CONT1_REG_7__SCAN_IN),
    .B2(_166_),
    .ZN(_201_)
  );
  AOI21_X1 _500_ (
    .A(_229_),
    .B1(_173_),
    .B2(_167_),
    .ZN(_202_)
  );
  NOR2_X1 _501_ (
    .A1(_201_),
    .A2(_202_),
    .ZN(_203_)
  );
  XNOR2_X1 _502_ (
    .A(CONT1_REG_8__SCAN_IN),
    .B(_203_),
    .ZN(_204_)
  );
  OAI211_X1 _503_ (
    .A(_194_),
    .B(_200_),
    .C1(_225_),
    .C2(_204_),
    .ZN(U378)
  );
  INV_X1 _504_ (
    .A(CONT_REG_5__SCAN_IN),
    .ZN(_205_)
  );
  NOR3_X1 _505_ (
    .A1(CONT_REG_0__SCAN_IN),
    .A2(CONT_REG_1__SCAN_IN),
    .A3(CONT_REG_2__SCAN_IN),
    .ZN(_206_)
  );
  NAND2_X1 _506_ (
    .A1(CONT_REG_3__SCAN_IN),
    .A2(CONT_REG_4__SCAN_IN),
    .ZN(_207_)
  );
  OAI21_X1 _507_ (
    .A(_205_),
    .B1(_206_),
    .B2(_207_),
    .ZN(_208_)
  );
  OR4_X1 _508_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_235_),
    .A3(_237_),
    .A4(_208_),
    .ZN(_209_)
  );
  INV_X1 _509_ (
    .A(_209_),
    .ZN(_210_)
  );
  NOR2_X1 _510_ (
    .A1(STATO_REG_0__SCAN_IN),
    .A2(_238_),
    .ZN(_211_)
  );
  NOR2_X1 _511_ (
    .A1(_016_),
    .A2(_012_),
    .ZN(_212_)
  );
  NOR2_X1 _512_ (
    .A1(_211_),
    .A2(_212_),
    .ZN(_213_)
  );
  MUX2_X1 _513_ (
    .A(_210_),
    .B(_213_),
    .S(CONT_REG_0__SCAN_IN),
    .Z(U379)
  );
  NAND2_X1 _514_ (
    .A1(CONT_REG_1__SCAN_IN),
    .A2(_213_),
    .ZN(_214_)
  );
  XNOR2_X1 _515_ (
    .A(CONT_REG_0__SCAN_IN),
    .B(CONT_REG_1__SCAN_IN),
    .ZN(_215_)
  );
  OAI21_X1 _516_ (
    .A(_214_),
    .B1(_215_),
    .B2(_209_),
    .ZN(U380)
  );
  INV_X1 _517_ (
    .A(CONT_REG_2__SCAN_IN),
    .ZN(_216_)
  );
  AND3_X1 _518_ (
    .A1(CONT_REG_0__SCAN_IN),
    .A2(CONT_REG_1__SCAN_IN),
    .A3(CONT_REG_2__SCAN_IN),
    .ZN(_217_)
  );
  AOI21_X1 _519_ (
    .A(CONT_REG_2__SCAN_IN),
    .B1(CONT_REG_1__SCAN_IN),
    .B2(CONT_REG_0__SCAN_IN),
    .ZN(_218_)
  );
  OAI33_X1 _520_ (
    .A1(_216_),
    .A2(_211_),
    .A3(_212_),
    .B1(_209_),
    .B2(_217_),
    .B3(_218_),
    .ZN(U381)
  );
  NAND2_X1 _521_ (
    .A1(CONT_REG_3__SCAN_IN),
    .A2(_217_),
    .ZN(_219_)
  );
  AOI21_X1 _522_ (
    .A(_213_),
    .B1(_210_),
    .B2(_219_),
    .ZN(_220_)
  );
  AOI21_X1 _523_ (
    .A(CONT_REG_3__SCAN_IN),
    .B1(_210_),
    .B2(_217_),
    .ZN(_221_)
  );
  NOR2_X1 _524_ (
    .A1(_220_),
    .A2(_221_),
    .ZN(U382)
  );
  INV_X1 _525_ (
    .A(CONT_REG_4__SCAN_IN),
    .ZN(_222_)
  );
  OAI22_X1 _526_ (
    .A1(_209_),
    .A2(_219_),
    .B1(_220_),
    .B2(_222_),
    .ZN(U383)
  );
  NOR3_X1 _527_ (
    .A1(_205_),
    .A2(_211_),
    .A3(_212_),
    .ZN(U384)
  );
  NOR3_X1 _528_ (
    .A1(_224_),
    .A2(STATO_REG_1__SCAN_IN),
    .A3(_016_),
    .ZN(_223_)
  );
  MUX2_X1 _529_ (
    .A(R_IN_REG_5__SCAN_IN),
    .B(X_IN_5_),
    .S(_223_),
    .Z(U404)
  );
  MUX2_X1 _530_ (
    .A(R_IN_REG_4__SCAN_IN),
    .B(X_IN_4_),
    .S(_223_),
    .Z(U405)
  );
  MUX2_X1 _531_ (
    .A(_229_),
    .B(X_IN_3_),
    .S(_223_),
    .Z(U406)
  );
  MUX2_X1 _532_ (
    .A(_226_),
    .B(X_IN_2_),
    .S(_223_),
    .Z(U407)
  );
  MUX2_X1 _533_ (
    .A(_250_),
    .B(X_IN_1_),
    .S(_223_),
    .Z(U408)
  );
  MUX2_X1 _534_ (
    .A(R_IN_REG_0__SCAN_IN),
    .B(X_IN_0_),
    .S(_223_),
    .Z(U409)
  );
endmodule
