/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module b13_C(EOC, DATA_IN_7_, DATA_IN_6_, DATA_IN_5_, DATA_IN_4_, DATA_IN_3_, DATA_IN_2_, DATA_IN_1_, DATA_IN_0_, DSR, TX_END_REG_SCAN_IN, S2_REG_0__SCAN_IN, S2_REG_1__SCAN_IN, CANALE_REG_3__SCAN_IN, CANALE_REG_2__SCAN_IN, CANALE_REG_1__SCAN_IN, CANALE_REG_0__SCAN_IN, CONTA_TMP_REG_3__SCAN_IN, CONTA_TMP_REG_2__SCAN_IN, CONTA_TMP_REG_1__SCAN_IN
, CONTA_TMP_REG_0__SCAN_IN, ITFC_STATE_REG_1__SCAN_IN, ITFC_STATE_REG_0__SCAN_IN, OUT_REG_REG_7__SCAN_IN, OUT_REG_REG_6__SCAN_IN, OUT_REG_REG_5__SCAN_IN, OUT_REG_REG_4__SCAN_IN, OUT_REG_REG_3__SCAN_IN, OUT_REG_REG_2__SCAN_IN, OUT_REG_REG_1__SCAN_IN, OUT_REG_REG_0__SCAN_IN, NEXT_BIT_REG_3__SCAN_IN, NEXT_BIT_REG_2__SCAN_IN, NEXT_BIT_REG_1__SCAN_IN, NEXT_BIT_REG_0__SCAN_IN, TX_CONTA_REG_9__SCAN_IN, TX_CONTA_REG_8__SCAN_IN, TX_CONTA_REG_7__SCAN_IN, TX_CONTA_REG_6__SCAN_IN, TX_CONTA_REG_5__SCAN_IN, TX_CONTA_REG_4__SCAN_IN
, TX_CONTA_REG_3__SCAN_IN, TX_CONTA_REG_2__SCAN_IN, TX_CONTA_REG_1__SCAN_IN, TX_CONTA_REG_0__SCAN_IN, LOAD_REG_SCAN_IN, SEND_DATA_REG_SCAN_IN, SEND_EN_REG_SCAN_IN, MUX_EN_REG_SCAN_IN, TRE_REG_SCAN_IN, LOAD_DATO_REG_SCAN_IN, SOC_REG_SCAN_IN, SEND_REG_SCAN_IN, MPX_REG_SCAN_IN, CONFIRM_REG_SCAN_IN, SHOT_REG_SCAN_IN, ADD_MPX2_REG_SCAN_IN, RDY_REG_SCAN_IN, ERROR_REG_SCAN_IN, S1_REG_2__SCAN_IN, S1_REG_1__SCAN_IN, S1_REG_0__SCAN_IN
, U416, U415, U414, U413, U417, U412, U411, U410, U452, U409, U453, U454, U455, U456, U457, U458, U459, U460, U461, U408, U407
, U462, U406, U405, U404, U403, U402, U401, U400, U399, U398, U397, U396, U395, U394, U393, U392, U391, U450, U390, U389, U388
, U387, U386, U385, U451, U383, U464, U384, U463, U382, U381, U380);
  input EOC;
  wire EOC;
  
  input DATA_IN_7_;
  wire DATA_IN_7_;
  input DATA_IN_6_;
  wire DATA_IN_6_;
  input DATA_IN_5_;
  wire DATA_IN_5_;
  input DATA_IN_4_;
  wire DATA_IN_4_;
  input DATA_IN_3_;
  wire DATA_IN_3_;
  input DATA_IN_2_;
  wire DATA_IN_2_;
  input DATA_IN_1_;
  wire DATA_IN_1_;
  input DATA_IN_0_;
  wire DATA_IN_0_;
  input DSR;
  wire DSR;
  input TX_END_REG_SCAN_IN;
  wire TX_END_REG_SCAN_IN;
  input S2_REG_0__SCAN_IN;
  wire S2_REG_0__SCAN_IN;
  input S2_REG_1__SCAN_IN;
  wire S2_REG_1__SCAN_IN;
  input CANALE_REG_3__SCAN_IN;
  wire CANALE_REG_3__SCAN_IN;
  input CANALE_REG_2__SCAN_IN;
  wire CANALE_REG_2__SCAN_IN;
  input CANALE_REG_1__SCAN_IN;
  wire CANALE_REG_1__SCAN_IN;
  input CANALE_REG_0__SCAN_IN;
  wire CANALE_REG_0__SCAN_IN;
  input CONTA_TMP_REG_3__SCAN_IN;
  wire CONTA_TMP_REG_3__SCAN_IN;
  input CONTA_TMP_REG_2__SCAN_IN;
  wire CONTA_TMP_REG_2__SCAN_IN;
  input CONTA_TMP_REG_1__SCAN_IN;
  wire CONTA_TMP_REG_1__SCAN_IN;
  input CONTA_TMP_REG_0__SCAN_IN;
  wire CONTA_TMP_REG_0__SCAN_IN;
  input ITFC_STATE_REG_1__SCAN_IN;
  wire ITFC_STATE_REG_1__SCAN_IN;
  input ITFC_STATE_REG_0__SCAN_IN;
  wire ITFC_STATE_REG_0__SCAN_IN;
  input OUT_REG_REG_7__SCAN_IN;
  wire OUT_REG_REG_7__SCAN_IN;
  input OUT_REG_REG_6__SCAN_IN;
  wire OUT_REG_REG_6__SCAN_IN;
  input OUT_REG_REG_5__SCAN_IN;
  wire OUT_REG_REG_5__SCAN_IN;
  input OUT_REG_REG_4__SCAN_IN;
  wire OUT_REG_REG_4__SCAN_IN;
  input OUT_REG_REG_3__SCAN_IN;
  wire OUT_REG_REG_3__SCAN_IN;
  input OUT_REG_REG_2__SCAN_IN;
  wire OUT_REG_REG_2__SCAN_IN;
  input OUT_REG_REG_1__SCAN_IN;
  wire OUT_REG_REG_1__SCAN_IN;
  input OUT_REG_REG_0__SCAN_IN;
  wire OUT_REG_REG_0__SCAN_IN;
  input NEXT_BIT_REG_3__SCAN_IN;
  wire NEXT_BIT_REG_3__SCAN_IN;
  input NEXT_BIT_REG_2__SCAN_IN;
  wire NEXT_BIT_REG_2__SCAN_IN;
  input NEXT_BIT_REG_1__SCAN_IN;
  wire NEXT_BIT_REG_1__SCAN_IN;
  input NEXT_BIT_REG_0__SCAN_IN;
  wire NEXT_BIT_REG_0__SCAN_IN;
  input TX_CONTA_REG_9__SCAN_IN;
  wire TX_CONTA_REG_9__SCAN_IN;
  input TX_CONTA_REG_8__SCAN_IN;
  wire TX_CONTA_REG_8__SCAN_IN;
  input TX_CONTA_REG_7__SCAN_IN;
  wire TX_CONTA_REG_7__SCAN_IN;
  input TX_CONTA_REG_6__SCAN_IN;
  wire TX_CONTA_REG_6__SCAN_IN;
  input TX_CONTA_REG_5__SCAN_IN;
  wire TX_CONTA_REG_5__SCAN_IN;
  input TX_CONTA_REG_4__SCAN_IN;
  wire TX_CONTA_REG_4__SCAN_IN;
  input TX_CONTA_REG_3__SCAN_IN;
  wire TX_CONTA_REG_3__SCAN_IN;
  input TX_CONTA_REG_2__SCAN_IN;
  wire TX_CONTA_REG_2__SCAN_IN;
  input TX_CONTA_REG_1__SCAN_IN;
  wire TX_CONTA_REG_1__SCAN_IN;
  input TX_CONTA_REG_0__SCAN_IN;
  wire TX_CONTA_REG_0__SCAN_IN;
  input LOAD_REG_SCAN_IN;
  wire LOAD_REG_SCAN_IN;
  input SEND_DATA_REG_SCAN_IN;
  wire SEND_DATA_REG_SCAN_IN;
  input SEND_EN_REG_SCAN_IN;
  wire SEND_EN_REG_SCAN_IN;
  input MUX_EN_REG_SCAN_IN;
  wire MUX_EN_REG_SCAN_IN;
  input TRE_REG_SCAN_IN;
  wire TRE_REG_SCAN_IN;
  input LOAD_DATO_REG_SCAN_IN;
  wire LOAD_DATO_REG_SCAN_IN;
  input SOC_REG_SCAN_IN;
  wire SOC_REG_SCAN_IN;
  input SEND_REG_SCAN_IN;
  wire SEND_REG_SCAN_IN;
  input MPX_REG_SCAN_IN;
  wire MPX_REG_SCAN_IN;
  input CONFIRM_REG_SCAN_IN;
  wire CONFIRM_REG_SCAN_IN;
  input SHOT_REG_SCAN_IN;
  wire SHOT_REG_SCAN_IN;
  input ADD_MPX2_REG_SCAN_IN;
  wire ADD_MPX2_REG_SCAN_IN;
  input RDY_REG_SCAN_IN;
  wire RDY_REG_SCAN_IN;
  input ERROR_REG_SCAN_IN;
  wire ERROR_REG_SCAN_IN;
  input S1_REG_2__SCAN_IN;
  wire S1_REG_2__SCAN_IN;
  input S1_REG_1__SCAN_IN;
  wire S1_REG_1__SCAN_IN;
  input S1_REG_0__SCAN_IN;
  wire S1_REG_0__SCAN_IN;
  output U416;
  wire U416;
  output U415;
  wire U415;
  output U414;
  wire U414;
  output U413;
  wire U413;
  output U417;
  wire U417;
  output U412;
  wire U412;
  output U411;
  wire U411;
  output U410;
  wire U410;
  output U452;
  wire U452;
  output U409;
  wire U409;
  output U453;
  wire U453;
  output U454;
  wire U454;
  output U455;
  wire U455;
  output U456;
  wire U456;
  output U457;
  wire U457;
  output U458;
  wire U458;
  output U459;
  wire U459;
  output U460;
  wire U460;
  output U461;
  wire U461;
  output U408;
  wire U408;
  output U407;
  wire U407;
  output U462;
  wire U462;
  output U406;
  wire U406;
  output U405;
  wire U405;
  output U404;
  wire U404;
  output U403;
  wire U403;
  output U402;
  wire U402;
  output U401;
  wire U401;
  output U400;
  wire U400;
  output U399;
  wire U399;
  output U398;
  wire U398;
  output U397;
  wire U397;
  output U396;
  wire U396;
  output U395;
  wire U395;
  output U394;
  wire U394;
  output U393;
  wire U393;
  output U392;
  wire U392;
  output U391;
  wire U391;
  output U450;
  wire U450;
  output U390;
  wire U390;
  output U389;
  wire U389;
  output U388;
  wire U388;
  output U387;
  wire U387;
  output U386;
  wire U386;
  output U385;
  wire U385;
  output U451;
  wire U451;
  output U383;
  wire U383;
  output U464;
  wire U464;
  output U384;
  wire U384;
  output U463;
  wire U463;
  output U382;
  wire U382;
  output U381;
  wire U381;
  output U380;
  wire U380;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  NOR3_X1 _094_ (
    .A1(TX_CONTA_REG_7__SCAN_IN),
    .A2(TX_CONTA_REG_8__SCAN_IN),
    .A3(TX_CONTA_REG_9__SCAN_IN),
    .ZN(_000_)
  );
  NAND2_X1 _095_ (
    .A1(TX_CONTA_REG_5__SCAN_IN),
    .A2(TX_CONTA_REG_6__SCAN_IN),
    .ZN(_001_)
  );
  OR3_X1 _096_ (
    .A1(TX_CONTA_REG_0__SCAN_IN),
    .A2(TX_CONTA_REG_1__SCAN_IN),
    .A3(TX_CONTA_REG_2__SCAN_IN),
    .ZN(_002_)
  );
  AOI21_X1 _097_ (
    .A(TX_CONTA_REG_4__SCAN_IN),
    .B1(_002_),
    .B2(TX_CONTA_REG_3__SCAN_IN),
    .ZN(_003_)
  );
  OAI21_X1 _098_ (
    .A(_000_),
    .B1(_001_),
    .B2(_003_),
    .ZN(_004_)
  );
  AND2_X1 _099_ (
    .A1(SEND_EN_REG_SCAN_IN),
    .A2(_004_),
    .ZN(_005_)
  );
  INV_X1 _100_ (
    .A(NEXT_BIT_REG_0__SCAN_IN),
    .ZN(_006_)
  );
  NOR3_X1 _101_ (
    .A1(NEXT_BIT_REG_3__SCAN_IN),
    .A2(NEXT_BIT_REG_1__SCAN_IN),
    .A3(NEXT_BIT_REG_2__SCAN_IN),
    .ZN(_007_)
  );
  AOI211_X1 _102_ (
    .A(_006_),
    .B(_007_),
    .C1(NEXT_BIT_REG_3__SCAN_IN),
    .C2(OUT_REG_REG_0__SCAN_IN),
    .ZN(_008_)
  );
  AND2_X1 _103_ (
    .A1(NEXT_BIT_REG_1__SCAN_IN),
    .A2(NEXT_BIT_REG_2__SCAN_IN),
    .ZN(_009_)
  );
  NAND2_X1 _104_ (
    .A1(OUT_REG_REG_2__SCAN_IN),
    .A2(_009_),
    .ZN(_010_)
  );
  INV_X1 _105_ (
    .A(NEXT_BIT_REG_1__SCAN_IN),
    .ZN(_011_)
  );
  NAND3_X1 _106_ (
    .A1(OUT_REG_REG_4__SCAN_IN),
    .A2(_011_),
    .A3(NEXT_BIT_REG_2__SCAN_IN),
    .ZN(_012_)
  );
  INV_X1 _107_ (
    .A(NEXT_BIT_REG_2__SCAN_IN),
    .ZN(_013_)
  );
  NAND3_X1 _108_ (
    .A1(OUT_REG_REG_6__SCAN_IN),
    .A2(NEXT_BIT_REG_1__SCAN_IN),
    .A3(_013_),
    .ZN(_014_)
  );
  NAND4_X1 _109_ (
    .A1(_008_),
    .A2(_010_),
    .A3(_012_),
    .A4(_014_),
    .ZN(_015_)
  );
  AOI221_X1 _110_ (
    .A(NEXT_BIT_REG_0__SCAN_IN),
    .B1(NEXT_BIT_REG_3__SCAN_IN),
    .B2(OUT_REG_REG_1__SCAN_IN),
    .C1(_009_),
    .C2(OUT_REG_REG_3__SCAN_IN),
    .ZN(_016_)
  );
  NAND3_X1 _111_ (
    .A1(OUT_REG_REG_7__SCAN_IN),
    .A2(NEXT_BIT_REG_1__SCAN_IN),
    .A3(_013_),
    .ZN(_017_)
  );
  NAND3_X1 _112_ (
    .A1(OUT_REG_REG_5__SCAN_IN),
    .A2(_011_),
    .A3(NEXT_BIT_REG_2__SCAN_IN),
    .ZN(_018_)
  );
  NAND3_X1 _113_ (
    .A1(_016_),
    .A2(_017_),
    .A3(_018_),
    .ZN(_019_)
  );
  NAND2_X1 _114_ (
    .A1(_015_),
    .A2(_019_),
    .ZN(_020_)
  );
  NAND2_X1 _115_ (
    .A1(_005_),
    .A2(_020_),
    .ZN(U380)
  );
  AND3_X1 _116_ (
    .A1(NEXT_BIT_REG_0__SCAN_IN),
    .A2(SEND_EN_REG_SCAN_IN),
    .A3(_004_),
    .ZN(_021_)
  );
  AND2_X1 _117_ (
    .A1(_007_),
    .A2(_021_),
    .ZN(U381)
  );
  INV_X1 _118_ (
    .A(SEND_DATA_REG_SCAN_IN),
    .ZN(_022_)
  );
  OR3_X1 _119_ (
    .A1(_022_),
    .A2(S2_REG_1__SCAN_IN),
    .A3(S2_REG_0__SCAN_IN),
    .ZN(_023_)
  );
  INV_X1 _120_ (
    .A(S2_REG_0__SCAN_IN),
    .ZN(_024_)
  );
  NAND3_X1 _121_ (
    .A1(S2_REG_1__SCAN_IN),
    .A2(_024_),
    .A3(CONFIRM_REG_SCAN_IN),
    .ZN(_025_)
  );
  NAND2_X1 _122_ (
    .A1(_023_),
    .A2(_025_),
    .ZN(U382)
  );
  NAND2_X1 _123_ (
    .A1(S1_REG_2__SCAN_IN),
    .A2(S1_REG_0__SCAN_IN),
    .ZN(_026_)
  );
  INV_X1 _124_ (
    .A(S1_REG_1__SCAN_IN),
    .ZN(_027_)
  );
  OAI21_X1 _125_ (
    .A(_026_),
    .B1(S1_REG_0__SCAN_IN),
    .B2(_027_),
    .ZN(U383)
  );
  NOR2_X1 _126_ (
    .A1(S1_REG_1__SCAN_IN),
    .A2(S1_REG_2__SCAN_IN),
    .ZN(_028_)
  );
  NOR2_X1 _127_ (
    .A1(S1_REG_2__SCAN_IN),
    .A2(RDY_REG_SCAN_IN),
    .ZN(_029_)
  );
  AOI21_X1 _128_ (
    .A(_029_),
    .B1(EOC),
    .B2(_027_),
    .ZN(_030_)
  );
  OAI21_X1 _129_ (
    .A(S1_REG_0__SCAN_IN),
    .B1(_028_),
    .B2(_030_),
    .ZN(U384)
  );
  INV_X1 _130_ (
    .A(MPX_REG_SCAN_IN),
    .ZN(_031_)
  );
  OAI21_X1 _131_ (
    .A(RDY_REG_SCAN_IN),
    .B1(_031_),
    .B2(_025_),
    .ZN(_032_)
  );
  NAND2_X1 _132_ (
    .A1(_023_),
    .A2(_032_),
    .ZN(U385)
  );
  INV_X1 _133_ (
    .A(ADD_MPX2_REG_SCAN_IN),
    .ZN(_033_)
  );
  OAI21_X1 _134_ (
    .A(_033_),
    .B1(_025_),
    .B2(MPX_REG_SCAN_IN),
    .ZN(U386)
  );
  NAND2_X1 _135_ (
    .A1(S2_REG_1__SCAN_IN),
    .A2(_024_),
    .ZN(_034_)
  );
  OAI21_X1 _136_ (
    .A(SHOT_REG_SCAN_IN),
    .B1(CONFIRM_REG_SCAN_IN),
    .B2(_034_),
    .ZN(_035_)
  );
  OR2_X1 _137_ (
    .A1(S2_REG_1__SCAN_IN),
    .A2(_024_),
    .ZN(_036_)
  );
  NAND2_X1 _138_ (
    .A1(_035_),
    .A2(_036_),
    .ZN(U387)
  );
  OAI21_X1 _139_ (
    .A(CONFIRM_REG_SCAN_IN),
    .B1(ITFC_STATE_REG_0__SCAN_IN),
    .B2(ITFC_STATE_REG_1__SCAN_IN),
    .ZN(_037_)
  );
  NAND3_X1 _140_ (
    .A1(TX_END_REG_SCAN_IN),
    .A2(ITFC_STATE_REG_0__SCAN_IN),
    .A3(ITFC_STATE_REG_1__SCAN_IN),
    .ZN(_038_)
  );
  NAND2_X1 _141_ (
    .A1(_037_),
    .A2(_038_),
    .ZN(U388)
  );
  XNOR2_X1 _142_ (
    .A(MPX_REG_SCAN_IN),
    .B(_025_),
    .ZN(U389)
  );
  INV_X1 _143_ (
    .A(ITFC_STATE_REG_0__SCAN_IN),
    .ZN(_039_)
  );
  NOR2_X1 _144_ (
    .A1(_039_),
    .A2(ITFC_STATE_REG_1__SCAN_IN),
    .ZN(_040_)
  );
  NOR2_X1 _145_ (
    .A1(SEND_REG_SCAN_IN),
    .A2(_040_),
    .ZN(_041_)
  );
  AOI21_X1 _146_ (
    .A(_041_),
    .B1(ITFC_STATE_REG_1__SCAN_IN),
    .B2(_039_),
    .ZN(U390)
  );
  NOR3_X1 _147_ (
    .A1(S1_REG_1__SCAN_IN),
    .A2(EOC),
    .A3(_026_),
    .ZN(_042_)
  );
  INV_X1 _148_ (
    .A(S1_REG_0__SCAN_IN),
    .ZN(_043_)
  );
  NAND3_X1 _149_ (
    .A1(S1_REG_1__SCAN_IN),
    .A2(S1_REG_2__SCAN_IN),
    .A3(_043_),
    .ZN(_044_)
  );
  AOI21_X1 _150_ (
    .A(_042_),
    .B1(_044_),
    .B2(LOAD_DATO_REG_SCAN_IN),
    .ZN(_045_)
  );
  INV_X1 _151_ (
    .A(_045_),
    .ZN(U391)
  );
  OR3_X1 _152_ (
    .A1(TX_END_REG_SCAN_IN),
    .A2(LOAD_REG_SCAN_IN),
    .A3(TRE_REG_SCAN_IN),
    .ZN(U392)
  );
  INV_X1 _153_ (
    .A(MUX_EN_REG_SCAN_IN),
    .ZN(_046_)
  );
  NOR2_X1 _154_ (
    .A1(_046_),
    .A2(_042_),
    .ZN(_047_)
  );
  AOI21_X1 _155_ (
    .A(_047_),
    .B1(_028_),
    .B2(_043_),
    .ZN(_048_)
  );
  INV_X1 _156_ (
    .A(_048_),
    .ZN(U393)
  );
  NAND3_X1 _157_ (
    .A1(SEND_REG_SCAN_IN),
    .A2(TRE_REG_SCAN_IN),
    .A3(DSR),
    .ZN(_049_)
  );
  INV_X1 _158_ (
    .A(SEND_EN_REG_SCAN_IN),
    .ZN(_050_)
  );
  OAI21_X1 _159_ (
    .A(_049_),
    .B1(_050_),
    .B2(TX_END_REG_SCAN_IN),
    .ZN(U394)
  );
  AND3_X1 _160_ (
    .A1(S1_REG_1__SCAN_IN),
    .A2(S1_REG_0__SCAN_IN),
    .A3(RDY_REG_SCAN_IN),
    .ZN(_051_)
  );
  OAI22_X1 _161_ (
    .A1(_027_),
    .A2(_026_),
    .B1(_051_),
    .B2(_022_),
    .ZN(U395)
  );
  INV_X1 _162_ (
    .A(LOAD_REG_SCAN_IN),
    .ZN(_052_)
  );
  NAND2_X1 _163_ (
    .A1(SHOT_REG_SCAN_IN),
    .A2(_039_),
    .ZN(_053_)
  );
  OAI22_X1 _164_ (
    .A1(_052_),
    .A2(_040_),
    .B1(_053_),
    .B2(ITFC_STATE_REG_1__SCAN_IN),
    .ZN(U396)
  );
  XNOR2_X1 _165_ (
    .A(SEND_EN_REG_SCAN_IN),
    .B(TX_CONTA_REG_0__SCAN_IN),
    .ZN(_054_)
  );
  NOR2_X1 _166_ (
    .A1(_005_),
    .A2(_054_),
    .ZN(U397)
  );
  AOI21_X1 _167_ (
    .A(TX_CONTA_REG_1__SCAN_IN),
    .B1(TX_CONTA_REG_0__SCAN_IN),
    .B2(SEND_EN_REG_SCAN_IN),
    .ZN(_055_)
  );
  AND3_X1 _168_ (
    .A1(SEND_EN_REG_SCAN_IN),
    .A2(TX_CONTA_REG_0__SCAN_IN),
    .A3(TX_CONTA_REG_1__SCAN_IN),
    .ZN(_056_)
  );
  NOR3_X1 _169_ (
    .A1(_005_),
    .A2(_055_),
    .A3(_056_),
    .ZN(U398)
  );
  NOR2_X1 _170_ (
    .A1(TX_CONTA_REG_2__SCAN_IN),
    .A2(_056_),
    .ZN(_057_)
  );
  AND4_X1 _171_ (
    .A1(SEND_EN_REG_SCAN_IN),
    .A2(TX_CONTA_REG_0__SCAN_IN),
    .A3(TX_CONTA_REG_1__SCAN_IN),
    .A4(TX_CONTA_REG_2__SCAN_IN),
    .ZN(_058_)
  );
  NOR3_X1 _172_ (
    .A1(_005_),
    .A2(_057_),
    .A3(_058_),
    .ZN(U399)
  );
  NOR2_X1 _173_ (
    .A1(TX_CONTA_REG_3__SCAN_IN),
    .A2(_058_),
    .ZN(_059_)
  );
  AND2_X1 _174_ (
    .A1(TX_CONTA_REG_3__SCAN_IN),
    .A2(_058_),
    .ZN(_060_)
  );
  NOR3_X1 _175_ (
    .A1(_005_),
    .A2(_059_),
    .A3(_060_),
    .ZN(U400)
  );
  NOR2_X1 _176_ (
    .A1(TX_CONTA_REG_4__SCAN_IN),
    .A2(_060_),
    .ZN(_061_)
  );
  AND2_X1 _177_ (
    .A1(TX_CONTA_REG_4__SCAN_IN),
    .A2(_060_),
    .ZN(_062_)
  );
  NOR3_X1 _178_ (
    .A1(_005_),
    .A2(_061_),
    .A3(_062_),
    .ZN(U401)
  );
  XNOR2_X1 _179_ (
    .A(TX_CONTA_REG_5__SCAN_IN),
    .B(_062_),
    .ZN(_063_)
  );
  NOR2_X1 _180_ (
    .A1(_005_),
    .A2(_063_),
    .ZN(U402)
  );
  AOI21_X1 _181_ (
    .A(TX_CONTA_REG_6__SCAN_IN),
    .B1(_062_),
    .B2(TX_CONTA_REG_5__SCAN_IN),
    .ZN(_064_)
  );
  NOR2_X1 _182_ (
    .A1(_005_),
    .A2(_064_),
    .ZN(U403)
  );
  AND2_X1 _183_ (
    .A1(_050_),
    .A2(TX_CONTA_REG_7__SCAN_IN),
    .ZN(U404)
  );
  AND2_X1 _184_ (
    .A1(_050_),
    .A2(TX_CONTA_REG_8__SCAN_IN),
    .ZN(U405)
  );
  AND2_X1 _185_ (
    .A1(_050_),
    .A2(TX_CONTA_REG_9__SCAN_IN),
    .ZN(U406)
  );
  OAI21_X1 _186_ (
    .A(NEXT_BIT_REG_0__SCAN_IN),
    .B1(NEXT_BIT_REG_1__SCAN_IN),
    .B2(_013_),
    .ZN(_065_)
  );
  OAI21_X1 _187_ (
    .A(_006_),
    .B1(NEXT_BIT_REG_3__SCAN_IN),
    .B2(NEXT_BIT_REG_2__SCAN_IN),
    .ZN(_066_)
  );
  NAND2_X1 _188_ (
    .A1(_065_),
    .A2(_066_),
    .ZN(_067_)
  );
  NAND2_X1 _189_ (
    .A1(SEND_EN_REG_SCAN_IN),
    .A2(_004_),
    .ZN(_068_)
  );
  OAI22_X1 _190_ (
    .A1(_011_),
    .A2(_021_),
    .B1(_067_),
    .B2(_068_),
    .ZN(U407)
  );
  NAND4_X1 _191_ (
    .A1(NEXT_BIT_REG_0__SCAN_IN),
    .A2(NEXT_BIT_REG_1__SCAN_IN),
    .A3(SEND_EN_REG_SCAN_IN),
    .A4(_004_),
    .ZN(_069_)
  );
  XNOR2_X1 _192_ (
    .A(NEXT_BIT_REG_2__SCAN_IN),
    .B(_069_),
    .ZN(U408)
  );
  INV_X1 _193_ (
    .A(TX_END_REG_SCAN_IN),
    .ZN(_070_)
  );
  OAI21_X1 _194_ (
    .A(ITFC_STATE_REG_1__SCAN_IN),
    .B1(_039_),
    .B2(_070_),
    .ZN(_071_)
  );
  NAND2_X1 _195_ (
    .A1(_053_),
    .A2(_071_),
    .ZN(U409)
  );
  XNOR2_X1 _196_ (
    .A(CONTA_TMP_REG_0__SCAN_IN),
    .B(_044_),
    .ZN(U410)
  );
  AND3_X1 _197_ (
    .A1(S1_REG_1__SCAN_IN),
    .A2(S1_REG_2__SCAN_IN),
    .A3(_043_),
    .ZN(_072_)
  );
  AOI21_X1 _198_ (
    .A(CONTA_TMP_REG_1__SCAN_IN),
    .B1(_072_),
    .B2(CONTA_TMP_REG_0__SCAN_IN),
    .ZN(_073_)
  );
  AND2_X1 _199_ (
    .A1(CONTA_TMP_REG_0__SCAN_IN),
    .A2(CONTA_TMP_REG_1__SCAN_IN),
    .ZN(_074_)
  );
  AOI21_X1 _200_ (
    .A(_073_),
    .B1(_074_),
    .B2(_072_),
    .ZN(U411)
  );
  AOI21_X1 _201_ (
    .A(_044_),
    .B1(_074_),
    .B2(CONTA_TMP_REG_2__SCAN_IN),
    .ZN(_075_)
  );
  OAI21_X1 _202_ (
    .A(_075_),
    .B1(_074_),
    .B2(CONTA_TMP_REG_2__SCAN_IN),
    .ZN(_076_)
  );
  INV_X1 _203_ (
    .A(CONTA_TMP_REG_2__SCAN_IN),
    .ZN(_077_)
  );
  OAI21_X1 _204_ (
    .A(_076_),
    .B1(_072_),
    .B2(_077_),
    .ZN(U412)
  );
  NOR2_X1 _205_ (
    .A1(CANALE_REG_0__SCAN_IN),
    .A2(_072_),
    .ZN(_078_)
  );
  AOI21_X1 _206_ (
    .A(_078_),
    .B1(_072_),
    .B2(CONTA_TMP_REG_0__SCAN_IN),
    .ZN(U413)
  );
  XOR2_X1 _207_ (
    .A(CONTA_TMP_REG_0__SCAN_IN),
    .B(CONTA_TMP_REG_1__SCAN_IN),
    .Z(_079_)
  );
  MUX2_X1 _208_ (
    .A(CANALE_REG_1__SCAN_IN),
    .B(_079_),
    .S(_072_),
    .Z(U414)
  );
  INV_X1 _209_ (
    .A(CANALE_REG_2__SCAN_IN),
    .ZN(_080_)
  );
  OAI21_X1 _210_ (
    .A(_076_),
    .B1(_072_),
    .B2(_080_),
    .ZN(U415)
  );
  AOI22_X1 _211_ (
    .A1(CANALE_REG_3__SCAN_IN),
    .A2(_044_),
    .B1(_075_),
    .B2(CONTA_TMP_REG_3__SCAN_IN),
    .ZN(_081_)
  );
  INV_X1 _212_ (
    .A(_081_),
    .ZN(U416)
  );
  NAND3_X1 _213_ (
    .A1(CONTA_TMP_REG_2__SCAN_IN),
    .A2(_072_),
    .A3(_074_),
    .ZN(_082_)
  );
  AND2_X1 _214_ (
    .A1(CONTA_TMP_REG_3__SCAN_IN),
    .A2(_082_),
    .ZN(U417)
  );
  AOI21_X1 _215_ (
    .A(SOC_REG_SCAN_IN),
    .B1(_043_),
    .B2(S1_REG_1__SCAN_IN),
    .ZN(_083_)
  );
  NOR2_X1 _216_ (
    .A1(_072_),
    .A2(_083_),
    .ZN(U450)
  );
  NOR2_X1 _217_ (
    .A1(_052_),
    .A2(TRE_REG_SCAN_IN),
    .ZN(_084_)
  );
  INV_X1 _218_ (
    .A(ERROR_REG_SCAN_IN),
    .ZN(_085_)
  );
  AOI21_X1 _219_ (
    .A(_084_),
    .B1(_085_),
    .B2(_052_),
    .ZN(_086_)
  );
  OAI21_X1 _220_ (
    .A(_049_),
    .B1(_086_),
    .B2(SEND_REG_SCAN_IN),
    .ZN(_087_)
  );
  INV_X1 _221_ (
    .A(_087_),
    .ZN(U451)
  );
  OAI21_X1 _222_ (
    .A(_071_),
    .B1(ITFC_STATE_REG_1__SCAN_IN),
    .B2(_039_),
    .ZN(U452)
  );
  MUX2_X1 _223_ (
    .A(OUT_REG_REG_7__SCAN_IN),
    .B(DATA_IN_7_),
    .S(_084_),
    .Z(U453)
  );
  MUX2_X1 _224_ (
    .A(OUT_REG_REG_6__SCAN_IN),
    .B(DATA_IN_6_),
    .S(_084_),
    .Z(U454)
  );
  MUX2_X1 _225_ (
    .A(OUT_REG_REG_5__SCAN_IN),
    .B(DATA_IN_5_),
    .S(_084_),
    .Z(U455)
  );
  MUX2_X1 _226_ (
    .A(OUT_REG_REG_4__SCAN_IN),
    .B(DATA_IN_4_),
    .S(_084_),
    .Z(U456)
  );
  MUX2_X1 _227_ (
    .A(OUT_REG_REG_3__SCAN_IN),
    .B(DATA_IN_3_),
    .S(_084_),
    .Z(U457)
  );
  MUX2_X1 _228_ (
    .A(OUT_REG_REG_2__SCAN_IN),
    .B(DATA_IN_2_),
    .S(_084_),
    .Z(U458)
  );
  MUX2_X1 _229_ (
    .A(OUT_REG_REG_1__SCAN_IN),
    .B(DATA_IN_1_),
    .S(_084_),
    .Z(U459)
  );
  MUX2_X1 _230_ (
    .A(OUT_REG_REG_0__SCAN_IN),
    .B(DATA_IN_0_),
    .S(_084_),
    .Z(U460)
  );
  MUX2_X1 _231_ (
    .A(NEXT_BIT_REG_3__SCAN_IN),
    .B(_009_),
    .S(_021_),
    .Z(U461)
  );
  INV_X1 _232_ (
    .A(NEXT_BIT_REG_3__SCAN_IN),
    .ZN(_088_)
  );
  AOI21_X1 _233_ (
    .A(_007_),
    .B1(_088_),
    .B2(NEXT_BIT_REG_0__SCAN_IN),
    .ZN(_089_)
  );
  MUX2_X1 _234_ (
    .A(NEXT_BIT_REG_0__SCAN_IN),
    .B(_089_),
    .S(_005_),
    .Z(U462)
  );
  AND2_X1 _235_ (
    .A1(_031_),
    .A2(CONFIRM_REG_SCAN_IN),
    .ZN(_090_)
  );
  OAI21_X1 _236_ (
    .A(_036_),
    .B1(_090_),
    .B2(_034_),
    .ZN(U463)
  );
  NOR2_X1 _237_ (
    .A1(_028_),
    .A2(_029_),
    .ZN(_091_)
  );
  OAI211_X1 _238_ (
    .A(S1_REG_0__SCAN_IN),
    .B(_091_),
    .C1(EOC),
    .C2(S1_REG_1__SCAN_IN),
    .ZN(_092_)
  );
  OAI21_X1 _239_ (
    .A(_092_),
    .B1(S1_REG_0__SCAN_IN),
    .B2(S1_REG_2__SCAN_IN),
    .ZN(_093_)
  );
  INV_X1 _240_ (
    .A(_093_),
    .ZN(U464)
  );
endmodule
