/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1;
  wire N1;
  input N2;
  wire N2;
  input N3;
  wire N3;
  input N6;
  wire N6;
  input N7;
  wire N7;
  output N22;
  wire N22;
  output N23;
  wire N23;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  NAND2_X1 _4_ (
    .A1(N1),
    .A2(N3),
    .ZN(_2_)
  );
  AND2_X1 _5_ (
    .A1(N3),
    .A2(N6),
    .ZN(_3_)
  );
  INV_X1 _6_ (
    .A(N2),
    .ZN(_0_)
  );
  OAI21_X1 _7_ (
    .A(_2_),
    .B1(_3_),
    .B2(_0_),
    .ZN(N22)
  );
  INV_X1 _8_ (
    .A(N7),
    .ZN(_1_)
  );
  AOI21_X1 _9_ (
    .A(_3_),
    .B1(_0_),
    .B2(_1_),
    .ZN(N23)
  );
endmodule
